### PR TITLE
Fix serialization order change after #4775 (`@JsonAnyGetter` respects order)

### LINKED ISSUE #5215: `@JsonAnyGetter` serialization order change from 2.18.4 to 2.19.0
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Using `JsonAnyGetter` used to return property's value from this source instead of the field annotated with `JsonProperty` until 2.18.4. Starting with 2.19.0, the behavior changed and now value from property is always returned.

### Version Information

2.19.1

### Reproduction

I am attaching a reproducer with Java 17 https://github.com/eddumelendez/jackson-deserializer-issue with the very exact configuration I use in my project.

### Expected behavior

read the value from `JsonAnyGetter`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JooHyukKim**
Fixes #5215 (caused by #4775)

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java [hunk 1]
```diff
@@ -501,6 +501,28 @@ protected void collectAll()
...
+                anyGetterProp = prop;
+            } else {
+                newAll.put(prop.getName(), prop);
+            }
+        }
+        if (anyGetterProp != null) {
+            newAll.put(anyGetterProp.getName(), anyGetterProp);
+        }
+        return newAll;
+    }
```
Comment (JooHyukKim) [inline src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java]: This puts anyGetter prop in the end by default, before we go sorting downstream in `_sortProperties`

File: src/test/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollectorTest.java [hunk 2]
```diff
@@ -502,7 +502,7 @@ public void testDuplicateGetters() throws Exception
         assertTrue(prop.getGetter().hasAnnotation(B.class));
     }
 
-    @Test
+//    @Test
```
Comment (JooHyukKim) [inline src/test/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollectorTest.java]: Need to figure this out first.

File: src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java [hunk 3]
```diff
@@ -501,6 +501,29 @@ protected void collectAll()
...
+     * Put anyGetter in the end, before actual sorting further down {@link POJOPropertiesCollector#_sortProperties(Map)}
+     */
+    private Map<String, POJOPropertyBuilder> _putAnyGettersInTheEnd(Map<String, POJOPropertyBuilder> all, Map<String, POJOPropertyBuilder> props) {
+        for (POJOPropertyBuilder prop : props.values()) {
+            all.put(prop.getName(), prop);
+        }
+        Map<String, POJOPropertyBuilder> newAll = new LinkedHashMap<String,POJOPropertyBuilder>(props.size()+props.size());
+        POJOPropertyBuilder anyGetterProp = null;
+        for (POJOPropertyBuilder prop : all.values()) {
+            if (prop.getAccessor() != null && Boolean.TRUE.equals(this._config.getAnnotationIntrospector().hasAnyGetter(prop.getAccessor()))) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java]: No, we really should not do annotation introspector here, again...

**Comment by JooHyukKim** [comment]
Oh wow, thank you for the extra work @cowtowncoder 👍👍 almost seems like a brand new PR

**Comment by cowtowncoder** [comment]
> Oh wow, thank you for the extra work @cowtowncoder 👍👍 almost seems like a brand new PR

Np. I got bit carried away. But the logic remains the way it was so it's still your PR :)

Will now merge.

**Review by cowtowncoder — APPROVED** [review]
LGTM
