### PR TITLE
Change Records deserialization to use the same mechanism as POJO deserialization.

### LINKED ISSUE #2974: Null coercion with `@JsonSetter` does not work with `java.lang.Record`
Looks like use of `@JsonSetter(nulls=...)` does not work with Records in 2.12.0.

Note that earlier report (#2970) turned out to be valid, but since I closed it earlier decided to file a separate one.

### LINKED ISSUE #2992: Properties naming strategy do not work with Record
Hello,

When I try to use a `@JsonNaming`  annotation on a record, I cannot unmarshall json to an object because a mapping exception occurs. 

I use jackson 2.12.0 with JDK 15.

A Test example can be something like: 

```
    @Test
    void tryJsonNamingOnRecord() throws Exception{
        ObjectMapper mapper=new ObjectMapper();

        @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
                record Test(String myId, String myValue){}

        var src=new Test("id", "value");
        String json=mapper.writeValueAsString(src);
        assertThat(json).contains("\"my_id\":\"id\"", "\"my_value\":\"value\"");
        var after=mapper.readValue(json, Test.class);
        assertThat(after).isEqualTo(src);
    }
```

The json String is generated correctly, but when unmarshalling, I got an exception  

```
com.fasterxml.jackson.databind.JsonMappingException: Can not set final java.lang.String field test.Tests$1Test.myValue to java.lang.String
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:274)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:623)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:611)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:634)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:193)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValue$Regular.assign(PropertyValue.java:62)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1390)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4591)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3546)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
	at test.Tests.tryJsonNamingOnRecord(Tests.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
...
Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field test.Tests$1Test.myValue to java.lang.String
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
	at java.base/java.lang.reflect.Field.set(Field.java:793)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:190)
	... 76 more
```

### LINKED ISSUE #3102: @JsonNaming does not work with Java 16 record types
**Describe the bug**
JsonNaming does not seem to be applied to Java 16 record types for deserialization.

**Version information**
2.12.2

**To Reproduce**
Simple unit test:
```java
public class RecordTest
{
    @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
    public record TestRecord(int id, String toSnakeCase) {}

    @Test
    public void testSerializeJsonTestRecord()
            throws JsonProcessingException
    {
        JsonMapper jsonMapper = new JsonMapper();

        TestRecord expectedRecord = new TestRecord(123, "Bob");

        String actualJson = jsonMapper.writeValueAsString(expectedRecord);
        assertEquals("{\"id\":123,\"to_snake_case\":\"Bob\"}", actualJson);

        TestRecord actualValue = jsonMapper.readValue("{\"id\":123,\"to_snake_case\":\"Bob\"}", TestRecord.class);
        assertEquals(new TestRecord(123, "Bob"), actualValue);
    }
}
```

Failure stack:
```

com.fasterxml.jackson.databind.JsonMappingException: Can not set final java.lang.String field io.starburst.stargate.portal.security.client.RecordTest$TestRecord.toSnakeCase to java.lang.String

	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:274)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:623)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:611)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:634)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:193)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValue$Regular.assign(PropertyValue.java:62)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at io.starburst.stargate.portal.security.client.RecordTest.testSerializeJsonTestRecord(RecordTest.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field io.starburst.stargate.portal.security.client.RecordTest$TestRecord.toSnakeCase to java.lang.String
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
	at java.base/java.lang.reflect.Field.set(Field.java:793)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:190)
	... 74 more
```

### LINKED ISSUE #3180: Support `@JsonCreator` annotation on record classes
Using Jackson 2.12.

One common pattern in code on my teams is to use 'alias' types to decorate otherwise primitive value types in APIs and/or for dimensional units to gain compiler support for detecting otherwise subtle programming errors (such as using the wrong unit or passing parameters in the wrong order).

Today, to do this with Java records, we need to write classes like
```java
public record Watts(@JsonValue double value) {
    @JsonCreator
    public static Watts of(double value) {
        return new Watts(value);
    }
}
```
Without the `@JsonCreator` annotated static method (or similarly trivial but verbose constructor), Jackson produces the error
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `...Watts` 
  (although at least one Creator exists): no double/Double-argument constructor/factory method to 
  deserialize from Number value (<value>)
```

If we could place `@JsonCreator` on record classes and infer use of the single argument default constructor I think it'd cut the boilerplate even more. Alternatively, or in addition, it might be interesting to infer that a record class with a single labeled `@JsonValue` parameter should use the default constructor, allowing us to write either:
```java
@JsonCreator
public record Watts(@JsonValue int value) {}
```

or
```java
public record Watts(@JsonValue int value) {}
```

### LINKED ISSUE #3297: `@JsonDeserialize(converter = ...)` does not work with Records
**Describe the bug**
`@JsonDeserialize(converter = ...)` on Record's fields isn't picked up by Jackson during deserialization. I'm using this converter to parse time without zone information into `Instant` field.

**Version information**
Jackson: 2.13, 2.13.1-SNAPSHOT
JDK: 17

**To Reproduce**
```
public class JacksonTestCase {

    public static void main(String[] args) throws JsonProcessingException {
        var objectMapper = new ObjectMapper().registerModule(new JavaTimeModule());

        objectMapper.readValue("""
                               { "value": "test", "time": "2021-10-07T22:47:15" }
                                """, RecordEntity.class);
    }

    static record RecordEntity(
            String value,
            @JsonDeserialize(converter = InstantWithoutZoneConverter.class)
            Instant time
    ) {
    }

    static class InstantWithoutZoneConverter implements Converter<LocalDateTime, Instant> {
        @Override
        public Instant convert(LocalDateTime value) {
            return value.toInstant(ZoneOffset.UTC);
        }

        @Override
        public JavaType getInputType(TypeFactory typeFactory) {
            return typeFactory.constructType(LocalDateTime.class);
        }

        @Override
        public JavaType getOutputType(TypeFactory typeFactory) {
            return typeFactory.constructType(Instant.class);
        }
    }
}
```

**Additional context**
It looks similar to #2974 and workaround to add `@JsonProperty("time")` works here as well:
```
    static record RecordEntity(
            String value,
            @JsonProperty("time")
            @JsonDeserialize(converter = InstantWithoutZoneConverter.class)
            Instant time
    ) {
    }
```

### LINKED ISSUE #3342: JsonTypeInfo.As.EXTERNAL_PROPERTY does not work with record wrappers
**Describe the bug**
When I try to use  `JsonTypeInfo.As.EXTERNAL_PROPERTY` inside a record, I get 
```
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `my.company.fastcheck.analyzer.JacksonExternalTypeIdTest$Parent`, problem: Internal error: no creator index for property 'child' (of type com.fasterxml.jackson.databind.deser.impl.FieldProperty)
```

Note that it works with normal classes. Code examples below.

**Version information**
2.13.0

**To Reproduce**

Using a record as wrapping object: (**Fails**)
```java
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.DatabindContext;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonTypeIdResolver;
import com.fasterxml.jackson.databind.jsontype.impl.TypeIdResolverBase;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;

class JacksonExternalTypeIdTest {

	@Test
	void testExternalTypeIdPropertyInsideRecord() throws IOException {
		ObjectMapper objectMapper = new ObjectMapper();
		Parent parent = objectMapper.readValue("""
			{"type": "CHILLED", "child": {}}
		""", Parent.class);
		Assertions.assertTrue(parent.child instanceof ChilledChild);
	}

	public enum ParentType {
		CHILLED,
		AGGRESSIVE
	}

	public static record Parent(
			ParentType type,
			@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "type")
			@JsonTypeIdResolver(ChildBaseByParentTypeResolver.class)
			ChildBase child
	) {}

	public static interface ChildBase {
	}

	public static record AggressiveChild(String someString) implements ChildBase {
	}

	public static record ChilledChild(String someString) implements ChildBase {
	}

	public static class ChildBaseByParentTypeResolver extends TypeIdResolverBase {

		private JavaType superType;

		@Override
		public void init(JavaType baseType) {
			superType = baseType;
		}

		@Override
		public JsonTypeInfo.Id getMechanism() {
			return JsonTypeInfo.Id.NAME;
		}

		@Override
		public JavaType typeFromId(DatabindContext context, String id) {
			Class<?> subType = switch (id) {
				case "CHILLED" -> ChilledChild.class;
				case "AGGRESSIVE" -> AggressiveChild.class;
				default -> throw new IllegalArgumentException();
			};
			return context.constructSpecializedType(superType, subType);
		}

		@Override
		public String idFromValue(Object value) {
			throw new UnsupportedOperationException();
		}

		@Override
		public String idFromValueAndType(Object value, Class<?> suggestedType) {
			throw new UnsupportedOperationException();
		}
	}
}
```

Using a class as wrapping object: (**Passes**)
```java
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.DatabindContext;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonTypeIdResolver;
import com.fasterxml.jackson.databind.jsontype.impl.TypeIdResolverBase;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;

class JacksonExternalTypeIdTest {

	@Test
	void testExternalTypeIdPropertyInsideRecord() throws IOException {
		ObjectMapper objectMapper = new ObjectMapper();
		Parent parent = objectMapper.readValue("""
					{"type": "CHILLED", "child": {}}
				""", Parent.class);
		Assertions.assertTrue(parent.child instanceof ChilledChild);
	}

	public enum ParentType {
		CHILLED,
		AGGRESSIVE
	}

	public static final class Parent {
		private final ParentType type;

		@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "type")
		@JsonTypeIdResolver(ChildBaseByParentTypeResolver.class)
		private final ChildBase child;

		public Parent(
				@JsonProperty("type") ParentType type,
				@JsonProperty("child") ChildBase child
		) {
			this.type = type;
			this.child = child;
		}

		public ParentType type() {
			return type;
		}

		public ChildBase child() {
			return child;
		}

	}

	public static interface ChildBase {
	}

	public static record AggressiveChild(String someString) implements ChildBase {
	}

	public static record ChilledChild(String someString) implements ChildBase {
	}

	public static class ChildBaseByParentTypeResolver extends TypeIdResolverBase {

		private JavaType superType;

		@Override
		public void init(JavaType baseType) {
			superType = baseType;
		}

		@Override
		public JsonTypeInfo.Id getMechanism() {
			return JsonTypeInfo.Id.NAME;
		}

		@Override
		public JavaType typeFromId(DatabindContext context, String id) {
			Class<?> subType = switch (id) {
				case "CHILLED" -> ChilledChild.class;
				case "AGGRESSIVE" -> AggressiveChild.class;
				default -> throw new IllegalArgumentException();
			};
			return context.constructSpecializedType(superType, subType);
		}

		@Override
		public String idFromValue(Object value) {
			throw new UnsupportedOperationException();
		}

		@Override
		public String idFromValueAndType(Object value, Class<?> suggestedType) {
			throw new UnsupportedOperationException();
		}
	}
}
```

**Expected behavior**
Should work with records, too.
For now, using normal class as workaround.

**Additional context**
(none)

### PR DESCRIPTION
**Pull request by yihtserns**
### New
- Supports `@JsonCreator.mode=DISABLED` on canonical constructor.
- Supports deserialization using "implicit" (i.e. without `@JsonCreator` annotation) non-canonical constructor when 1/more of its parameter is/are annotated with `@JsonProperty`.
- Supports "implicit" (i.e. without `@JsonCreator` annotation) 1-arg delegating constructor.
- Supports "implicit" (i.e. without `@JsonCreator` annotation) 1-arg delegating factory method.
- Supports disabling "implicit" (i.e. without `@JsonCreator` annotation) constructor/factory method detection via `MapperFeature.AUTO_DETECT_CREATORS`.

This is a non-exhaustive list - I don't have full knowledge of existing JavaBeans deserialization capabilities.

### Fixes
- Fixes #2992
- Fixes #2974
- Fixes #3297
- Fixes #3342
- Resolves #3180 (via "implicit" 1-arg delegating factory method)

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java [hunk 1]
```diff
@@ -28,9 +27,8 @@ public static String[] getRecordFieldNames(Class<?> recordType) {
         return RecordAccessor.instance().getRecordFieldNames(recordType);
     }
 
-    public static AnnotatedConstructor findRecordConstructor(DeserializationContext ctxt,
-            BeanDescription beanDesc, List<String> names) {
-        return new CreatorLocator(ctxt, beanDesc)
+    public static AnnotatedConstructor findRecordConstructor(AnnotatedClass recordClass, AnnotationIntrospector intr, MapperConfig<?> config, List<String> names) {
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java:30]: API change? Possibly not a good thing - any chance that the old version can be kept and deprecated?

File: src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java [hunk 2]
```diff
@@ -632,12 +663,12 @@ protected void _addCreators(Map<String, POJOPropertyBuilder> props)
      * @since 2.4
      */
     protected void _addCreatorParam(Map<String, POJOPropertyBuilder> props,
-            AnnotatedParameter param)
+            AnnotatedParameter param, String defaultParameterName)
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java:666]: can you deprecate the original and add a new overloaded version?

File: src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java [hunk 3]
```diff
@@ -400,7 +390,9 @@ public ValueInstantiator _valueInstantiatorInstance(DeserializationConfig config
      * constructor is to be used: if so, we have implicit names to consider.
      *
      * @since 2.12
+     * @deprecated no longer used, but kept because this protected method might have been overridden(?)
      */
+    @Deprecated
```
[the remark this answers is not in the document]
Comment (yihtserns) [reply src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java:395]: Actually I'm not sure what to do with this method, since it's no longer used.  Yet I dare not remove since it is `protected`.

Is marking it as deprecated the way to go?

[the remark this answers is not in the document]
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java:395]: Yes, deprecation is the way to go, but as @pjfanning mentioned please always indicate version in which deprecation occurred.

File: src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java:30]: Yeah no, please leave the signature as it was: `DeserializationContext` and `BeanDescription` can be used to access `AnnotationIntrospector` and `MapperConfig`.

File: src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java [hunk 4]
```diff
@@ -150,25 +148,25 @@ public RawTypeName(Class<?> rt, String n) {
     }
 
     static class CreatorLocator {
-        protected final BeanDescription _beanDesc;
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java:153]: Same as above, please do not change these. Over time I have learned that information from more expressive types (BeanDescription is superset of AnnotatedClass, DeserializationContext similarly superset of MapperConfig) is safer to pass around -- I consistently needed to upgrade parameters.

**Comment by cowtowncoder** [comment]
First of all, thank you for contributing this @yihtserns ! It sounds like solid improvement, potentially.

I added some smaller notes on keeping existing API in some places, but there is one bigger request I have: this PR needs to be against `2.15` branch; I don't feel comfortable merging it in a patch to 2.14 -- patches are typically for smaller, less risky changes, and while I don't have specific issues here I feel there is potential for some breakage.

**Comment by yihtserns** [comment]
> ...this PR needs to be against `2.15` branch; I don't feel comfortable merging it in a patch to 2.14...

Do I put "since 2.15" in the deprecation notice?

And yeah I wasn't sure whether I should go with 2.14 or 2.15 since https://github.com/FasterXML/jackson/blob/master/CONTRIBUTING.md didn't mention the latter...  That doc needs to be updated?

File: src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java (hunk 1 above)
Comment (yihtserns) [reply src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java:30]: The problem is in the place I'm using it now (`POJOPropertiesCollector`), I don't have `DeserializationContext` nor `BeanDescription`...

Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java]: Hmmm, ok that makes sense. But that's bit of a problem. Let me think about it.

**Comment by cowtowncoder** [comment]
> > ...this PR needs to be against `2.15` branch; I don't feel comfortable merging it in a patch to 2.14...
> 
> Do I put "since 2.15" in the deprecation notice?
> 
> And yeah I wasn't sure whether I should go with 2.14 or 2.15 since https://github.com/FasterXML/jackson/blob/master/CONTRIBUTING.md didn't mention the latter... That doc needs to be updated?



> > ...this PR needs to be against `2.15` branch; I don't feel comfortable merging it in a patch to 2.14...
> 
> Do I put "since 2.15" in the deprecation notice?

Yes.
 
> And yeah I wasn't sure whether I should go with 2.14 or 2.15 since https://github.com/FasterXML/jackson/blob/master/CONTRIBUTING.md didn't mention the latter... That doc needs to be updated?

Thanks, I'll need to update that. There are some things that should go into earlier branches too -- generally earliest maintained, for safe enough fixes. So it is not easy to correctly guess what I think is the right branch :)
(which is also why I don't mind pointing out what I think should be used).

File: src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java [hunk 5]
```diff
@@ -467,6 +467,10 @@ protected Object _deserializeUsingPropertyBased(final JsonParser p, final Deseri
             // regular property? needs buffering
             SettableBeanProperty prop = _beanProperties.find(propName);
             if (prop != null) {
+                if (prop.isIgnorable() && _beanType.isRecordType()) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java:470]: Was there a problem here, to require additional processing? And/or would this work even for POJO types?

File: src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java [hunk 6]
```diff
@@ -653,7 +690,8 @@ protected void _addCreatorParam(Map<String, POJOPropertyBuilder> props,
             // Also: if this occurs, there MUST be explicit annotation on creator itself
             JsonCreator.Mode creatorMode = _annotationIntrospector.findCreatorAnnotation(_config,
                     param.getOwner());
-            if ((creatorMode == null) || (creatorMode == JsonCreator.Mode.DISABLED)) {
+            if ((creatorMode == null || creatorMode == JsonCreator.Mode.DISABLED)
+                    && defaultParameterName.isEmpty()) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java:694]: Should add a comment explaining logic for "defaultParameterName" somewhere (what/why?)

File: src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java [hunk 7]
```diff
@@ -902,6 +940,12 @@ protected void _removeUnwantedProperties(Map<String, POJOPropertyBuilder> props)
             }
             // Otherwise, check ignorals
             if (prop.anyIgnorals()) {
+                if (_classDef.getType().isRecordType()) {
+                    prop.removeIgnored();
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java:944]: Why do record types require different handling from POJOs here? (add a comment)

**Comment by cowtowncoder** [comment]
Ok, looks pretty good. I do need to go over it again with more thought, but I like how small changes are.

**Comment by cowtowncoder** [comment]
@yihtserns One more thing: I hope to be able to merge this soon. One last thing before that is that we need a Contributor License Agreement (CLA) before merging the first contribution. This only needs to be done once and then it is good for all future PRs for Jackson project.

Document is here:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the usual way is to print, fill & sign, scan/photo, email to `info` at fasterxml dot com.
Once I get the document I will be able to merge the PR (I will do one more code review but I assume we are very close).

Thank you again for providing this patch -- looking forward to merging it!

**Comment by yihtserns** [comment]
I'm currently re-reviewing if `@JsonIgnore` can be supported in a different way (else the explanation of the current approach will be a headache).

**Comment by yihtserns** [comment]
CLA sent.

**Comment by cowtowncoder** [comment]
@yihtserns One more thing: I hope to be able to merge this soon. One last thing before that is that we need a Contributor License Agreement (CLA) before merging the first contribution. This only needs to be done once and then it is good for all future PRs for Jackson project.

Document is here:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the usual way is to print, fill & sign, scan/photo, email to `info` at fasterxml dot com.
Once I get the document I will be able to merge the PR (I will do one more code review but I assume we are very close).

Thank you again for providing this patch -- looking forward to merging it!

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Ok looks good, will merge! Will see how much trouble merging into `master` (3.0) will be....

**Comment by cowtowncoder** [comment]
Ugh. Ok, so I was able to merge code. But now there are ~20 failures for Record-related tests in `master`.

Also: I think I may disagree with test

        public void testDeserializeMultipleConstructorsRecord_WithExplicitAndImplicitParameterNames() throws Exception

wherein it is claimed there are 2 usable Creators (canonical, one with `@JsonProperty` annotation).
It seems to me that while constructor has no `@JsonCreator`, existence of `@JsonProperty` would make that explicit constructor, over canonical constructor.

But be that as it may, I think I will need help with `master`, failing tests. I think some calls are now missing so that even simplest of `Record` tests in `RecordsBasicTest` fail.

File: src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java [hunk 8]
```diff
@@ -610,23 +611,53 @@ protected void _addFields(Map<String, POJOPropertyBuilder> props)
...
-                _creatorProperties = new LinkedList<POJOPropertyBuilder>();
-            }
-            for (int i = 0, len = factory.getParameterCount(); i < len; ++i) {
-                _addCreatorParam(props, factory.getParameter(i));
+        if (_classDef.getType().isRecordType()) {
+            List<String> recordComponentNames = new ArrayList<String>();
+            AnnotatedConstructor canonicalCtor = JDK14Util.findRecordConstructor(
+                    _classDef, _annotationIntrospector, _config, recordComponentNames);
+
+            if (canonicalCtor != null) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java:637]: Shouldn't `null` result be anomaly and result in exception? Or is the assumption that it's only returned if there are no explicitly annotated alternatives?

Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java:637]: Oh actually no; method does avoid returning anything if there is something that should override the canonical constructor. Naming is bit unfortunate.

**Comment by yihtserns** [comment]
> But be that as it may, I think I will need help with master, failing tests.

OK I'll look into them.

**Comment by cowtowncoder** [comment]
Thank you @yihtserns! I am zeroing in on one issue: VisibilityChecker for Constructors is somehow claiming default record constructors are not visible. I'll try to see what gives...

**Comment by cowtowncoder** [comment]
Ok, yes; there is something in minimum visibility needed; defaults are defined by `@JsonAutoDetect` annotation in `VisibilityChecker` and have changed to require `public` for 3.0.

But what seems odd to me is how canonical constructor is apparently not generated as `public` (looking at decompiled record classes) but as package default.
So I think one way to fix this would be to somehow use differently configured `VisibilityChecker` for records; similar to have "all public" variant is (by default) used for JDK types.
Looks like logic could be injected from `getDefaultVisibilityChecker()` of `MapperConfigBase`; possibly checking if type is a record type (before even checking for "is JDK class").

**Comment by yihtserns** [comment]
> But what seems odd to me is how canonical constructor is apparently not generated as public

They aren't public because the `record` declarations weren't public.  Changing `record XXX` to `public record XXX` reduced test failures from 21 to 3.

(For some of the records, although the declaration itself weren't `public`, their _declared_ constructors are `public` so they're not failing.)

**Comment by yihtserns** [comment]
I've created https://github.com/FasterXML/jackson-databind/pull/3733 (will remain in draft until all test failures are resolved) to deal with issues related to the 3.0 port - let's continue this conversation there.

**Comment by yihtserns** [comment]
@pjfanning @cowtowncoder thank you for taking the time to review this PR, I really appreciate it.

**Comment by cowtowncoder** [comment]
FWTW, I think this change may have also caused a regression of one Kotlin test:

https://github.com/FasterXML/jackson-module-kotlin/issues/396

**Comment by yihtserns** [comment]
> FWTW, I think this change may have also caused a regression of one Kotlin test: https://github.com/FasterXML/jackson-module-kotlin/issues/396

So [Github396.kt](https://github.com/FasterXML/jackson-module-kotlin/blob/2.15/src/test/kotlin/com/fasterxml/jackson/module/kotlin/test/github/failing/Github396.kt) is a negative test that expects deserialization to fail with `MismatchedInputException`, but it is now by managing to deserialize `<product><stuff></stuff></product>` into `Product(stuff=Stuff(str=null))`.

That seems to have been caused by #3676.  When I change `BeanDeserializerBase.getEmptyValue(...)` from `_valueInstantiator.createUsingDefaultOrWithoutArguments(...)` back to `_valueInstantiator.createUsingDefault(...)`, that negative test is passing again.

**Comment by cowtowncoder** [comment]
@yihtserns Ok. So not these changes but earlier one; and unnoticed since there's no cascading CI builds across projects (that is, without changes to Kotlin module, no CI triggered when databind has changed -- something that'd be really nice to somehow resolve).

But this sounds like it would be a good thing? I am not big fan of negative tests because of this, although the main alternative (having failing tests under `failing/`) has the problem of "hiding" fixes.

**Comment by cowtowncoder** [comment]
@yihtserns Ok yes, thank you for pointing out the "failing to fail" part. This is indeed something fixed in `jackson-dataformat-xml` so I just had to change test. Looking how things work it's actually not a bad idea to verify "is now fixed" part... need to keep that in mind wrt other modules :)

**Comment by yihtserns** [comment]
> Also: I think I may disagree with test `testDeserializeMultipleConstructorsRecord_WithExplicitAndImplicitParameterNames()` wherein it is claimed there are 2 usable Creators (canonical, one with @JsonProperty annotation).
It seems to me that while constructor has no @JsonCreator, existence of @JsonProperty would make that explicit constructor, over canonical constructor.

@cowtowncoder when I test the POJO equivalent:
```
public static class BeanWithJsonPropertyAndImplicitPropertyWithoutJsonCreator {

    // Private fields

    public BeanWithJsonPropertyAndImplicitPropertyWithoutJsonCreator(int id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    public BeanWithJsonPropertyAndImplicitPropertyWithoutJsonCreator(@JsonProperty("id_only") int id, String email) {
        this.id = id;
        this.email = email;
    }

    // Public getters
}
```

I get the same failure as Records':
> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.github.yihtserns.records.jackson.RecordCanonicalVsJsonPropertyTest$RecordWithJsonPropertyAndImplicitPropertyWithoutJsonCreator` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

Bug?

**Comment by cowtowncoder** [comment]
@yihtserns If there is no module for getting implicit constructor parameter names, I'd expect failure since partial use of `@JsonProperty` is not enough for detection. But if parameter name detection exists, I am not 100% sure if logic would only allow it if there are no competing constructors (ones with or without annotation).

The thing that further complications matters is that POJOs do not have canonical constructor to solve the case where nothing is annotated -- but there are always implicit names.

**Comment by leonardehrenfried** [comment]
Renovate [auto-updated our application](https://github.com/opentripplanner/OpenTripPlanner/pull/5065) to Jackson 2.15 tonight. Some tests which check that records can be serialized fail as records are always serialized to empty objects.

These are plain records with no annotations or methods. Should that just work or do I need to configure/annotation something? In Jackson 2.14 it just worked.

**Comment by yihtserns** [comment]
@leonardehrenfried that symptom sounds similar to the one describe in https://github.com/FasterXML/jackson-databind/issues/3628#issuecomment-1504892161 - let me test that.

**Comment by yihtserns** [comment]
@leonardehrenfried so I tested `OpenTripPlanner`:
1. Changed `jackson.version` in `pom.xml` to `2.15.0`.
2. Run `mvn test` to observe the test failures (there's 1 unrelated to Records, so I'm ignoring it).
3. Create a local fork of `jackson-databind:2.15.0`, reverting [0a4cfc4](https://github.com/FasterXML/jackson-databind/commit/0a4cfc46bc491aed9eab83e13dcd65d415b10c64#diff-8a89bf8f93c483493c778cda25b2e31e2e89bd4b0a8a131e71bfd2ed5a199fff).
4. Change `OpenTripPlanner/pom.xml`'s `jackson-databind` to refer to that local fork.
5. Run `mvn test` again - no more test failures related to Records.

I've confirmed that the issue you're facing is related to the broken workaround mentioned in #3628, unrelated to this change.

**Comment by leonardehrenfried** [comment]
I since checked and we seem to be using a custom object mapper in the test:

```
      objectMapper = new ObjectMapper();
      objectMapper.configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);
      objectMapper.enable(SerializationFeature.WRITE_DATES_WITH_ZONE_ID);
      objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
      objectMapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
      objectMapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
      objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
      objectMapper.registerModule(new JavaTimeModule());
      objectMapper.registerModule(new Jdk8Module());

      objectMapper.setVisibility(
        objectMapper
          .getSerializationConfig()
          .getDefaultVisibilityChecker()
          .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
          .withGetterVisibility(JsonAutoDetect.Visibility.NONE)
          .withSetterVisibility(JsonAutoDetect.Visibility.NONE)
          .withCreatorVisibility(JsonAutoDetect.Visibility.NONE)
      );
```

https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java#L366-L384

So it appears that your analysis is totally correct.

I'm still not clear if this is was an intentional change in Jackson or not - can you clarify this for me?

Asked the other way around: is the old behaviour going to be restored and I should just wait for a new release or do I need to change the config of my object mapper?

**Comment by yihtserns** [comment]
> ...do I need to change the config of my object mapper?

I think that config was used because you had the same problem as #3628, and I can't think of an alternative solution for that problem.

> ...is the old behaviour going to be restored and I should just wait for a new release...

I've helped create #3894 to support that type of config.

**Comment by leonardehrenfried** [comment]
I'm sorry and as an open source maintainer myself I feel you.

I'm the last guy showing up on an issue making demands.

I would love to help diagnose and test and don't expect you to make a potentially broken config work for my benefit.

**Comment by cowtowncoder** [comment]
@leonardehrenfried Oh and just to make sure: I did not mean to blame you or users at all. I appreciate your reaching out and reporting the issue. I think we can figure this out; PR submitted might be the way, although I have some reservations. But it's a tricky problem.

**Comment by yihtserns** [comment]
@leonardehrenfried I've spent a bit of time to study the codebase to understand why that config was used - seems like it was to prevent `ApiLeg.getDuration()` from being serialized.

I assume that is to make assertion easier, since that method returns non-constant number?

If that's the case, here's my suggestion (tested with `2.15.0`):
```java
public abstract class SnapshotTestBase {
    ...

    private static class SnapshotItinerarySerializer implements SnapshotSerializer {

        private SnapshotItinerarySerializer() {
            ...

            // Remove this config:
            //objectMapper.setVisibility(
            //    objectMapper
            //      .getSerializationConfig()
            //      .getDefaultVisibilityChecker()
            //      .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
            //      .withGetterVisibility(JsonAutoDetect.Visibility.NONE)
            //      .withSetterVisibility(JsonAutoDetect.Visibility.NONE)
            //      .withCreatorVisibility(JsonAutoDetect.Visibility.NONE)
            //);

            // Add this:
            objectMapper.addMixIn(ApiLeg.class, ApiLegMixin.class);
            ...
        }
    }

    
    /**
     * To exclude {@link ApiLeg#getDuration()} from being deserialized because the returned number
     * is non-constant making it impossible to assert.
     */
    private abstract static class ApiLegMixin {

      @JsonIgnore
      abstract double getDuration();
    }
}
```

**Comment by leonardehrenfried** [comment]
@yihtserns thanks so much for this. It absolutely fixes the problems we are having. Fantastic work!

**Comment by agavrilov76** [comment]
Related to https://github.com/FasterXML/jackson-databind/issues/3900

**Comment by cowtowncoder** [comment]
Another breakage: #3938.

**Comment by yihtserns** [comment]
I used to think "nobody would ever put a setter in a Record since nothing is mutable, right?"

Now I know how ignorant I was...

**Comment by cowtowncoder** [comment]
To be honest, that use case is a bit "Creative" and just used to prevent deserialization of something without full ignoral.
But it is something I'd have used with regular POJOs and works very well for what is needed.

If someone else has shown that use case to me, I might have argued against it tho, with Records. Given that they are immutable.

Anyway, was happy to figure out how to make it work again via fix for #3928.

**Comment by yihtserns** [comment]
Caused #3968.
