### PR TITLE
Fix #2602: Make sure ByteBufferSerializer takes position into account

### LINKED ISSUE #2602: ByteBufferSerializer produces unexpected results with a duplicated ByteBuffer and a position > 0
The below test shows an issue where a duplicated `ByteBuffer` with a `position > 0` is returning unexpected results:

```

public void testDuplicatedByteBufferWithCustomPosition() throws IOException
{
    final byte[] INPUT_BYTES = new byte[] { 1, 2, 3, 4, 5 };
    String exp = MAPPER.writeValueAsString(new byte[] { 3, 4, 5 });

    ByteBuffer bbuf = ByteBuffer.wrap(INPUT_BYTES);

    bbuf.position(2);
    ByteBuffer duplicated = bbuf.duplicate();

    assertEquals(exp, MAPPER.writeValueAsString(duplicated));
}
```

```
Expected :"AwQF"
Actual   :"AQIDBAU="
```

I tested this on commit 6e5e2b06e with the `2.10` branch.

### PR DESCRIPTION
**Pull request by nastra**

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/ser/std/ByteBufferSerializer.java [hunk 1]
```diff
@@ -19,8 +19,16 @@
     public void serialize(ByteBuffer bbuf, JsonGenerator gen, SerializerProvider provider) throws IOException
     {
         // first, simple case when wrapping an array...
-        if (bbuf.hasArray()) {
-            gen.writeBinary(bbuf.array(), bbuf.arrayOffset(), bbuf.limit());
+        if (bbuf.hasArray())
+        {
+            if (bbuf.position() > 0)
```
Comment (nastra) [inline src/main/java/com/fasterxml/jackson/databind/ser/std/ByteBufferSerializer.java]: alternative option would be:

```
if (bbuf.hasArray())
{
    if (bbuf.position() > 0)
    {
        bbuf = bbuf.slice();
    }
    gen.writeBinary(bbuf.array(), bbuf.arrayOffset(), bbuf.limit());
    return;
}
```

**Comment by nastra** [comment]
@cowtowncoder could you review please?
