### PR TITLE
#1983 Allow case insensitive properties and values

### LINKED ISSUE #1983: Polymorphic deserialization should handle case-insensitive Type Id property name if `MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES` is enabled
Consider this data class:

```
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "operation")
@JsonSubTypes({
        @JsonSubTypes.Type(value = Equal.class, name = "eq"),
        @JsonSubTypes.Type(value = NotEqual.class, name = "noteq"),
})
public abstract class Filter {
    public String operation;
}
```
`MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES` is enabled for `ObjectMapper`:
`objectMapper.enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES);`

Trying to deserialize json `{ "operation": "EQ"}` fails with:
`com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'eq' into a subtype of...`

but deserializing from `{ "operation": "eq" }` works as expected.

It would be great if `MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES` would also work for this use case.

Tested with Jackson 2.8.0.

### PR DESCRIPTION
**Pull request by alevskyi**
Fixes #1983.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
That was quick! Thank you; I hope to review this soon.

File: src/test/java/com/fasterxml/jackson/failing/JsonTypeInfoCaseInsensitive1983Test.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+    }
+
+    static class Equal extends Filter {
+    }
+
+    static class NotEqual extends Filter {
+    }
+
+    public void testReadMixedCaseSubclass() throws IOException {
+//        There is also "ACCEPT_CASE_INSENSITIVE_VALUES" feature. Is it more suitable here, or I should leave it as is?
```
Comment (cowtowncoder) [inline src/test/java/com/fasterxml/jackson/failing/JsonTypeInfoCaseInsensitive1983Test.java]: Hmmm. Good question. I will have to think about this -- VALUES seems slightly better. But I will need to think through consequences and see what existing documentation says.

**Comment by cowtowncoder** [comment]
Quick note: same as with `jackson-core` contribution, just need that one CLA (no separate ones needed, covers all Jackson projects, contributions) and can then merge this.

**Comment by cowtowncoder** [comment]
Also: I just realized that both features are relevant: one to ensure that virtual property name is compared in case-insensitive manner; and the other that value (type id) is -- so I think your suggestion is correct wrt which one to use and where.

**Comment by cowtowncoder** [comment]
@alevskyi Thank you again for the fix! I made some minor tweaks (to match in all cases, I hope), will be in 2.11.0.
