### PR TITLE
Fix #5238 `@JsonIdentityInfo` w/ Records

### LINKED ISSUE #5238: Immutable classes with `@JsonIdentityInfo` can be deserialized; records cannot
### Search before asking

- [ ] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

If `@JsonIdentityInfo` is used with records, an exception is thrown at deserialization.

### Version Information

2.19.2

### Reproduction

This works perfectly:

```java
import java.io.IOException;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.databind.ObjectMapper;

public class JacksonTester {
    public static void main(String args[]) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        Thing thing1 = new Thing(1, "name1");
        Thing thing3 = new Thing(3, "name3");
        Example example = new Example(List.of(thing1, thing3), thing3);

        String jsonString = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(example);
        System.out.println(jsonString);
        Example exampleD = mapper.readValue(jsonString, Example.class);
        System.out.println(exampleD);
    }
}

record Example(List<Thing> allThings, Thing selected) {}

@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
// record Thing(int id, String name) { }
class Thing {
    public final int id;
    public final String name;

    @JsonCreator
    Thing(@JsonProperty("id") int id, @JsonProperty("name") String name) {
        this.id = id;
        this.name = name;
    }

    @Override
    public String toString() {
        return "Thing [id=" + id + ", name=" + name + "]";
    }
}
```

If, however, I replace `class Thing {...}`  with `record Thing(int id, String name) { }`, an exception is thrown when the json is deserialized:

> Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No fallback setter/field defined for creator property 'id' (of `Thing`) (through reference chain: Example["allThings"]->java.util.ArrayList[0])

### Expected behavior

Either no exception when using records or a more informative error message if records cannot be supported for whatever reason.

### Additional context

See https://github.com/FasterXML/jackson-databind/issues/3307 - marked with try-with-later-jackson.

(I tried with the last available version.)

### PR DESCRIPTION
**Pull request by JooHyukKim**
Fixes #5238 (`@JsonIdentityInfo` w/ Records)

### CODE REVIEW

File: src/test-jdk17/java/com/fasterxml/jackson/databind/records/JsonIdentityOnRecord5328Test.java [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+    @Test
+    void testIdentityWithRecord() throws Exception {
+        ThingRecord t1 = new ThingRecord(1, "a");
+        ThingRecord t2 = new ThingRecord(2, "b");
+
+        ExampleRecord input = new ExampleRecord(List.of(t1, t2), t2);
+
+        String json = MAPPER.writeValueAsString(input);
+
+        Exception ex = assertThrows(Exception.class, () ->
```
Comment (cowtowncoder) [inline src/test-jdk17/java/com/fasterxml/jackson/databind/records/JsonIdentityOnRecord5328Test.java]: This and following lines should be removed, converted to that "expected failure" annotation.... ?
(assuming this is to be merged)

Comment (JooHyukKim) [reply src/test-jdk17/java/com/fasterxml/jackson/databind/records/JsonIdentityOnRecord5328Test.java]: Sorry, yes this indeed DRAFT only.
Will change PR to draft.

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/PropertyValueBuffer.java [hunk 2]
```diff
@@ -335,7 +335,12 @@ public Object handleIdValue(final DeserializationContext ctxt, Object bean) thro
                 // also: may need to set a property value as well
                 SettableBeanProperty idProp = _objectIdReader.idProperty;
                 if (idProp != null) {
-                    return idProp.setAndReturn(bean, _idValue);
+                    // [databind#5328] Records do not have setters, skip...to set id value
+                    if (bean.getClass().isRecord()) {
```
Comment (JooHyukKim) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/PropertyValueBuffer.java]: Very much open for suggestion, couldn't think of more static way to get this done (unless we add property in `SettableBeanProperty`?

File: src/test-jdk17/java/com/fasterxml/jackson/databind/records/JsonIdentityOnRecord5238Test.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+        }
+    }
+
+    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
+    static class ThingPojo {
+        public final int id;
+        public final String name;
+
+        @JsonCreator
+        public ThingPojo(@JsonProperty("id") int id, @JsonProperty("name") String name) {
```
Comment (cowtowncoder) [inline src/test-jdk17/java/com/fasterxml/jackson/databind/records/JsonIdentityOnRecord5238Test.java]: I think this test should make sure `id` is only set via Constructor and NOT direct set on Field.
(JVM does allow forced settting of `final` Fields).

One way would be to make constructor change "id" value by prefix or suffix.

I know the end result does not look different, but it would explain discrepancy.

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/PropertyValueBuffer.java [hunk 4]
```diff
@@ -335,7 +336,12 @@ public Object handleIdValue(final DeserializationContext ctxt, Object bean) thro
                 // also: may need to set a property value as well
                 SettableBeanProperty idProp = _objectIdReader.idProperty;
                 if (idProp != null) {
-                    return idProp.setAndReturn(bean, _idValue);
+                    // [databind#5328] Records do not have setters, skip...to set id value
+                    if (ClassUtil.isRecordType(bean.getClass())) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/PropertyValueBuffer.java]: I'll have to think about this: ideally, `setAndReturn()` would not be called because id was passed via Constructor and no check was needed here.

Or maybe check could be done that if `idProp` is a `CreatorProperty`, no call would be made?

This is related to ensuring that we also do not try forcibly setting `Field` in regular POJO case, if id was already passed via Creator (see my note on test class).

Comment (JooHyukKim) [reply src/main/java/com/fasterxml/jackson/databind/deser/impl/PropertyValueBuffer.java]: Yes, let's do that. Applied :)

**Comment by cowtowncoder** [comment]
Looks good, but I am slightly worried about regression. Could we re-create this against `2.x` @JooHyukKim ? 2.20.0 will be released quite soon, probably sooner than next 2.19.x patch.

**Comment by JooHyukKim** [comment]
Ah okay, no objection pushing for `2.x`

**Comment by cowtowncoder** [comment]
Thank you @JooHyukKim ! Hoping to merge today.

**Review by cowtowncoder — APPROVED** [review]

**Review by cowtowncoder — APPROVED** [review]
