### PR TITLE
Ignore ConstructorDetector.SingleArgConstructor.PROPERTIES preference for Records.

### LINKED ISSUE #3968: Records with additional constructors failed to deserialize
**Describe the bug**
Records are not deserialized as before due to error:

> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Conflicting property-based creators: already had implicitly discovered creator [constructor for `RecordsDeserializationTest$TestRecord` (1 arg), annotations: [null], encountered another: [constructor for `RecordsDeserializationTest$TestRecord` (2 args), annotations: [null]
>  at [Source: (String)"{"a":"a", "b":"b"}"; line: 1, column: 1]

See the test below for the exact setup.

**Version information**
Which Jackson version(s) was this for?
2.15.0

**To Reproduce**

```
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.cfg.ConstructorDetector;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class RecordsDeserializationTest {

    private final ObjectMapper objectMapper = JsonMapper.builder()
            // commenting only this fixes the problem
            .addModules(new ParameterNamesModule())
            // commenting only this fixes the problem
            .constructorDetector(ConstructorDetector.USE_PROPERTIES_BASED)
            .build();

    record TestRecord(String a, String b) {

        // uncommenting only this fixes the problem
        // @JsonIgnore
        TestRecord(String c) {
            this(c, c);
        }
    }

    @Test
    void testDeserialization() throws JsonProcessingException {
        assertEquals(
                new TestRecord("a", "b"),
                objectMapper.readValue("{\"a\":\"a\", \"b\":\"b\"}", TestRecord.class));
    }
}
```

**Expected behavior**
The exact combination of configuration is not working in version 2.15.0.
There are 4 ways to fix it:
- remove module `ParameterNamesModule`
- don't use `USE_PROPERTIES_BASED` constructor detection
- add `@JsonIgnore` annotation to the extra constructor
- use version 2.13.4 on which this works

**Additional context**
The caveat here is that I can't use explicit `@JsonCreator` annotation on the primary constructor on a `record` (or I have to implement it just to add the annotation). Ideally, you should restore the old behavior. The `@JsonIgnore` approach seems like a hack to me.

### PR DESCRIPTION
**Pull request by yihtserns**
To fix #3968.

**NOTE**: I also wanted to add test case to see what happens when the canonical constructor is `@JsonIgnore`-ed, but apparently that's (currently) not allowed because it will throw exception:
https://github.com/FasterXML/jackson-databind/blob/2cea7c9ce9cbdcb14e22838ea07937c376b7ab78/src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java#L206-L209

### CODE REVIEW

File: src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitSingleValueUsePropertiesBasedCreatorsTest.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+
+        assertEquals(new RecordWithSingleValueCanonAndMultiValueAltConstructor("Bob"), value);
+    }
+
+    public void testDeserializeMultipleConstructors_WillIgnoreMultiValueAltConstructor() throws Exception {
+        try {
+            MAPPER.readValue(a2q("{'name':'Bob','email':'bob@email.com'}"), RecordWithSingleValueCanonAndMultiValueAltConstructor.class);
+        } catch (UnrecognizedPropertyException e) {
+            verifyException(e, "Unrecognized");
+            verifyException(e, "\"email\"");
```
[the remark this answers is not in the document]
Comment (yihtserns) [reply src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitSingleValueUsePropertiesBasedCreatorsTest.java:71]: It's different because even this will match: `verifyException(e, "Unrecognized", "this text does not exist in the exception message");`.

`matches` should've been named `anyMatches` and documented with:
> will pass if ANY of the given text matches the exception matches, will fail if NONE of them matches"

File: src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitSingleValueUsePropertiesBasedCreatorsTest.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+import com.fasterxml.jackson.databind.cfg.ConstructorDetector;
+import com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException;
+
+public class RecordImplicitSingleValueUsePropertiesBasedCreatorsTest extends BaseMapTest
+{
+
+    private final ObjectMapper MAPPER = jsonMapperBuilder()
+            .annotationIntrospector(new Jdk8ConstructorParameterNameAnnotationIntrospector())
+            .constructorDetector(ConstructorDetector.USE_PROPERTIES_BASED)
+            .build();
```
[the remark this answers is not in the document]
Comment (yihtserns) [reply src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitSingleValueUsePropertiesBasedCreatorsTest.java:14]: Missed that convention.  :/

File: src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java [hunk 3]
```diff
@@ -482,7 +482,9 @@ protected void _addImplicitConstructorCreators(DeserializationContext ctxt,
         final AnnotationIntrospector intr = ccState.annotationIntrospector();
         final VisibilityChecker<?> vchecker = ccState.vchecker;
         List<AnnotatedWithParams> implicitCtors = null;
-        final boolean preferPropsBased = config.getConstructorDetector().singleArgCreatorDefaultsToProperties();
+        final boolean preferPropsBased = config.getConstructorDetector().singleArgCreatorDefaultsToProperties()
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java:485]: Is this based on semantics needing changing, or just that it happens to solve the failure case?
My understanding is that for Records, default of `Mode.PROPERTIES` is something we would want, not `Mode.DELEGATING`?

File: src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java [hunk 4]
```diff
@@ -482,7 +482,9 @@ protected void _addImplicitConstructorCreators(DeserializationContext ctxt,
...
+                // [databind#3968]: Only Record's canonical constructor is allowed to be considered for properties-based creator
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java:486]: You mean, implicitly? And this because by default, canonical constructor is already considered (usually) Properties-based?

**Comment by cowtowncoder** [comment]
Ok, added some questions -- I think I understand the challenge, just seems tricky to combine defaulting of creator Mode (where Records definitely should default to Properties). But I understand that the issue then is just the conflict between 2 alternative Creators of same type.

However... for non-annotated ("implicit") case the Canonical constructor should win, I think; and in case of annotated (explicit) that one.

So I just want to try to make sure logic does not get even more fragile with various extra checks.

I hope to review this within 24 hours or so, but wanted add a quick note first.

File: src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java (hunk 4 above)
Comment (yihtserns) [reply src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java:486]: Yes, canonical constructor will be recognised as properties-based creator by:
1. https://github.com/FasterXML/jackson-databind/blob/a1e6208fd8c6d1873ae41106eb58f8c3751a12f3/src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java#L1025-L1033
2. https://github.com/FasterXML/jackson-databind/blob/a1e6208fd8c6d1873ae41106eb58f8c3751a12f3/src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java#L542-L548

...because only a canonical constructor will have an implicit constructor + `propDef` with implicit name.

File: src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java (hunk 3 above)
Comment (yihtserns) [reply src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java:485]: >  My understanding is that for Records, default of Mode.PROPERTIES is something we would want, not Mode.DELEGATING?

For when the constructor has single-arg, canonical constructor will already be recognised as properties-based creator by:

https://github.com/FasterXML/jackson-databind/blob/a1e6208fd8c6d1873ae41106eb58f8c3751a12f3/src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java#L1025-L1033

...because only a canonical constructor will have an implicit constructor + `propDef` with implicit name.

This `ConstructorDetector` config would only affect non-canonical constructors (which currently are/should only be considered for delegating creators).

**Additional notes**: Currently the only way to "implicitly" make canonical constructor a delegating creator is via `@JsonValue`:
https://github.com/FasterXML/jackson-databind/blob/a1e6208fd8c6d1873ae41106eb58f8c3751a12f3/src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitCreatorsTest.java#L34-L44

**Comment by cowtowncoder** [comment]
@JooHyukKim Alas, when we have all existing issues, I am not sure how much users will benefit from more pro-active communication outside of issue updates (if I understood this correctly). It's very tricky situation of course, esp. with patch releases... we don't have mechanism for pre-releases (nor do users really use those even if we did). SNAPSHOT builds exist, but are rarely used too. Test coverage works for regressions but not use cases users have -- and users rarely contribute tests for theirs, not until they break :-( :-( :-(

**Comment by cowtowncoder** [comment]
For what it is worth I do plan on now finally tackling introspection rewrite for 2.16. It may be risky but at least we do have much improved test suite, as of 2.15.x. And -- I hope -- better understanding of challenges.

File: src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitSingleValueUsePropertiesBasedCreatorsTest.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (cowtowncoder) [reply src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitSingleValueUsePropertiesBasedCreatorsTest.java:71]: FWTW I changed the parameter name for 2.16. And yes, it probably makes sense to start using something like AssertJ with regexp matches or such.

File: src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java (hunk 4 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java:486]: Ok. I think I understand how this works around the issue, although it still seems like it shouldn't be needed (but is due to... combination of factors). But since it actually resolves an actual problem & does not break other tests, I think I should merge this. And revisit whole thing for 2.16; but not block 2.15.x.

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Thank you @yihtserns !
