### PR TITLE
JsonPOJOBuilder.empty() causes incorrect config resolution

### LINKED ISSUE #1557: jackson-databind 2.9.0-pr1 breaks builder deserialization
For a Builder like,
```java
@AutoValue
@JsonDeserialize(builder = AutoValue_Restaurant.Builder.class)
@JsonNaming(PropertyNamingStrategy.UpperCamelCaseStrategy.class)
public abstract class Restaurant {
    Restaurant() { }

    @JsonProperty("RID")
    public abstract long getRID();

    @AutoValue.Builder
    @JsonNaming(PropertyNamingStrategy.UpperCamelCaseStrategy.class)
    @JsonPOJOBuilder(withPrefix="set")
    public abstract static class Builder {
        @JsonProperty("RID")
        public abstract Builder setRID(long rid);
    }
}
```

This code worked with 2.8 branch, but updating the 2.9.0-pr1 (to test out https://github.com/FasterXML/jackson-databind/issues/1402) breaks it.  It seems that commit https://github.com/FasterXML/jackson-databind/commit/e45279370ee9d3977776159c6f23d67f05379613 changed the default behavior of `AnnotationInspector#findPOJOBuilderConfig()` to returning a default value rather than `null`.

We end up with a `ParameterNamesAnnotationIntrospector` stacked on top of a `JacksonAnnotationIntrospector`.  Previously, `AnnotationIntrospectorPair#findPOJOBuilderConfig` would try the former, get null, then fallback to the latter.  Now it gets a bogus empty configuration from the former and never gets the correct configuration from the latter.

### PR DESCRIPTION
**Pull request by stevenschlansker**
fixes #1557

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/annotation/JsonPOJOBuilder.java [hunk 1]
```diff
@@ -85,6 +85,6 @@ public Value(String buildMethodName, String withPrefix)
 	        this.withPrefix = withPrefix;
 	    }
 
-	    public static Value empty() { return EMPTY; }
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/annotation/JsonPOJOBuilder.java]: This is backwards incompatible change, unless change was done for 2.9? If so, shouldn't `empty` remain as deprecated and new one added. Also please add `@since 2.9` for new `defaults()` method

**Comment by cowtowncoder** [comment]
Thanks! Only one real question wrt backwards compatibility -- can't remember why change was even made.

File: src/main/java/com/fasterxml/jackson/databind/annotation/JsonPOJOBuilder.java (hunk 1 above)
Comment (stevenschlansker) [inline src/main/java/com/fasterxml/jackson/databind/annotation/JsonPOJOBuilder.java]: It looks like it was added in `2.9.0-pr1` so it is safe to change:
https://github.com/fasterxml/jackson-databind/commit/e45279370ee9d3977776159c6f23d67f05379613

**Comment by stevenschlansker** [comment]
Added `@since`

**Comment by cowtowncoder** [comment]
Ah ok. Yes, change for 2.9 was messed up, not taking into account difference between missing `Value` and missing values within... so yeah I'll merge proposed fix and see if I can untangle the mess any more.
With most other annotations there's mergeability, but in this case 2 values are sort of related.

**Comment by cowtowncoder** [comment]
Done, and just removed that default thing for now, replaced with simple constants. May redo in future if more properties are needed, or multi-level overrides or something. But not today.

**Comment by stevenschlansker** [comment]
@cowtowncoder when will `pr2` (or `2.9.0` final) be released?

**Comment by cowtowncoder** [comment]
@Stephan202 I will do pr2 as soon as possible, one more pr1 issue by spring boot to resolve. So hopefully within 1 week

**Comment by Stephan202** [comment]
Wrong Stephan ;)

**Comment by cowtowncoder** [comment]
@Stephan202 Heh sorry. Damn auto-completion.

@stevenschlansker As per above, having fixed the only (?) other blocking breakage hoping to release soon.
