### PR TITLE
Fix #5354: do not write cglibs Callback[] getCallbacks() (3.x)

### LINKED ISSUE #5354: jackson-databind 3.0.0 renders `callbacks` property from Spring CGLIB Proxy
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

jackson-databind 3.0.0 renders the `callbacks` property from Spring CGLIB Proxy which appears to be a regression of https://github.com/FasterXML/jackson-databind/issues/674 that occurred in https://github.com/FasterXML/jackson-databind/commit/be906756305ee727d6cb0a44376ca77b39e593fe

This change broke Spring Security's / Jackson tests that confirm that objects secured using Spring Security proxies do not render properties on the proxy itself. Details can be found at https://github.com/spring-projects/spring-security/issues/18077

Can the ignoring of CGLIB be restored? If not, what is the reason and what is the recommended way that users should restore this behavior in Jackson 3?

### Version Information

tools.jackson.core:jackson-databind-3.0.0

### Reproduction

A complete example of the `callbacks` property not being rendered [in Jackson 2](https://github.com/rwinch/spring-sample/blob/jackson-cglib-properties/src/jackson2/java/jackson2/CglibTest.java#L16) and [rendering callbacks property in Jackson 3](https://github.com/rwinch/spring-sample/blob/jackson-cglib-properties/src/jackson3/java/jackson3/CglibTest.java) can be found at https://github.com/rwinch/spring-sample/tree/jackson-cglib-properties You can run `./gradlew check` to perform checks for both Jackson 2 and Jackson 3 or `./gradlew jackson2` and `./gradlew jackson3` to run the tests separately.

```java
static class Person {
	private final String firstName;

	private final String lastName;

	public Person(String firstName, String lastName) {
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public String getFirstName() {
		return firstName;
	}

	public String getLastName() {
		return lastName;
	}
}

@Test
public void cglibPropertiesNotRendered() throws Exception {
	JsonMapper mapper = JsonMapper.builder().build();
	Person target = new Person("first", "last");
	ProxyFactory factory = new ProxyFactory(target); // ProxyFactory from org.springframework:spring-aop:7.0.0-RC1
	factory.setOpaque(true);

	Person proxied = (Person) factory.getProxy();
	String json = mapper.writeValueAsString(proxied);
	Map<String, Object> properties = mapper.readValue(json, new TypeReference<>() {
	});
	assertThat(properties).containsOnlyKeys("firstName", "lastName"); // fails because callbacks property is included
}
``` 

### Expected behavior

I'd expect that Jackson 3 does not render CGLIB proxy properties.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rwinch**
Fixes #5354

### CODE REVIEW

**Review by cowtowncoder — APPROVED** [review]
LGTM!

**Comment by cowtowncoder** [comment]
Looks good @rwinch ! Just one thing before I can merge (non-test-)code changes: unless we have gotten CLA for you (apologies if I missed it, tried to check), would need one now, from:

https://github.com/FasterXML/jackson/blob/main/contributor-agreement.pdf

It only needs to be sent once and covers all future contributions. The usual way is to print, fill & sign, scan/photo, email to `cla` at fasterxml dot com.
Once I got it I'll proceed with merge and the fix will make it in 3.0.1 that I hope to release this week!

Thank you again for both reporting the issue and providing the fix!

File: src/test/java/tools/jackson/databind/ext/cglib/CglibFiltering5354Test.java [hunk 1]
```diff
@@ -24,17 +24,14 @@ public class CglibFiltering5354Test
     @Test
     public void testWriteWithSpringCglibProxyDoesNotIncludeCallbacksProperty() throws Exception
     {
-        // 20-Oct-2025, tatu: Temporarily disable until #5357 merged
```
Comment (cowtowncoder) [inline src/test/java/tools/jackson/databind/ext/cglib/CglibFiltering5354Test.java:27]: Merged via 2.x (#5356), undoing temporary comment-out.

**Review by cowtowncoder — APPROVED** [review]
LGTM

**Comment by rwinch** [comment]
@cowtowncoder Thanks for the reply. I'm working on sorting out the CLA with my employer and will get back to you as soon as I can.

**Comment by rwinch** [comment]
@cowtowncoder Thank you for your patience. I've submitted the CLA

**Review by cowtowncoder — APPROVED** [review]
LGTM
