### PR TITLE
Fix #4788 : `WRITE_ENUMS_TO_LOWERCASE` overrides `@JsonProperty`

### LINKED ISSUE #4788: `EnumFeature.WRITE_ENUMS_TO_LOWERCASE` overrides `@JsonProperty` values
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When using `EnumFeature.WRITE_ENUMS_TO_LOWERCASE`, the `@JsonProperty` values of enum fields are ignored.

### Version Information

2.18.1

### Reproduction

```java
class ObjectMapperTest {

  public enum Sauce {
    @JsonProperty("Ketchup")
    KETCHUP,
  }

  ObjectMapper objectMapper = new ObjectMapper()
      .configure(EnumFeature.WRITE_ENUMS_TO_LOWERCASE, true);

  @Test
  void shouldUseJsonProperty() throws JsonProcessingException {
    assertEquals("\"Ketchup\"", objectMapper.writeValueAsString(Sauce.KETCHUP));
  }
}
```

Results in:

```
org.opentest4j.AssertionFailedError: 
Expected :"Ketchup"
Actual   :"ketchup"
```

### Expected behavior

Should return `@JsonProperty` defined value. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JooHyukKim**
resolves 4788

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/util/EnumValues.java [hunk 1]
```diff
@@ -267,6 +241,22 @@ protected static Enum<?>[] _enumConstants(Class<?> enumCls) {
         }
         return enumValues;
     }
+
+    protected static String _findNameToUse(String explicitName, String otherName, boolean toLowerCase) {
```
Comment (JooHyukKim) [inline src/main/java/com/fasterxml/jackson/databind/util/EnumValues.java:245]: I questioned for a second whether to lazy-initialize `otherName` param by passing a functional interface or something, but thought it would be overkill to start with.

File: src/main/java/com/fasterxml/jackson/databind/util/EnumValues.java [hunk 2]
```diff
@@ -125,19 +115,9 @@ public static EnumValues constructFromToString(MapperConfig<?> config, Annotated
...
-                //   coerce into "" for backwards compatibility
-                if (name == null) {
-                    name = "";
-                }
-            }
-            if (useLowerCase) {
-                name = name.toLowerCase();
-            }
+            String enumToString = enumConstants[i].toString();
+            enumToString = (enumToString == null) ? "" : enumToString;
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/util/EnumValues.java:119]: Let's retain comment from above wrt [databind#4355], otherwise unclear how/why should we ever get `null` in here.

Comment (JooHyukKim) [reply src/main/java/com/fasterxml/jackson/databind/util/EnumValues.java:119]: Ah my bad. will do

File: src/main/java/com/fasterxml/jackson/databind/util/EnumValues.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/util/EnumValues.java:247]: Agreed, I think it's ok to eagerly process things in this case. Should not be on critical path.

File: src/main/java/com/fasterxml/jackson/databind/util/EnumValues.java [hunk 3]
```diff
@@ -92,13 +87,8 @@ public static EnumValues constructFromName(MapperConfig<?> config, AnnotatedClas
...
             Enum<?> enumValue = enumConstants[i];
-            String name = names[i];
-            if (name == null) {
-                name = enumValue.name();
-            }
-            if (useLowerCase) {
-                name = name.toLowerCase();
-            }
+            String name = _findNameToUse(names[i], enumValue.name(), useLowerCase);
+            // if it should lower case? then lower it, but if there is Json Property, use JsonProperty name first, and not lower
```
Comment (JooHyukKim) [inline src/main/java/com/fasterxml/jackson/databind/util/EnumValues.java:91]: Idk how this got here, removing

**Review by cowtowncoder — APPROVED** [review]
LGTM! Will merge, add release notes.

**Comment by JooHyukKim** [comment]
Thanks! May I ask you to remove [this comment](https://github.com/FasterXML/jackson-databind/pull/4789#discussion_r1833567137) also along the way @cowtowncoder ? I was a few seconds late 😂
