### PR TITLE
Exclude JDK proxies from ClassUtil.isJDKClass

### LINKED ISSUE #5416: Annotations on an interface that's part of a JDK proxy are not honored with Jackson 3
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Annotations such as `@JsonIgnore` are not honoured in Jackson 3 when the type being serialised is a JDK proxy whose class name starts with `jdk.`. I believe this will be the case when all of the proxy's interfaces are public.

### Version Information

3.0.2

### Reproduction

Run the following with Jackson Databind 2.20.1 and 3.0.2 on the classpath:

```java
package com.example;

import java.lang.reflect.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.JsonProcessingException;

public class JacksonJdkProxyProblem {
	
	public static void main(String[] args) throws JsonProcessingException {
		Object proxied = Proxy.newProxyInstance(JacksonJdkProxyProblem.class.getClassLoader(), new Class[] {Example.class}, (proxy, method, methodArgs) -> {
			return method.getName();
		});
		System.out.println(tools.jackson.databind.json.JsonMapper.builder().build().writeValueAsString(proxied));
		System.out.println(new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(proxied));
	}
	
	public static interface Example {
		
		String getValue();
		
		@JsonIgnore(true)
		String getIgnoredValue();
		
	}
	
}
```

It will produce the following output:

```
{"ignoredValue":"getIgnoredValue","value":"getValue"}
{"value":"getValue"}
```

### Expected behavior

I expected the following output:

```
{"value":"getValue"}
{"value":"getValue"}
```

### Additional context

I think https://github.com/FasterXML/jackson-databind/commit/dc10783ee70df95e774d1f8a8a84cc9fa2522ed6 is the cause. It has added `jdk.` to the prefixes that are used to identify JDK classes.

Perhaps classes whose name starts with `jdk.proxy` could be special-cased?

### PR DESCRIPTION
**Pull request by Eng-Fouad**
- Fixes #5416

### CODE REVIEW

File: src/main/java/tools/jackson/databind/util/ClassUtil.java [hunk 1]
```diff
@@ -978,7 +978,9 @@ public static boolean isJacksonStdImpl(Class<?> implClass) {
     public static boolean isJDKClass(Class<?> rawType) {
         final String clsName = rawType.getName();
         for (String prefix : JDK_PREFIXES) {
-            if (clsName.startsWith(prefix)) {
+            if (clsName.startsWith(prefix) &&
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/util/ClassUtil.java:982]: Looks good -- could you also mention this in Javadoc above?

**Comment by cowtowncoder** [comment]
@Eng-Fouad Looks good, thank you!

Just one more thing before I can merge this PR: we need CLA from https://github.com/FasterXML/jackson/blob/main/contributor-agreement.pdf (unless you have sent one before, LMK if so).
It needs to be sent once, before first contribution, and is good for all contributions from then on.
Usual way is to print, fill & sign, scan/photo, email to "cla" at fasterxml dot com.

Once I get it I can proceed.

Thank you again for super fast patch -- looking forward to merging!

File: src/main/java/tools/jackson/databind/util/ClassUtil.java (hunk 1 above)
Comment (Eng-Fouad) [reply src/main/java/tools/jackson/databind/util/ClassUtil.java:982]: Updated.

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad Looks good, thank you!
> 
> Just one more thing before I can merge this PR: we need CLA from https://github.com/FasterXML/jackson/blob/main/contributor-agreement.pdf (unless you have sent one before, LMK if so). It needs to be sent once, before first contribution, and is good for all contributions from then on. Usual way is to print, fill & sign, scan/photo, email to "cla" at fasterxml dot com.
> 
> Once I get it I can proceed.
> 
> Thank you again for super fast patch -- looking forward to merging!

Already sent it like 15 mins ago :)

**Review by cowtowncoder — APPROVED** [review]
LGTM
