### PR TITLE
Fix #2686: @JsonBackReference not working with Builder

### LINKED ISSUE #2686: `@JsonBackReference` does not work with a builder
When deserializing using a builder, `@JsonBackReference` does not work. It works when using an all-args constructor; that means that the "containing" instance (which contains the `@JsonManagedReference` forward link) already exists when Jackson starts populating the contained instance, so it should be possible to set this via builder.

Even though the annotation is on every possible place I could think of (field, getter, the builder's field, and of course the builder's setter method), the deserialization fails with this exception:
`Problem deserializing property 'back' (expected type: [simple type, class Container]; actual type: 'Container'), problem: object is not an instance of declaring class (through reference chain: Container["forward"])`

Jackson version 2.10.3

I found this problem when investigating which Jackson annotation have to be copied to the builder's setter methods in rzwitserloot/lombok#2419. However, this problem is not limited to lombok; see source below for a non-lombok example.

**Source to reproduce**

	public static class Container {
		@JsonManagedReference
		private Content forward;

		private String containerValue;

		@JsonManagedReference
		public Content getForward() {
			return forward;
		}

		@JsonManagedReference
		public void setForward(Content forward) {
			this.forward = forward;
		}

		public String getContainerValue() {
			return containerValue;
		}

		public void setContainerValue(String containerValue) {
			this.containerValue = containerValue;
		}
	}

	@JsonDeserialize(builder = Content.Builder.class) // Works when removing this, i.e. using the constructor
	public static class Content {
		@JsonBackReference
		private Container back;

		private String contentValue;
		
		@ConstructorProperties({ "back", "contentValue" })
		public Content(Container back, String contentValue) {
			this.back = back;
			this.contentValue = contentValue;
		}

		public String getContentValue() {
			return contentValue;
		}

		@JsonBackReference
		public Container getBack() {
			return back;
		}

		@JsonPOJOBuilder(withPrefix = "")
		public static class Builder {
			@JsonBackReference
			Container back;
			private String contentValue;
			
			@JsonBackReference
			Builder back(Container back) {
				this.back = back;
				return this;
			}

			Builder contentValue(String contentValue) {
				this.contentValue = contentValue;
				return this;
			}
			
			Content build() {
				return new Content(back, contentValue);
			}
		}
	}

	public static void main(String[] args) throws JsonMappingException, JsonProcessingException {
		ObjectMapper mapper = new ObjectMapper();

		Container container = new Container();
		container.containerValue = "containerValue";
		Content content = new Content(container, "contentValue");
		container.forward = content;
		
		String json = mapper.writeValueAsString(container);

		Container readValue = mapper.readValue(json, Container.class); // Exception here
	}

### PR DESCRIPTION
**Pull request by JacksonJang**
Issue: #2686

I initially considered handling this problem in `ManagedReferenceProperty`,
but resolving it in `BeanDeserializerFactory` during construction seemed 
more appropriate as it addresses the root cause directly.

### CODE REVIEW

File: src/test/java/tools/jackson/databind/struct/BuilderWithBackRef2686Test.java [hunk 1]
```diff
@@ -52,7 +48,6 @@ public static class Content {
 
         private String contentValue;
 
-        @ConstructorProperties({"back", "contentValue"})
```
Comment (cowtowncoder) [inline src/test/java/tools/jackson/databind/struct/BuilderWithBackRef2686Test.java:55]: No longer needed in 3.x for this use (Constructor parameter names).

**Review by cowtowncoder — APPROVED** [review]
LGTM!
