### PR TITLE
Fix #5405: @JsonFormat(shape = Shape.POJO) does not work for java.util.Map serialization via property annotation

### LINKED ISSUE #5405: `@JsonFormat(shape = Shape.POJO)` does not work for `java.util.Map` serialization via property annotation
(note: split off from #1419 )

So, although Class/default-config to serialize `Map`s works, doing the same via property annotation doesn't.
Following:

```
    static class Bean476Container
    {
        @JsonFormat(shape=JsonFormat.Shape.POJO)
        public Map<String, Object> stuff;
    }
```

will not use "POJO" style serialization.

### PR DESCRIPTION
**Pull request by JacksonJang**
Issue: #5405 
I've fixed the issue.

Additionally, since the test without b had been removed, I added that test case back as well.

### CODE REVIEW

**Comment by JacksonJang** [comment]
I updated the patch so that the property path simply calls `_checkShapeShifting(...)` directly.

**Comment by JacksonJang** [comment]
@cowtowncoder 
Would it be possible to consider merging this issue as well?

**Comment by cowtowncoder** [comment]
@JacksonJang I'll try to review this soon. Thank you!

**Comment by cowtowncoder** [comment]
Note: Trying to get CI code coverage working for external contributors.

File: src/main/java/tools/jackson/databind/SerializationContext.java [hunk 1]
```diff
@@ -1041,7 +1057,7 @@ private ValueSerializer<Object> _checkShapeShifting(JavaType type,
             BeanDescription.Supplier beanDescRef, BeanProperty prop, ValueSerializer<?> ser)
     {
         JsonFormat.Value overrides = prop.findFormatOverrides(_config);
-        if (overrides != null) {
+        if (overrides != null && overrides != JsonFormat.Value.empty()) {
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/SerializationContext.java:1060]: Just a slight optimization to avoid call when there are no overrides.

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Ok, I think this is the way; added handling to another code path, will merge.
