### PR TITLE
Fix #650: @JsonUnwrapped prevents checks for DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES

### LINKED ISSUE #650: `@JsonUnwrapped` prevents checks for `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES`
Deserializer didn't handle unknown properties if they was not mapped to Unwrapped object fields.
Here is unit test:

``` java
    private static class A {
        @JsonUnwrapped
        public B b;
    }

    private static class B {
        public String field;
    }

    private final ObjectMapper MAPPER = new ObjectMapper();

    public void testFailOnUnknownPropertyUnwrapped() throws IOException {
        assertTrue(MAPPER.isEnabled(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES));

        final String JSON = "{'field': 'value', 'bad':'bad value'}";
        try {
            MAPPER.readValue(aposToQuotes(JSON), A.class);
        } catch (JsonMappingException e) {
            // it's ok
            return;
        }
        fail("Exception was not thrown on unkown property");
    }
```

### PR DESCRIPTION
**Pull request by JacksonJang**
Issue: #650

@cowtowncoder @JooHyukKim 

Previously, when `_ignoreAllUnknown` was true, unknown properties were silently skipped.
Now, the condition also checks `FAIL_ON_UNKNOWN_PROPERTIES` .
if enabled, unknown properties will throw an error as expected.

I'm not sure if this is the right approach,
but it works and `jackson-module-kotlin` tests pass as well.
Please let me know if there's a better way to handle this.

### CODE REVIEW

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java [hunk 1]
```diff
@@ -1711,7 +1711,9 @@ protected void handleUnknownProperty(JsonParser p, DeserializationContext ctxt,
             Object beanOrClass, String propName)
         throws JacksonException
     {
-        if (_ignoreAllUnknown) {
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java:1714]: Make sure you know how and why `_ignoreAllUnknown` is set to `true`.

For example, `@JsonIgnoreProperties(ignoreUnknown = true)` on Class must have precedence over global `FAIL_ON_UNKNOWN_PROPERTIES`.

And I think this change breaks that: `BeanDeserializerFactory` line 525 is where this setting is passed.

File: src/test/java/tools/jackson/databind/deser/UnwrappedWithUnknown650Test.java [hunk 2]
```diff
@@ -23,7 +22,6 @@ static class B {
     }
 
 
-    @JacksonTestFailureExpected
     @Test
     void failOnUnknownPropertyUnwrapped() throws Exception {
```
Comment (cowtowncoder) [inline src/test/java/tools/jackson/databind/deser/UnwrappedWithUnknown650Test.java:104]: Also need a test method testing that regular working case still works, so no exception accidentally thrown for unwrapped property case.

Comment (cowtowncoder) [reply src/test/java/tools/jackson/databind/deser/UnwrappedWithUnknown650Test.java:104]: I'll add that.

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java:1714]: I went ahead and added override case to show the issue.

File: src/test/java/tools/jackson/databind/deser/UnwrappedWithUnknown650Test.java [hunk 3]
```diff
@@ -1,45 +1,57 @@
...
-            MAPPER.readValue(a2q(JSON), A.class);
+            A a = MAPPER.readValue(json, A.class);
             fail("Exception was not thrown on unknown property");
         } catch (UnrecognizedPropertyException e) {
             verifyException(e, "Unrecognized property");
         }
     }
 
+    @Test
+    void workOnUnknownWithAnnotation() throws Exception {
```
Comment (cowtowncoder) [inline src/test/java/tools/jackson/databind/deser/UnwrappedWithUnknown650Test.java:115]: @JacksonJang This now fails with the change.

Comment (JacksonJang) [reply src/test/java/tools/jackson/databind/deser/UnwrappedWithUnknown650Test.java:115]: @cowtowncoder 
Thank you for the additional explanation about `_ignoreAllUnknown` and for adding the test case.
I'll proceed with this approach and update the PR.

**Comment by JacksonJang** [comment]
@cowtowncoder 
What do you think of this approach?
I added `hasUnwrappedProperty` to check whether a property exists.
With this change, when `FAIL_ON_UNKNOWN_PROPERTIES` is enabled, 
an error is happened for properties that are unknown.

**Comment by cowtowncoder** [comment]
@JacksonJang This looks promising -- I will dig bit deeper later on but I think this might work!

**Comment by JacksonJang** [comment]
Thanks! -- Looking forward to your feedback 😄

File: src/main/java/tools/jackson/databind/deser/impl/UnwrappedPropertyHandler.java [hunk 4]
```diff
@@ -109,4 +111,39 @@ public Object processUnwrapped(JsonParser originalParser, DeserializationContext
...
         return new PropertyName(JSON_UNWRAPPED_NAME_PREFIX + index);
     }
+
+    /**
+     * Method that checks if properties have the property name.
+     *
+     * @since 3.1
+     */
+    public boolean hasUnwrappedProperty(String propName) {
+        for (SettableBeanProperty prop : _properties) {
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/impl/UnwrappedPropertyHandler.java]: Ok. This is pretty expensive performance-wise (these loops done potentially for every property of containing POJO, so I think it'd make sense to create a `HashSet<String>` to make lookup constant time instead.

Construction of that `HashSet` could be done in a new initialization method, called at the end of `BeanDeserializerBase.resolve()` after other resolution is complete.
If that doesn't work (too early, not all deserializers resolved), may instead need to construct dynamically from this method (with `volatile` reference, or `AtomicReference`).

**Comment by cowtowncoder** [comment]
Ok looks good, conceptually. I think performance of the lookup needs to be addressed by constructing a lookup data struct (simple `Set<String>` should suffice).

One other thing wrt naming: I wonder if this would work with `@JsonUnwrapped(prefix = "nested.")` (and similarly `suffix`) -- see `TestUnwrappedWithPrefix.java` for examples.
I think it'd be good to add a simple test to ensure.

Also: handling needs to be also added in 2 other methods, aside from `deserializeWithUnwrapped(JsonParser p, DeserializationContext ctxt):

*  `deserializeUsingPropertyBasedWithUnwrapped()` method (line 1021) -- called when POJO with `@JsonUnwrapped` has `@JsonCreator`
*  `deserializeWithUnwrapped()` overload (line 957)

**Comment by JacksonJang** [comment]
Thank you for the quick feedback!

I'll improve the lookup performance by using `HashSet`, and I’ll also add the test for the `TestUnwrappedWithPrefix` case as you suggested.

Thanks as well for pointing out the two additional methods -- I'll make sure to apply the same handling there too.

File: src/main/java/tools/jackson/databind/deser/impl/UnwrappedPropertyHandler.java (hunk 4 above)
Comment (JacksonJang) [reply src/main/java/tools/jackson/databind/deser/impl/UnwrappedPropertyHandler.java]: I just submitted https://github.com/FasterXML/jackson-databind/pull/5504/commits/8c987fbb6e7e48d3a574f22fb808a57790d3b9e3

Please take your time to review it.

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java [hunk 5]
```diff
@@ -1133,13 +1136,31 @@ public ObjectIdReader getObjectIdReader(DeserializationContext ctxt) {
     }
 
     public boolean hasProperty(String propertyName) {
-        return _beanProperties.findDefinition(propertyName) != null;
+        // noraml
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java]: Probably should be `// normal`?

Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java]: fixed.

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java [hunk 6]
```diff
@@ -1133,13 +1136,31 @@ public ObjectIdReader getObjectIdReader(DeserializationContext ctxt) {
...
+        if (_beanProperties.findDefinition(propertyName) != null) {
+            return true;
+        }
+        // [databind#3277]: Check unwrapped properties for nested unwrapping using a prefix.
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java]: How is this related to #3277?

**EDIT**: I'll change comment

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java [hunk 7]
```diff
@@ -1133,13 +1136,31 @@ public ObjectIdReader getObjectIdReader(DeserializationContext ctxt) {
...
+        if (_unwrappedPropertyHandler != null) {
+            if (_unwrappedPropertyHandler.hasUnwrappedProperty(propertyName)) {
+                return true;
+            }
+        }
+        // [databind#3277]: AnySetter can handle any property
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java]: I am not sure about this one: I guess it really depends on intended logic of this method -- whether it should indicate that we know there is a property (if so, any-setter should sort of not count) or whether it's just ok to try to set given property.

But since method does not:

1. have javadoc detailing semantics
2. seem to be used by any code (at least within databind package)
3. or be tested by any unit tests

I guess it's hard to know. But I think we should not consider any-setter for now.
I'll change this and add Javadoc.

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java [hunk 8]
```diff
@@ -1164,6 +1185,18 @@ public Collection<Object> getKnownPropertyNames() {
         return names;
     }
 
+    /**
+     * Method to collect all property names including nested unwrapped properties
+     */
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java:1209]: Needs `@since 3.1` -- I'll add

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializer.java [hunk 9]
```diff
@@ -995,8 +1000,11 @@ protected Object deserializeWithUnwrapped(JsonParser p, DeserializationContext c
             // how about any setter? We'll get copies but...
             if (_anySetter == null) {
                 // but... others should be passed to unwrapped property deserializers
-                tokens.writeName(propName);
-                tokens.copyCurrentStructure(p);
+                if (_unwrappedPropertyHandler.hasUnwrappedProperty(propName)) {
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializer.java]: I think this should be done regardless of whether there is `_anySetter` or not -- so not sending copies to both unwrapped and any-setter, just one. Will change.

**Review by cowtowncoder — APPROVED** [review]
LGTM!

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializer.java (hunk 9 above)
Comment (JacksonJang) [reply src/main/java/tools/jackson/databind/deser/bean/BeanDeserializer.java]: Thank you for your fixing 😀

**Comment by JacksonJang** [comment]
Thank you for taking a look.

I really appreciate that you always review my code and suggest revisions!

**Comment by cowtowncoder** [comment]
Thank you once again for doing all the work to fix the issue!
