### PR TITLE
Fix #4983:`@JsonTypeInfo` location actual baseType via hierarchy

### LINKED ISSUE #4983: `JsonTypeInfo.Id.MINIMAL_CLASS` generates invalid type on sub-package
Jackson: 2.18.2

I consider an interface with `@JsonTypeInfo(use = JsonTypeInfo.Id.MINIMAL_CLASS, property = "type")`.

It works correctly with implementations in thr same package, but it fails with implementations in a child package.

Can be reproduced with:

```
package eu.solven.adhoc.jackson;

import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.MINIMAL_CLASS, property = "type")
public interface IParent {

}
```

---

OK:
```
package eu.solven.adhoc.jackson;

import java.util.Map;

import com.fasterxml.jackson.databind.ObjectMapper;

public class Children implements IParent {
	String someField;

	public String getSomeField() {
		return someField;
	}

	public void setSomeField(String someField) {
		this.someField = someField;
	}

	public static void main(String[] args) {
		ObjectMapper om = new ObjectMapper();

		Map<?, ?> asMap = om.convertValue(new Children(), Map.class);
		System.out.println(asMap);

		IParent asParent = om.convertValue(asMap, IParent.class);

	}
}
```

---

KO:
```
package eu.solven.adhoc.jackson.sub;

import java.util.Map;

import com.fasterxml.jackson.databind.ObjectMapper;

import eu.solven.adhoc.jackson.IParent;

public class ChildrenSubPackage implements IParent {
	String someField;

	public String getSomeField() {
		return someField;
	}

	public void setSomeField(String someField) {
		this.someField = someField;
	}

	public static void main(String[] args) {
		ObjectMapper om = new ObjectMapper();

		Map<?, ?> asMap = om.convertValue(new ChildrenSubPackage(), Map.class);
		System.out.println(asMap);

		IParent asParent = om.convertValue(asMap, IParent.class);

	}
}
```

> Could not resolve type id 'eu.solven.adhoc.jackson.ChildrenSubPackage' as a subtype of `eu.solven.adhoc.jackson.IParent`: no such class found at [Source: UNKNOWN; byte offset: #UNKNOWN]

Indeed, the type is invalid in `{type=.ChildrenSubPackage, someField=null}` as it should be `.sub.ChildrenSubPackage`.

---

Also, the javadoc seems invalid:

> For example, for supertype "com.foobar.Base", and concrete type "com.foo.Impl", only ".Impl" would be included; and for "com.foo.impl.Impl2" only ".impl.Impl2" would be included.

I suppose we want to read:

> For example, for supertype "com.foo.Base", and concrete type "com.foo.Impl", only ".Impl" would be included; and for "com.foo.impl.Impl2" only ".impl.Impl2" would be included.

### PR DESCRIPTION
**Pull request by blacelle**
Fixes #4983.

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java [hunk 1]
```diff
@@ -1583,7 +1583,26 @@ protected TypeResolverBuilder<?> _findTypeResolver(MapperConfig<?> config,
             if (typeInfo.getIdType() == JsonTypeInfo.Id.NONE) {
                 return _constructNoTypeResolverBuilder();
             }
-            b = _constructStdTypeResolverBuilder(config, typeInfo, baseType);
+
+        	// Search for the annotation through the parent classes/hierarchies
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java]: Hmmm. Ideally `AnnotationIntrospector` is not the right place for traversing inheritance hierarchy.

But at the same time, this is simplest solution in a way -- for class annotation case at least.

So, not sure. :-/

File: src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java [hunk 2]
```diff
@@ -1583,7 +1583,26 @@ protected TypeResolverBuilder<?> _findTypeResolver(MapperConfig<?> config,
...
+        	// BEWARE: What if the annotation appears on multiple places? Is there any specific ordering?
+            // Could/should this be a method of Annotated?
+            List<JavaType> superTypes;
+            if (ann instanceof AnnotatedClass) {
+            	superTypes = new ArrayList<>(((AnnotatedClass) ann)._superTypes);
+            	// We want to iterate from
+//            	Collections.reverse(superTypes);
+            } else {
+            	// Could walk the class hierarchy, but how can we get a JavaType from a Class?
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java]: No need: when method/field annotated, declared type MUST be intended base type. So it can and should be no-op -- nothing to add here I think.

File: src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java [hunk 3]
```diff
@@ -1583,7 +1583,26 @@ protected TypeResolverBuilder<?> _findTypeResolver(MapperConfig<?> config,
...
                 return _constructNoTypeResolverBuilder();
             }
-            b = _constructStdTypeResolverBuilder(config, typeInfo, baseType);
+
+        	// Search for the annotation through the parent classes/hierarchies
+        	// BEWARE: What if the annotation appears on multiple places? Is there any specific ordering?
+            // Could/should this be a method of Annotated?
+            List<JavaType> superTypes;
+            if (ann instanceof AnnotatedClass) {
+            	superTypes = new ArrayList<>(((AnnotatedClass) ann)._superTypes);
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java]: We probably want to add an accessor for cleaner access/traversal.

**EDIT**: added `AnnotedClass.getSuperTypes()`.

**Comment by cowtowncoder** [comment]
@blacelle Ok, yes, although I wish traversal did not need to be done in `AnnotationIntrospector`, I suspect that is the way to go instead of huge refactoring trying to have more general mechanism.

So a new PR against `3.x` would be good & I can help get that merged.
Thank you for your patience with this one.

File: src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java (hunk 2 above)
Comment (blacelle) [reply src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java]: Adjusted comment for this branch.

File: src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java (hunk 3 above)
Comment (blacelle) [reply src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java]: Done.

File: src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java (hunk 1 above)
Comment (blacelle) [reply src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java]: I understand doing this in `AnnotationIntrospector ` is lean in current state of things.

**Comment by blacelle** [comment]
@cowtowncoder This is rebased on `3.x` and adjusted following review. Thanks

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java [hunk 4]
```diff
@@ -23,6 +23,11 @@ public class StdTypeResolverBuilder
     protected JsonTypeInfo.Id _idType;
 
     protected JsonTypeInfo.As _includeAs;
+    
+    /**
+     * The type representing the base class. Typically the class holding the JsonTypeInfo annotation
+     */
+    protected JavaType _jsonTypeInfoAnnotatedClass;
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java]: Let's rename as `_detectedBaseType`

File: src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java [hunk 5]
```diff
@@ -269,16 +276,33 @@ protected TypeResolverBuilder<?> _findTypeResolver(MapperConfig<?> config,
...
             //   to map it to "PROPERTY" instead of "EXTERNAL_PROPERTY"
-            if (ann instanceof AnnotatedClass) {
+            if (ann instanceof AnnotatedClass annotatedClass) {
                 JsonTypeInfo.As inclusion = typeInfo.getInclusionType();
                 if (inclusion == JsonTypeInfo.As.EXTERNAL_PROPERTY) {
                     typeInfo = typeInfo.withInclusionType(JsonTypeInfo.As.PROPERTY);
                 }
+
+            	// Search for the annotation through the parent classes/hierarchies
+            	// BEWARE: What if the annotation appears on multiple places? Is there any specific ordering?
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java]: Can change: basically `AnnotatedClass.getSuperTypes()` javadocs should explain it, but ordering is same as what Jackson databind uses itself. So it is stable, defined (minus part where JDK may expose super-interfaces in arbitrary order).

File: src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java [hunk 6]
```diff
@@ -269,16 +276,33 @@ protected TypeResolverBuilder<?> _findTypeResolver(MapperConfig<?> config,
...
+                superTypes = annotatedClass.getSuperTypes();
+            } else {
+            	// when method/field annotated, declared type MUST be intended base type
+            	superTypes = List.of();
             }
-            b = _constructStdTypeResolverBuilder(config, typeInfo, baseType);
+
+            // Look for the javaType holding @JsonTypeInfo, so it can be used as referential package for JsonTypeInfo.Id.MINIMAL_CLASS"
+        	Optional<JavaType> optJavaType = superTypes.stream().filter(type -> null != type.getRawClass().getAnnotation(JsonTypeInfo.class)).findFirst();
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java]: This is part I think we need to change: ALL Jackson annotation access should go through `AnnotationIntrospector`, and no code outside should try directly accessing annotations.

I'll see if I can figure out a new method to add: existing `findPolymorphicTypeInfo()` cannot be changed easily, but an add-on should be possible.

Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java]: Got it: #5836 adds

        public JavaType findPolymorphicBaseType(MapperConfig<?> config,
            AnnotatedClass ac, JsonTypeInfo.Value typeInfo, JavaType assumedBaseType);

method in `AnnotationIntrospector` to call from here.

This may seem like an overkill but helps support functionality wrt JAXB annotations (potentially) and generally better encapsulated annotation access.

File: src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java (hunk 5 above)
Comment (blacelle) [reply src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java]: Totally. Comment was relevant when I was visiting types manually.

**Comment by blacelle** [comment]
BTW @cowtowncoder I have issues to run tests in some IDE (both Eclipse and Intellij) around JMPS/JDK9 modules. It's fine with 2.19 branch (probably not/less/different tests modules).

image

File: src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java (hunk 6 above)
Comment (blacelle) [reply src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java]: Thanks a lot, this is integrated in the PR.

**Comment by cowtowncoder** [comment]
@blacelle I also have problems running tests from Eclipse: need to use "Run Configurations" to select different JDK. I do see problem indicators for `module-info.class` but they do not appear to block running tests.
Maven from command-line has no problems running anything. :-/

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java [hunk 7]
```diff
@@ -23,6 +23,11 @@ public class StdTypeResolverBuilder
     protected JsonTypeInfo.Id _idType;
 
     protected JsonTypeInfo.As _includeAs;
+    
+    /**
+     * The type representing the base class. Typically the class holding the JsonTypeInfo annotation
+     */
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java:31]: `@since 3.2`

File: src/test/java/tools/jackson/databind/jsontype/TestSubtypesSubPackage.java [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+
+import com.fasterxml.jackson.annotation.JsonTypeInfo;
+
+import tools.jackson.databind.ObjectMapper;
+import tools.jackson.databind.jsontype.TestSubtypesSubPackage.SuperType.InnerType;
+import tools.jackson.databind.jsontype.subpackage.SubCSubPackage;
+import tools.jackson.databind.testutil.DatabindTestUtil;
+
+public class TestSubtypesSubPackage extends DatabindTestUtil
+{
```
Comment (cowtowncoder) [inline src/test/java/tools/jackson/databind/jsontype/TestSubtypesSubPackage.java:16]: Add:

```
// For [databind#4983]: `JsonTypeInfo.Id.MINIMAL_CLASS` generates invalid type on sub-package
```

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java [hunk 9]
```diff
@@ -23,6 +23,11 @@ public class StdTypeResolverBuilder
...
+    protected JavaType _detectedBaseType;
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java]: Also make `final` since this need not be mutable.

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java:124]: _detectedBaseType = base._detectedBaseType;

**Comment by cowtowncoder** [comment]
@blacelle Looks pretty good, only minor things to change. But aside from those, before I can merge this we'll need a CLA (unless you have sent one before). It needs to be sent just once before merging the first contribution and is good for all future prs.

Document is here: https://github.com/FasterXML/jackson/blob/main/CLA-jackson-2026.pdf
and the usual way is to print, fill & sign, scan/photo, email to `cla` at fasterxml dot com.

Looking forward to merging this; big thank you for contributing the pr!

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java (hunk 9 above)
Comment (blacelle) [reply src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java]: - If I put final, I'll have to add `_detectedBaseType = null` in multiple constructors. 
- `protected String _typeProperty;` seems similarly `final` but is not explicitely.

~I suggest not adding `final` for homogeneity. Tell me if you confirm I should go with explicit null in other constructor.~

(This may also be a signal that `JavaType detectedBaseType` should be an additional argument to other contructors ; I had a (very) quick look and I did not spot any relevant case, through it is certainly beyong my current understanding).

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java
Comment (blacelle) [reply src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java:124]: Well, that's another case of missed impact in ctor. TY

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java (hunk 9 above)
Comment (blacelle) [reply src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java]: Given the review on one of the constructor, I digged more into the 1 left not-trivial constructor:
```
    public StdTypeResolverBuilder(JsonTypeInfo.Id idType,
            JsonTypeInfo.As idAs, String propName)
    {
        if (idType == null) {
            throw new IllegalArgumentException("idType cannot be null");
        }
        _idType = idType;
        _includeAs = idAs;
        _typeProperty = _propName(propName, _idType);
        this._detectedBaseType = null;
    }
```

It's single usage in the codebase is:
```
    public static StdTypeResolverBuilder noTypeInfoBuilder() {
        return new StdTypeResolverBuilder(JsonTypeInfo.Id.NONE, null, null);
    }
```
I feel  I should add a `JavaType detectedBaseType` parameter, which will be null in `noTypeInfoBuilder()`.

Should I:
- do that and impact existing API? 
- Or do that in an additional constructor, keeping the existing one with a default `this._detectedBaseType = null` (hence increasing API surface area)?

*edit: I went with first option, editting the ctor signature*

**Comment by blacelle** [comment]
@cowtowncoder CLA is sent. PR is progressed ; one element looks opinionated.

Thanks a lot, the contribution experience is quite smooth.

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java (hunk 9 above)
Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java]: Sorry, no, please do not remove existing constructors (without deprecation). Let's assign `null` instead in existing constructor.

Comment (blacelle) [reply src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java]: Are you sure we should not add one constructor, enabling setting this ` final` field?

Comment (blacelle) [reply src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java]: I went with option2:
- keep existing constructor, with null `detectedBaseType`, and with a deprecation notice
- add a similar construtor requiring an additional `detectedBaseType`

Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java]: That's a good approach, thanks! Did not mean no new constructor at all (we do need to pass new base type!) just that not effectively remove old ones without deprecation.

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java [hunk 10]
```diff
@@ -55,23 +62,34 @@ public class StdTypeResolverBuilder
     /**********************************************************************
      */
 
-    public StdTypeResolverBuilder() { }
+    public StdTypeResolverBuilder() { 
+        this._detectedBaseType = null;
+    }
 
-    public StdTypeResolverBuilder(JsonTypeInfo.Value settings) {
+    public StdTypeResolverBuilder(JsonTypeInfo.Value settings, JavaType detectedBaseType) {
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java:82]: Add

```
/**
 * @since 3.2
 */
```

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java [hunk 11]
```diff
@@ -55,23 +62,34 @@ public class StdTypeResolverBuilder
...
     }
 
+    @Deprecated(since = "Prefer similar constructor accepting a JavaType detectedBaseType")
     public StdTypeResolverBuilder(JsonTypeInfo.Id idType,
             JsonTypeInfo.As idAs, String propName)
+    {
+        this(idType, idAs, propName, null);
+    }
+
+    public StdTypeResolverBuilder(JsonTypeInfo.Id idType,
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java:102]: Needs

```
/**
 * @since 3.2
 */
```

as well

**Review by cowtowncoder — COMMENTED** [review]
Almost there, just minor Javadoc additions needed.

**Comment by blacelle** [comment]
Done. I also restored the `StdTypeResolverBuilder(JsonTypeInfo.Value settings)` constructor.

File: src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java [hunk 12]
```diff
@@ -55,23 +62,47 @@ public class StdTypeResolverBuilder
     /**********************************************************************
      */
 
-    public StdTypeResolverBuilder() { }
+    public StdTypeResolverBuilder() { 
+        this._detectedBaseType = null;
+    }
 
+    @Deprecated(since = "Prefer similar constructor accepting a JavaType detectedBaseType")
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java]: Note: `since` means version in which deprecation happens, so needs to be `3.2`.
There is no description property; but you can add javadoc comment:

```
/**
 * @deprecated Prefer similar constructor accepting a JavaType detectedBaseType
 */
```

**Review by cowtowncoder — APPROVED** [review]

File: src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java [hunk 13]
```diff
@@ -297,7 +312,7 @@ protected TypeResolverBuilder<?> _findTypeResolver(MapperConfig<?> config,
     }
 
     protected TypeResolverBuilder<?> _constructStdTypeResolverBuilder(MapperConfig<?> config,
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java:314]: Whops. Change of this signature broke XML backend: will patch.

(granted, sub-classing and overriding `protected` method not clean extension but....
