### PR TITLE
Fix `Coercion` fail message around `Array` and `Object`.

### LINKED ISSUE #3924: Incorrect target type when disabling coercion
When disabling coercions and providing a wrong type on an array element, the error message is specifying that we are trying to coerce the type of the array when it should mention we are trying to coerce the type of the element of the array. See the example below. This is another instance of https://github.com/FasterXML/jackson-databind/issues/3690/.

```
// Test class.
public static class Input<T> {
    private T field;

    public T getField() {
        return field;
    }

    public void setField(T field) {
        this.field = field;
    }
}

// Building a strict ObjectMapper.
ObjectMapper objectMapper = JsonMapper.builder()
    .withCoercionConfigDefaults(config -> {
        config.setCoercion(CoercionInputShape.Boolean, CoercionAction.Fail)
            .setCoercion(CoercionInputShape.Integer, CoercionAction.Fail)
            .setCoercion(CoercionInputShape.Float, CoercionAction.Fail)
            .setCoercion(CoercionInputShape.String, CoercionAction.Fail)
            .setCoercion(CoercionInputShape.Array, CoercionAction.Fail)
            .setCoercion(CoercionInputShape.Object, CoercionAction.Fail);
    })
    .build();
TypeFactory typeFactory = objectMapper.getTypeFactory();

// Test.
JavaType arrayType = typeFactory.constructParametricType(List.class, String.class);
JavaType inputType = typeFactory.constructParametricType(Input.class, arrayType);
try {
    // Returns class java.lang.String + VALUE_NUMBER_INT -> correct.
    objectMapper.readValue("{ \"field\": [ 1 ] }", inputType);
    // Returns class java.util.ArrayList + START_ARRAY -> was expecting target type to be String.
    objectMapper.readValue("{ \"field\": [ [ 1 ] ] }", inputType);
    // Returns class java.util.ArrayList + START_OBJECT -> was expecting target type to be String.
    objectMapper.readValue("{ \"field\": [ { \"field\": 1 } ] }", inputType);
} catch (MismatchedInputException exception) {
    JsonParser parser = (JsonParser) exception.getProcessor();
    System.out.println(exception.getTargetType());
    System.out.println(parser.currentToken());
}

// A truly strict String parser.
// If we register this deserializer in the ObjectMapper above we will then get the expected target type.
public class StringDeserializer extends JsonDeserializer<String> {
    @Override
    public String deserialize(JsonParser parser, DeserializationContext context) throws IOException {
        if (!parser.hasToken(VALUE_STRING)) {
            throw context.wrongTokenException(parser, String.class, VALUE_STRING, null);
        }

        return parser.getText();
    }
}
```

This is our test suite for JSON strict parsing which we have used to open many such issues in the past, in case you want to take inspiration for Jackson tests.
[Test.zip](https://github.com/FasterXML/jackson-databind/files/11461536/Test.zip)

### PR DESCRIPTION
**Pull request by JooHyukKim**
resolves #3924

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java [hunk 1]
```diff
@@ -1421,13 +1421,16 @@ protected final String _parseString(JsonParser p, DeserializationContext ctxt,
             return ob.toString();
         // 29-Jun-2020, tatu: New! "Scalar from Object" (mostly for XML)
         case JsonTokenId.ID_START_OBJECT:
+            act = _checkObjectToStringCoercion(p, ctxt, rawTargetType);
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java:1424]: Hmmmh. Let's not add this call -- the thing is that this only applies to XML backend, and is more of a work-around in that case, not a real coercion. For all other backends, including JSON, there will be failure for incompatible coercion.

So for time being, let's remove this check.

File: src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java [hunk 2]
```diff
@@ -1421,13 +1421,16 @@ protected final String _parseString(JsonParser p, DeserializationContext ctxt,
...
             return ctxt.extractScalarFromObject(p, this, _valueClass);
         case JsonTokenId.ID_NUMBER_INT:
             act = _checkIntToStringCoercion(p, ctxt, rawTargetType);
             break;
         case JsonTokenId.ID_NUMBER_FLOAT:
             act = _checkFloatToStringCoercion(p, ctxt, rawTargetType);
             break;
+        case JsonTokenId.ID_START_ARRAY:
+            act = _checkArrayToStringCoercion(p, ctxt, rawTargetType);
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java:1433]: Missing `break` after check?

File: src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java [hunk 3]
```diff
@@ -1589,6 +1592,26 @@ protected CoercionAction _checkBooleanToStringCoercion(JsonParser p, Deserializa
...
+            Class<?> rawTargetType)
+        throws IOException
+    {
+        return _checkToStringCoercion(p, ctxt, rawTargetType, p.getText(), CoercionInputShape.Array);
+    }
+    
+    /**
+     * @since 2.16
+     */
+    protected CoercionAction _checkObjectToStringCoercion(JsonParser p, DeserializationContext ctxt,
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java:1608]: No longer needed since call shouldn't be made, so remove.

**Comment by cowtowncoder** [comment]
So as per comments, Object check case can not be added because of oddities wrt how it is used for XML.

But I must say I am not 100% sure how this actually fixes the problem -- we are not coercing Array to anything, but rather contents within Array? 
So why would we need to add checks for Array coercion here?

File: src/test/java/com/fasterxml/jackson/databind/convert/DisableCoercions3690Test.java [hunk 4]
```diff
@@ -35,4 +49,51 @@ public void testFailMessage3690() throws Exception
...
+                new String[]{"{ \"field\": [ { \"field\": 1 } ] }", "Cannot coerce Object value ({)", "to `java.lang.String` value"}
+        };
+
+        // Act & Assert
+        for (String[] input : inputs) {
+            _verifyFailedCoercionWithInvalidFormat(objectMapper, inputType, input);
+        }
+    }
+
+    private void _verifyFailedCoercionWithInvalidFormat(ObjectMapper objectMapper, JavaType inputType, String[] input)
```
Comment (cowtowncoder) [inline src/test/java/com/fasterxml/jackson/databind/convert/DisableCoercions3690Test.java:85]: Why input array instead of named arguments?

**Comment by cowtowncoder** [comment]
Ok. So, after reading, re-reading things, I am not sure this is quite the way to fix the problem.

The thing is that aside from "Scalar from Object" work-around needed for XML backend (failing for others including JSON), there is no coercion we would actually consider: we are just failing  in general by calling `ctxt.handleUnexpectedToken()` -- but there we are passing `getValueType(ctxt)` which is wrong.

So I think test change is good, but the fix should be much simpler: I'll add a note to point it.

File: src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java (hunk 1 above)
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java:1424]: Ideally should not be needed either, BUT may need to verify how "ctxt.extractScalarFromObject()" works, so...

File: src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java [hunk 5]
```diff
@@ -1421,13 +1421,16 @@ protected final String _parseString(JsonParser p, DeserializationContext ctxt,
             return ob.toString();
         // 29-Jun-2020, tatu: New! "Scalar from Object" (mostly for XML)
         case JsonTokenId.ID_START_OBJECT:
+            act = _checkObjectToStringCoercion(p, ctxt, rawTargetType);
             return ctxt.extractScalarFromObject(p, this, _valueClass);
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java:1425]: ... here I think we do need to pass `rawTargetType` and NOT `_valueClass`. And that should do the trick.

**Comment by cowtowncoder** [comment]
Ok so I can't attach code review comment in place, so this line:

```
return (String) ctxt.handleUnexpectedToken(getValueType(ctxt), p);
```

needs to be changed to, I think:

```
return (String) ctxt.handleUnexpectedToken(rawTargetType, p);
```

and that's the proper fix here.

Plus change to call `ctxt.extractScalarFromObject(...)` to also pass `rawTargetType`, not `_valueClass`.

**Review by cowtowncoder — APPROVED** [review]
