### PR TITLE
Fix: Support class-level @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY) on custom Collection subclasses

### LINKED ISSUE #5522: `@JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)` doesn't work on custom Collection subclass
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

According to the Javadoc for `@JsonFormat`, the annotation *"Can be used on Classes (types) as well, for modified default behavior"*.

However, when `@JsonFormat(with = Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)` is applied directly to a custom `Collection` subclass (e.g., `class MyList extends ArrayList`), it is ignored durng deserialization. The configuration only works when applied to the field (property), but fails when applied to the class declaration.

### Version Information

3.0

### Reproduction

Here is a minimal reproduction case. The `CustomNumberList` has the annotation enabled, but deserialization fails with `MismatchedInputException` when the input is a single value because the class-level annotation is ignored.

```java
class CollectionDeserializerTest {

    @JsonFormat(with = Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
    static class CustomNumberList extends ArrayList<Number>{
    }

    static class CustomClassForNumber {
        private CustomNumberList value;

        public CustomNumberList getValue() {
            return value;
        }
        public void setValue(CustomNumberList value) {
            this.value = value;
        }
    }

    private final ObjectMapper objectMapper = JsonMapper.builder()
        .disable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
        .build();

    @Test
    void testCustomNumberCollectionDeserialize() throws Exception {
        // given
        String jsonValue = """
            {
                "value": 1
            }
            """;

        // when
        CustomClassForNumber result = objectMapper.readValue(jsonValue, CustomClassForNumber.class);

        // then
        assertThat(result.value)
            .hasSize(1)
            .containsExactly(1);
    }
}
```

### Analysis & Context

I investigated `CollectionDeserializer` (and `StringCollectionDeserializer`) and found that `findFormatFeature` is called using `Collection.class` as the type argument.

This logic currently checks for:

1. Property-level annotations.
2. Config overrides for `Collection.class`.

It misses the check for annotations on the actual container type itself.

### Proposed Solution

Instead of replacing `Collection.class` (which might break existing `ConfigOverride` behavior for generic `Collection` types), I propose adding a **fallback check** using `AnnotationIntrospector` if the initial lookup returns `null`.

This approach respects the priority and maintains backward compatibility:

1. Property Annotation
2. ConfigOverride (Collection)
3. **Class Annotation (Custom Collection)** <-- Added this

I will submit a PR with the fix and test cases shortly.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jher235**
### Issue
Closes #5522 
### 1. What does this PR do?

This PR extends `CollectionDeserializer` to respect `@JsonFormat` annotations declared directly on custom `Collection` subclasses.

Currently, `CollectionDeserializer` ignores class-level annotations (e.g., `@JsonFormat class MyList ...`) and only considers property-level configurations or global `ConfigOverride`. This PR adds a **fallback mechanism** to explicitly check the container type's annotations when no property-level configuration is found.

### 2. Why is this change necessary?

**A. Addressing Feature Inconsistency**
While `@JsonFormat` is allowed on classes, `CollectionDeserializer` currently ignores it for enabling single-value uwrapping. This aligns the behavior with other types (like POJOs) where class-level features are respected.

**B. Enabling Fine-Grained Control**
Users currently rely on `mapper.configOverride(Collection.class)` which affects **ALL** collections globally.
This change allows users to enable `ACCEPT_SINGLE_VALUE_AS_ARRAY` for specific collection types only:

```java
// Now supported:
@JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
public class FlexibleList<E> extends ArrayList<E> { }

class MyDTO {
    private FlexibleList<String> items;
}
```

### 3. Implementation Details

I implemented this as a **fallback** to ensure full backward compatibility.

**Resolution Order:**

1. **Property Annotation** (Highest priority, unchanged)
2. **ConfigOverride for `Collection.class`** (Existing global config, unchanged)
3. **Concrete Container Class Annotation** (New fallback logic for `ACCEPT_SINGLE_VALUE_AS_ARRAY`)
4. **Global DeserializationFeature**

Note on Safety:

I purposely maintained the existing findFormatFeature(..., Collection.class) call as the primary check. Replacing Collection.class with the concrete type would break existing ConfigOverride settings for generic collections. The new check is strictly additive.

### 4. Test Coverage

Added `CollectionDeserializer5522Test` covering:

- `@JsonFormat` on custom collection subclass is respected.
- Property-level annotation still takes precedence.
- Standard `Collection` behavior remains unaffected.

### CODE REVIEW

File: src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java [hunk 1]
```diff
@@ -172,6 +172,13 @@ public CollectionDeserializer createContextual(DeserializationContext ctxt,
         //   comes down to "List vs Collection" I suppose... for now, pass Collection
         Boolean unwrapSingle = findFormatFeature(ctxt, property, Collection.class,
                 JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
+        if (unwrapSingle == null) {
+            tools.jackson.databind.introspect.AnnotatedClass ac = ctxt.introspectClassAnnotations(_containerType);
```
Comment (pjfanning) [inline src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java]: Can you import this class instead of fully referencing it here?

Can you create a static method that StringCollectionDeserializer.java‎ can use too instead of duplicating the code in StringCollectionDeserializer? Or if there is a shared superclass, you could put the method there.

File: src/test/java/tools/jackson/databind/deser/jdk/CollectionDeserializer5522Test.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+        // when
+        CustomClassForListField result = objectMapper.readValue(jsonValue, CustomClassForListField.class);
+
+        // then
+        assertThat(result.value)
+            .hasSize(1)
+            .containsExactly("test");
+    }
+
+}
```
Comment (pjfanning) [inline src/test/java/tools/jackson/databind/deser/jdk/CollectionDeserializer5522Test.java]: new line at end of file please

**Comment by JooHyukKim** [comment]
@jher235 Can we also have another test case with Pojo-wrapping-CustomNumberList? Currently CustomNumberList is at root-level. 

Wonder how behavior might change...

**Comment by jher235** [comment]
Hello @JooHyukKim 

Current test case `testCustomNumberCollectionDeserialize` actually uses `CustomClassForNumber`, which is a POJO wrapper containing `CustomNumberList` as a field (`value`).
``` java 
static class CustomClassForNumber {
    private CustomNumberList value;
    ...
}
```
Is this the "Pojo-wrapping" test you were looking for?
Or would you like me to add a "Root-level" test (deserializing CustomNumberList directly) as well?

File: src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java (hunk 1 above)
Comment (jher235) [reply src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java]: Sure, I will fix the import. Regarding the duplication, I will extract the added logic into a static method in CollectionDeserializer and have StringCollectionDeserializer call it.

File: src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java [hunk 3]
```diff
@@ -602,4 +598,18 @@ public void handleResolvedForwardReference(DeserializationContext ctxt, Object i
             _parent.resolveForwardReference(ctxt, id, value);
         }
     }
+
+    public static Boolean findFormatFeatureOrClassFallback(DeserializationContext ctxt,
```
Comment (pjfanning) [inline src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java]: remove 'public', package private is fine

File: src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java [hunk 4]
```diff
@@ -172,6 +173,8 @@ public CollectionDeserializer createContextual(DeserializationContext ctxt,
         //   comes down to "List vs Collection" I suppose... for now, pass Collection
         Boolean unwrapSingle = findFormatFeature(ctxt, property, Collection.class,
                 JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
+        unwrapSingle = findFormatFeatureOrClassFallback(ctxt, _containerType, unwrapSingle,
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java]: Ok, logic makes sense, but I think precedence is not quite right since the new value has lower precedence than everything else. It should be in the middle; from highest to lowest:

1. Property-override
2. Collection class annotation (new thing added here)
3. ConfigOverride for `Collection`
4. Global `JsonFormat` via ConfigOverride

But maybe what is here is good enough... I'll have to think about it.

File: src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java [hunk 5]
```diff
@@ -595,4 +598,18 @@ public void handleResolvedForwardReference(DeserializationContext ctxt, Object i
             _parent.resolveForwardReference(ctxt, id, value);
         }
     }
+
+    static Boolean findFormatFeatureOrClassFallback(DeserializationContext ctxt,
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java]: Change to non-static and don't pass `_containerType`, refer from here.

File: src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java [hunk 6]
```diff
@@ -595,4 +598,18 @@ public void handleResolvedForwardReference(DeserializationContext ctxt, Object i
...
+        JavaType type, Boolean unwrapSingle, JsonFormat.Feature feature)
+    {
+        if (unwrapSingle != null) {
+            return unwrapSingle;
+        }
+        AnnotatedClass ac = ctxt.introspectClassAnnotations(type);
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java]: Ideally we would not need to re-introspect (adds to startup overhead)... since `BasicDeserializerFactory.createCollectionDeserializer(...)` has `BeanDescription.Supplier beanDescRef` and could pass it to `CollectionDeserializer`.

That'd require a bit of refactoring that might be worth it: instead of direct call to constructor, should call factory method... I'll go ahead and do that part of refactoring now.

Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java]: Ok, #5525 added 

```
    public static CollectionDeserializer create(JavaType collectionType,
            BeanDescription.Supplier beanDescRef,
            ValueDeserializer<Object> valueDeser,
            TypeDeserializer valueTypeDeser, ValueInstantiator valueInstantiator)

```

where

    beanDescRef.getClassAnnotations();

can be used to get introspected class annotations of target type. This could be passed to constructor (new overload with added parameter), retained in a `transient` field, to be available for `createContextual()`. May sound like lots of work but annotation introspection is becoming bigger and bigger problem with start up overhead with Jackson so I'd like to limit additional calls to re-introspecting again and again.

**Comment by jher235** [comment]
Hello @cowtowncoder  
Thanks for the detailed review!

I implemented the logic as non-static instance methods in both classes as suggested. I decided to keep them as separate helper methods (findFormatFeatureOrClassFallback) instead of inlining them into createContextual, as it keeps the main logic much cleaner.
Also, I set the helper method to protected in CollectionDeserializer (for extensibility) but private in StringCollectionDeserializer since it is a final class.

**Comment by cowtowncoder** [comment]
+1 for separate lookup methods instead of inlining. Static vs non-static matter of preference, not a big deal for me.

But let's see if we can avoid re-introspecting class annotations, as per my suggestion.

**Comment by jher235** [comment]
Actually, I did it in my latest commit `9935f3d`. Could you please take a look?

File: src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java [hunk 7]
```diff
@@ -217,6 +228,21 @@ public CollectionDeserializer createContextual(DeserializationContext ctxt,
...
     }
 
+    protected Boolean findFormatFeatureOrClassFallback(Boolean unwrapSingle,
+        JsonFormat.Feature feature)
+    {
+        if (unwrapSingle != null) {
+            return unwrapSingle;
+        }
+        if(_classAnnotations != null){
+            JsonFormat formatAnnotation = _classAnnotations.get(JsonFormat.class);
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/jdk/CollectionDeserializer.java]: Right idea, but implementation needs bit more work: the only code that should ever access concrete annotations is `[Jackson]AnnotationIntrospector`. So we need to hold on to`AnnotatedClass`, pass that to `AnnotationIntrospector.findFormat()`.

(the reason `AnnotationIntrospector` needs to be involved is mainly for 2 things:
1. mix-in annotations
2. non-Jackson (JAXB) annotation suppor
but also gives a powerful extension point for overrides).

**Comment by cowtowncoder** [comment]
> Actually, I did it in my latest commit `9935f3d`. Could you please take a look?

Nice! Much better, just needs work to get `AnnotationIntrospector` involved (as per my inline note), instead of direct annotation lookup.

**Comment by jher235** [comment]
@cowtowncoder 
I refactored Collection deserializers to use `AnnotatedClass` instead of `Annotations` following your feedback.

**Comment by cowtowncoder** [comment]
Thank you @jher235 -- I hope to review this within couple of days (on christmas vacation).
