### PR TITLE
[databind#4849] Allow standard defaultTyping with `EnumSet<E>`

### LINKED ISSUE #4849: Not able to deserialize Enum with default typing after upgrading 2.15.4 -> 2.17.1
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

After bumping up the version to 2.17.1 I'm not longer able to deserialize values serialized with the version 2.15.4.
Moreover, values serialized with the new version (2.17.1) give error when deserializing.

### Version Information

2.17.1

### Reproduction

```java
package com.kze.test;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.jsontype.BasicPolymorphicTypeValidator;
import com.fasterxml.jackson.databind.jsontype.PolymorphicTypeValidator;
import com.fasterxml.jackson.databind.jsontype.impl.StdTypeResolverBuilder;

import java.io.IOException;
import java.util.EnumSet;

import static com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY;
import static com.fasterxml.jackson.databind.ObjectMapper.DefaultTyping.NON_FINAL;
import static com.kze.test.TestClazz.TestEnum.TEST_ENUM_VALUE;

public class TestClazz {

    public enum TestEnum {
        TEST_ENUM_VALUE
    }

    public static void main(String[] args) throws IOException {

        ObjectMapper mapper = new ObjectMapper();

        final PolymorphicTypeValidator validator = BasicPolymorphicTypeValidator.builder()
                .allowIfSubType("com.kze.test")
                .allowIfSubType("java")
                .build();

        ObjectMapper.DefaultTypeResolverBuilder resolverBuilder
                = new ObjectMapper.DefaultTypeResolverBuilder(NON_FINAL, validator) {
            @Override
            public boolean useForType(JavaType t) {
                return true;
            }
        };

        StdTypeResolverBuilder stdTypeResolverBuilder = resolverBuilder
                .init(JsonTypeInfo.Id.CLASS, null)
                .inclusion(PROPERTY);

        mapper.setDefaultTyping(stdTypeResolverBuilder);
        mapper.configure(JsonParser.Feature.INCLUDE_SOURCE_IN_LOCATION, true);

        EnumSet<TestEnum> input = EnumSet.of(TEST_ENUM_VALUE);
        String inputJson = mapper.writeValueAsString(input);
        System.out.println(inputJson);

        Object inputDeserialized = mapper.readValue(inputJson, Object.class);
        System.out.println(inputDeserialized);
    }

}

``` 

Version 2.15.4 output 
```
["java.util.EnumSet<com.kze.test.TestClazz$TestEnum>",["TEST_ENUM_VALUE"]]
[TEST_ENUM_VALUE]
```

Version 2.17.1 error:
```
["java.util.EnumSet<com.kze.test.TestClazz$TestEnum>",["TEST_ENUM_VALUE"]]
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (VALUE_STRING), expected START_ARRAY: need Array value to contain `As.WRAPPER_ARRAY` type information for class com.kze.test.TestClazz$TestEnum
 at [Source: (String)"["java.util.EnumSet<com.kze.test.TestClazz$TestEnum>",["TEST_ENUM_VALUE"]]"; line: 1, column: 56] (through reference chain: java.util.RegularEnumSet[0])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1913)
	at com.fasterxml.jackson.databind.DeserializationContext.reportWrongTokenException(DeserializationContext.java:1699)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._locateTypeId(AsArrayTypeDeserializer.java:141)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:96)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromScalar(AsArrayTypeDeserializer.java:66)
	at com.fasterxml.jackson.databind.deser.std.StdScalarDeserializer.deserializeWithType(StdScalarDeserializer.java:66)
	at com.fasterxml.jackson.databind.deser.std.EnumSetDeserializer._deserialize(EnumSetDeserializer.java:281)
	at com.fasterxml.jackson.databind.deser.std.EnumSetDeserializer.deserialize(EnumSetDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.EnumSetDeserializer.deserialize(EnumSetDeserializer.java:24)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:238)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR.deserializeWithType(UntypedObjectDeserializerNR.java:112)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
	at com.kze.test.TestClazz.main(TestClazz.java:52)
```

### Expected behavior

Should be able to deserialized values

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JooHyukKim**
resolves #4849 
possible backport to 2.17

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsArrayTypeDeserializer.java [hunk 1]
```diff
@@ -146,6 +146,11 @@ protected String _locateTypeId(JsonParser p, DeserializationContext ctxt) throws
                             +ClassUtil.classNameOf(_idResolver)+") returned `null`");
                 }
                 return id;
+            }
+            // [databind#4849] Since 2.18.3, Should maybe allow defaultTyping without defaultImpl if type is already known
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsArrayTypeDeserializer.java:150]: @JooHyukKim Thinking this through, I don't think this is a proper fix, even tho it works around the specific failure here. I'll elaborate on the issue itself, but I think the problem may have been introduced by #4214 (in 2.17.0). Problem for tested case specifically is that customized `DefaultTypeResolverBuilder` forces addition of type information for EVERY type (for whatever reason), due to:

```
            @Override
            public boolean useForType(JavaType t) {
                return true;
            }
```

Or, it should. But while `EnumSetDeserializer` now expects polymorphic type id for `EnumSet` AND every `Enum` contained (... why is this desired?), I think `EnumSetSerializer` does not write said type id. And I guess it should.

Comment (JooHyukKim) [reply src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsArrayTypeDeserializer.java:150]: Ah okay. Let's close this for now. Will read through ur comment later.

**Comment by cowtowncoder** [comment]
Ok: change the fix the way I think it might work -- solves the round-trip case, but serialization is different as type ids included for enum values.
But also now fails one earlier test; will try to figure it out tomorrow.

Might also consider opposite path of sort of undoing #4214 in part, maybe -- such that contents (Enums) of `EnumSet` would never have type id.
But in a way that still allows 4214 case to work.

File: src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsArrayTypeDeserializer.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsArrayTypeDeserializer.java]: I committed my changes but it's very much work in progress. Too tired to continue for today, will pick up tomorrow :)

**Comment by cowtowncoder** [comment]
Ah ok. So the problem wrt #4214 -- after removing expectation of deserializer expecting type id -- is this:

1. When serializing `EnumSet` value declared as plain `Set`, regular `CollectionSerializer` is used, NOT `EnumSetSerializer` -- and `CollectionSerializer` includes Type Id for contents if so requested. Whereas `EnumSetSerializer` won't.
2. But... Polymorphic type is still recognized as `EnumSet`, so type id for Collection itself is included
3. Due to (2), correct deserializer -- `EnumSetDeserializer` is used. And that will now not expect Type Id (since matching `EnumSetSerializer` would not add it).

So. Need to think of possible way to suppress Type Id inclusion for elements even with `CollectionSerializer`. Might need to resort to bit of hack, even :)

File: src/main/java/com/fasterxml/jackson/databind/ser/std/CollectionSerializer.java [hunk 2]
```diff
@@ -26,6 +27,15 @@ public class CollectionSerializer
 {
     private static final long serialVersionUID = 1L;
 
+    /**
+     * Flag that indicates that we may need to check for EnumSet dynamically
+     * during serialization: problem being that we can't always do it statically.
+     * But we can figure out when there is a possibility wrt type signature we get.
+     *
+     * @since 2.18.3
```
Comment (JooHyukKim) [inline src/main/java/com/fasterxml/jackson/databind/ser/std/CollectionSerializer.java:35]:
```suggestion
     * @since 2.19
```

File: release-notes/VERSION-2.x [hunk 3]
```diff
@@ -31,15 +31,18 @@ Project: jackson-databind
  (reported by Eduard G)
 #4773: `SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS` should not apply to Maps
   with uncomparable keys
- (requested by @nathanukey)
+ (requested by @nathanukey
+#4849 Not able to deserialize Enum with default typing after upgrading 2.15.4 -> 2.17.1
+ (reported by Kornel Zemla)
+ (fix by Joo-Hyuk K)
```
Comment (JooHyukKim) [inline release-notes/VERSION-2.x:37]: Seems right lol

```suggestion
```

**Review by JooHyukKim — COMMENTED** [review]
@cowtowncoder great work!

File: release-notes/VERSION-2.x (hunk 3 above)
Comment (cowtowncoder) [reply release-notes/VERSION-2.x:37]: Well, ok. :)

File: src/main/java/com/fasterxml/jackson/databind/ser/std/CollectionSerializer.java [hunk 4]
```diff
@@ -38,22 +48,17 @@ public class CollectionSerializer
...
-     */
-    @Deprecated // since 2.6
-    public CollectionSerializer(JavaType elemType, boolean staticTyping, TypeSerializer vts,
-            BeanProperty property, JsonSerializer<Object> valueSerializer) {
-        // note: assumption is 'property' is always passed as null
-        this(elemType, staticTyping, vts, valueSerializer);
+        // Unfortunately we can't check for EnumSet statically (if type indicated it,
+        // we'd have constructed `EnumSetSerializer` instead). But we can check that
+        // element type could possibly be an Enum.
+        _maybeEnumSet = elemType.isEnumType() || elemType.isJavaLangObject();
```
Comment (JooHyukKim) [inline src/main/java/com/fasterxml/jackson/databind/ser/std/CollectionSerializer.java:54]: For 3.x version, would it be worth the effort trying to find other way instead of this?
And also parts with below code

```
// [databind#4849]/[databind#4214]: need to check for EnumSet
        final TypeSerializer typeSer = (_maybeEnumSet && value instanceof EnumSet<?>)
                ? null : _valueTypeSerializer;
                
```

**Comment by cowtowncoder** [comment]
Ok. So, fix is quite ugly, but I cannot think of a cleaner way to achieve this.
Basically we get "wrong" serializer (`CollectionSerializer`) in cases where nominal type is not `EnumSet`, and need to make `CollectionSerializer` aware of having to skip inclusion of type id for elements for case where collection happens to be `EnumSet`.

There was discrepancy b/w serialization (was not adding type id) vs deserialization (was expecting type id) in some cases. So, fix was also to remove earlier (#4214) changes that added type id handling for `EnumSetDeserializer`).

And why is type id not needed/wanted? Because for polymorphic typing we already have parent type id identified as something like `java.util.EnumMap<EnumType>`; anything else is redundant.

Will merge into 2.19 due to somewhat extensive change; basically changes serialization of `EnumSet` in some (hopefully rare) cases. So while new mechanism works better, there could be interoperability issues and there's no real way to avoid this.

File: src/main/java/com/fasterxml/jackson/databind/ser/std/CollectionSerializer.java (hunk 4 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/ser/std/CollectionSerializer.java:54]: If there is a way, sure, it would be great to get rid of this work-around.
But I am not sure how, considering the problem itself and how it occurs.
That is: I do not know how this could be avoided at all, regardless of compatibility concerns.
