### PR TITLE
Fix : Allow deserialization of concrete subtypes of `@JsonTypeInfo` target type

### LINKED ISSUE #2968: Deserialization of `@JsonTypeInfo` annotated type fails with missing type id even for explicit concrete subtypes
When attempting to deserialize to a concrete class that is part of a polymorphic type hierarchy, an InvalidTypeIdException is thrown if the JSON does not contain the type id field. Example:

```java
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = Foo.class, name = "foo"),
    @JsonSubTypes.Type(value = Bar.class, name = "bar")})
public interface Base {}

public class Foo implements Base {}

public class Bar implements Base {}

ObjectMapper mapper = new ObjectMapper();

mapper.readerFor(Foo.class).readValue("{}"); // throws InvalidTypeIdException
mapper.readValue("{}", Foo.class); // throws InvalidTypeIdException
```

While I understand *why* this happens, as Jackson is finding the JsonTypeInfo / JsonSubTypes annotations on the interface, it is counterintuitive to me. In this instance, I am instructing the mapper as to the specific concrete class to deserialize to, so consulting those annotations seems unnecessary. Perhaps checking if the class / type supplied to readerFor / readValue matches exactly one of the classes listed in JsonSubType could be a fallback if the type id property is not found?

So far, the only workaround I've found is to do something like this:

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NONE)
public class Foo implements Base {}
```

but then that means serializing a Foo instance would not get the type id property. Perhaps a custom TypeIdResolver or SubTypeResolver could also be used, but having the described behavior baked in seems like a sensible default to me. Thoughts?

### PR DESCRIPTION
**Pull request by JooHyukKim**
### Description
- resolves #2968

### History of (failed attempts)

1. Make `DeserializationContext.indRootValueDeserializer(JavaType *type)*` return TypedWrapperDeser **ONLY IF target type is NOT concrete**
    - Too many failed classes.

2. Make `DeserializationContext.handleMissingTypeId()` return base JavaType instead of Error at the end

    - returning was NOT the purpose of the `handleMissingTypeId` method
    - and fails a couple of tests

3. Before throwing `InvalidTypeIdException` in `AsPropertyTypeDeserializer._handleMissingTypeId()` within`AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl()` method, check if current type has`TypeResolverBuilder` attached.

    - has performance issues even with caching the result of "type-info checking".

### CODE REVIEW

**Comment by cowtowncoder** [comment]
No, I am sorry, this is not the way to go about it. Concrete types have subtypes too; it is not possible to assume only non-concrete types require `TypeDeserializer`s.

You can see that this is not going to work by amount of unit test fail with CI runs.

File: src/main/java/com/fasterxml/jackson/databind/DeserializationContext.java [hunk 1]
```diff
@@ -657,11 +657,15 @@ public final JsonDeserializer<Object> findRootValueDeserializer(JavaType type)
...
         }
         deser = (JsonDeserializer<Object>) handleSecondaryContextualization(deser, null, type);
-        TypeDeserializer typeDeser = _factory.findTypeDeserializer(_config, type);
-        if (typeDeser != null) {
-            // important: contextualize to indicate this is for root value
-            typeDeser = typeDeser.forProperty(null);
-            return new TypeWrappedDeserializer(typeDeser, deser);
+
+        // @since 2.15 only get TypedDeserializer if we are deserializing with Abstract target type
+        if (!type.isConcrete()) {
```
[the remark this answers is not in the document]
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/DeserializationContext.java:662]: Correct; that is not the test we can use here.

File: src/main/java/com/fasterxml/jackson/databind/DeserializationContext.java [hunk 2]
```diff
@@ -1604,7 +1605,7 @@ public JavaType handleMissingTypeId(JavaType baseType,
 //        if (!isEnabled(DeserializationFeature.FAIL_ON_INVALID_SUBTYPE)) {
 //            return null;
 //        }
-        throw missingTypeIdException(baseType, extraDesc);
+        return baseType;
```
[the remark this answers is not in the document]
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/DeserializationContext.java:1608]: Unfortunately I don't think this is right either. At this point error is being detected and we don't have good information on what should be done.

Figuring out something is not a problem needs to occur earlier when there is more information available: keep in mind that this method gets called in cases where type id is missing and it is an actual problem.

**Comment by cowtowncoder** [comment]
Thank you for looking into this issue @JooHyukKim -- it is a highly requested one to fix!

Perhaps you will be able to find a working solution solution that solves the problem without causing other failures (that is, things need to fail for cases where type id would be required).

**Comment by cowtowncoder** [comment]
> Btw, no worries, It is fun to work on things around here.👍🏻

I am very happy to hear that! Your contributions are welcome and much appreciated!

File: src/test/java/com/fasterxml/jackson/databind/jsontype/TestBaseTypeAsDefault.java [hunk 3]
```diff
@@ -60,12 +60,9 @@ public void testNegativeForParent() throws Exception {
...
     public void testNegativeForChild() throws Exception {
-        try {
-            /*Object o =*/ MAPPER_WITHOUT_BASE.readerFor(Child.class).readValue("{}");
-            fail("Should not pass");
-        } catch (InvalidTypeIdException ex) {
-            assertTrue(ex.getMessage().contains("missing type id property '@class'"));
-        }
+        Child child = MAPPER_WITHOUT_BASE.readerFor(Child.class).readValue("{}");
+
+        assertEquals(Child.class, child.getClass());
```
[the remark this answers is not in the document]
Comment (cowtowncoder) [reply src/test/java/com/fasterxml/jackson/databind/jsontype/TestBaseTypeAsDefault.java:65]: True.

**Comment by cowtowncoder** [comment]
Ok. So, first the good things: I think the idea is correct, mostly: we will allow missing type id if target type itself would NOT be marked polymorphic. So, like if we had:

```
@JsonTypeInfo(...)
class BaseType { }

class ChildType extends BaseType {
}
```

then deserializing as `ChildType` would be allowed.

(we might require that type to be concrete, i.e. not interface or not abstract class too -- or maybe just leave that to fail).

My remaining concern is with the implementation; ideally all introspection would be done during construction of deserializers (and `TypeDeserializer`), and not during actual reading. Doing that would eliminate need for concurrency checks etc, but it is not necessarily trivial to do.

Another possible concern is with respect to "Default Typing" which is enabled without annotations; I don't know how this change would behave there. Possibly it would work fine (or at least no worse).
There is also yet another case where `@JsonTypeInfo` is associated with a property (field, method) and NOT class. I don't know how this would behave for such case either.

One things that would allow solving this would be if there was a way to reliably find what is the Base Type, based on class/interface where relevant `@JsonTypeInfo` comes from. If so, the logic would simply be that Type Id would be optional if (and only if) the target type itself does not have that annotation.
Being able to do that might require change(s) to `AnnotationIntrospector`, and/or code that handles annotation flattening (creates `AnnotatedClass` etc).
I'll have a look at code that introspects information for `@JsonTypeInfo`.

So... right now I am bit uneasy wrt solution and have to think of how to proceed. I think that if the determination for "is this specific class annotated" could be done during construction -- I'd be less hesitant to consider solution.

File: src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsDeductionTypeDeserializer.java [hunk 4]
```diff
@@ -41,9 +41,9 @@ public class AsDeductionTypeDeserializer extends AsPropertyTypeDeserializer
     private final Map<BitSet, String> subtypeFingerprints;
 
     public AsDeductionTypeDeserializer(JavaType bt, TypeIdResolver idRes, JavaType defaultImpl,
-            DeserializationConfig config, Collection<NamedType> subtypes)
+            DeserializationConfig config, Collection<NamedType> subtypes, boolean hasTypeResolverAnnotation)
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsDeductionTypeDeserializer.java:44]: could you add back the old api method and hardcode its hasTypeResolverAnnotation (to false, perhaps)? -- this would prevent a backward compatibility issue.

could you add Javadoc to the new constructor with `@since 2.15`

File: src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsPropertyTypeDeserializer.java [hunk 5]
```diff
@@ -39,23 +46,25 @@ public class AsPropertyTypeDeserializer extends AsArrayTypeDeserializer
...
     /**
      * @since 2.8
      */
     public AsPropertyTypeDeserializer(JavaType bt, TypeIdResolver idRes,
             String typePropertyName, boolean typeIdVisible, JavaType defaultImpl,
-            As inclusion)
+            As inclusion, Boolean hasTypeResolverAttached)
     {
         super(bt, idRes, typePropertyName, typeIdVisible, defaultImpl);
         _inclusion = inclusion;
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsPropertyTypeDeserializer.java:60]: this is wrong - you modifed its param list - you need to keep the old `@since 2.8` and add a new `@since 2.15` one with the new hasTypeResolverAttached param 

does it have to be `Boolean`? This type is very unpopular - it confuses developers who don't recognise that it is not the same as `boolean` -- allows `null`

**Comment by cowtowncoder** [comment]
> > I'll have a look at code that introspects information for @JsonTypeInfo.
> 
> This would be so much cleaner. Would you have time for it, @cowtowncoder ? Let me know if I can help with anything searching or something.

Yeah unfortunately I haven't had much time. But the complexity in `JacksonAnnotationIntrospector` is that instead of gathering information just from `@JsonTypeInfo`, there is logic to combine that and some other annotations to construct `TypeResolverBuilder<?>` (for both serialization, deserialization)

**Comment by cowtowncoder** [comment]
Ohhh. Ok, this looks MUCH simpler! I hope to go over code again tomorrow and see that it makes sense -- I'd be happy if this leads to solution. Even if handling wrt Default Typing had issues (although depends on what kind of problems remain etc).

File: src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsPropertyTypeDeserializer.java [hunk 6]
```diff
@@ -182,7 +202,9 @@ protected Object _deserializeTypedUsingDefaultImpl(JsonParser p,
         // genuine, or faked for "dont fail on bad type id")
         JsonDeserializer<Object> deser = _findDefaultImplDeserializer(ctxt);
         if (deser == null) {
-            JavaType t = _handleMissingTypeId(ctxt, priorFailureMsg);
+            JavaType t = _hasTypeResolver
+                ? _handleMissingTypeId(ctxt, priorFailureMsg) : ctxt.constructType(_baseType.getRawClass());
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsPropertyTypeDeserializer.java:206]: Shouldn't this just be

    ? _handleMissingTypeId(ctxt, priorFailureMsg) : _baseType

so as not to lose generic types possible present in base (or in general just to avoid extra work)?

Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsPropertyTypeDeserializer.java:206]: I can try it out, after merging.

**Review by cowtowncoder — APPROVED** [review]
Ok I think it's very close to what I want so I'll merge it -- and play to see if I can tweak some small aspects (maybe avoid call for introspection)

**Review by cowtowncoder — APPROVED** [review]

File: src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsPropertyTypeDeserializer.java (hunk 6 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsPropertyTypeDeserializer.java]: Ok perfect, thank you!

File: src/test/java/com/fasterxml/jackson/failing/DeserDefaultTypedConcrete2968Test.java [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+            .build();
+        ObjectMapper mapper = jsonMapperBuilder()
+            .activateDefaultTyping(ptv, ObjectMapper.DefaultTyping.NON_FINAL)
+            .build();
+
+        final String concreteTypeJson = a2q("{'size': 42}");
+        BasketBall basketBall = mapper.readValue(concreteTypeJson, BasketBall.class);
+        assertEquals(42, basketBall.size);
+    }
+}
```
[the remark this answers is not in the document]
Comment (cowtowncoder) [reply src/test/java/com/fasterxml/jackson/failing/DeserDefaultTypedConcrete2968Test.java:35]: I think I know what is going on here: by default, inclusion mechanism used here is `As.WRAPPER_ARRAY`.

When I add explicit 3rd parameter like so:

```
        ObjectMapper mapper = jsonMapperBuilder()
            .activateDefaultTyping(ptv, ObjectMapper.DefaultTyping.NON_FINAL,
                    JsonTypeInfo.As.PROPERTY)
            .build();
```

test actually passes. I can make that change.

[the remark this answers is not in the document]
Comment (cowtowncoder) [reply src/test/java/com/fasterxml/jackson/failing/DeserDefaultTypedConcrete2968Test.java:35]: Yeah that's... not the easiest thing to understand. Powerful feature, but bit complicated, dangerous.
Basically it is a way of saying that "for all Classes that fulfill this criteria, pretend like there was `@JsonTypeInfo` attached" (criteria being like "non-final class" or "abstract type"). Useful for enabling polymorphic handling to all kinds of types; like when serializing objects for caches.

File: src/main/java/com/fasterxml/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java [hunk 8]
```diff
@@ -398,4 +403,22 @@ protected boolean allowPrimitiveTypes(MapperConfig<?> config,
...
+     *
+     * @param config the deserialization configuration to use
+     * @param baseType the base type to check for type resolver annotations
+     *
+     * @return true if the class has type resolver annotations, false otherwise
+     *
+     * @since 2.15
+     */
+    protected boolean _hasTypeResolver(DeserializationConfig config, JavaType baseType) {
+        AnnotatedClass ac = AnnotatedClassResolver.resolveWithoutSuperTypes(config,  baseType.getRawClass());
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java:420]: Ahhhh. Only now realized WHY this actually works. Essentially this breaks introspection's inheritance of annotations, so indirectly checks, essentially, that target type has no `@JsonTypeInfo` annotation.

I guess that'll do for now; would be nice to have simpler checking (avoiding full construction of `TypeResolverBuilder` when all we need is existence check), but there are some downsides in adding new methods.

Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java:420]: Yes. And now that I started looking, I think I found a simple(r) fix for 3.0. Which is good... :)
