### PR TITLE
Fix Records deserialization with `@JsonIgnore` on prefixed getters (2.x backport)

### LINKED ISSUE #5184: `@JsonIgnore` on record method applied to record matching field at deserialization
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Since version 2.18.4 (probably since https://github.com/FasterXML/jackson-databind/issues/4628) behavior of annotation on methods of  a records has changed.

before 2.18.4, If I had 

```java
    public record TestData(
            @JsonProperty("test_property")
            String value) {

        @JsonIgnore
        public Optional<String> getValue() {
            return Optional.ofNullable(value);
        }
    }
```

and serialized object 

```json
{ "test_property": "jackson" }
```

it would be deserialized to `TestData("jackson")`

Now since 2.18.4, the `@JsonIgnore` is applied to the value field even though `getValue` is not the record getter. This make `TestData` to be deserialized to `TestData(null)`

It seems that Jackson confuse the `getValue()` for the record getter `value()`. If I name my method something else than `getX` the `@JsonIgnore` is not applied to the field. 

What make me think that its a bug is that an equivalent case with a class doesn't have the same behavior. If I have a class getter with `@JsonIgnore` the object mapper won't apply the ignore to the class field but only the method. 

### Version Information

2.18.4 and 2.19.0

### Reproduction

```java
package com.libon.jackson;

import static org.assertj.core.api.Assertions.assertThat;
import static com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;

class JacksonTest {

    private static final ObjectMapper MAPPER = new ObjectMapper().disable(FAIL_ON_UNKNOWN_PROPERTIES);

    @Test
    void should_deserialize_json_to_test_data() throws Exception {
        String json = """
                      {"test_property":"test value"}
                      """;

        var testData = MAPPER.readValue(json, JacksonTest.TestData.class);

        assertThat(testData.value()).isEqualTo("test value");
    }

    @Test
    void should_deserialize_json_to_test_data_class() throws Exception {
        String json = """
                      {"test_property":"test value"}
                      """;

        var testData = MAPPER.readValue(json, JacksonTest.TestDataClass.class);

        assertThat(testData.getValue()).contains("test value");
    }

    @Test
    void should_deserialize_json_to_test_data_alternate() throws Exception {
        String json = """
                      {"test_property":"test value"}
                      """;

        var testData = MAPPER.readValue(json, JacksonTest.TestDataAlternate.class);

        assertThat(testData.value()).isEqualTo("test value");
    }

    @Test
    void should_not_deserialize_wrong_json_model_to_test_data() throws Exception {
        String json = """
                      {"value":"test value"}
                      """;

        JacksonTest.TestData testData = MAPPER.readValue(json, JacksonTest.TestData.class);

        assertThat(testData.value()).isNull();
    }

    public record TestData(
            @JsonProperty("test_property")
            String value) {

        @JsonIgnore
        public Optional<String> getValue() {
            return Optional.ofNullable(value);
        }
    }

    public record TestDataAlternate(
            @JsonProperty("test_property")
            String value) {

        @JsonIgnore
        public Optional<String> optionalValue() {
            return Optional.ofNullable(value);
        }
    }

    public static final class TestDataClass {
        private final String value;

        public TestDataClass(
                @JsonProperty("test_property")
                String value) {
            this.value = value;
        }

        @JsonIgnore
        public Optional<String> getValue() {
            return Optional.ofNullable(value);
        }

    }
}

``` 

### Expected behavior

The `@JsonIgnore` on a record method should not be applied to the record field especially when its not the field getter. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JooHyukKim**
Fixes #5184

### CODE REVIEW

**Comment by pjfanning** [comment]
The CI failure is actually probably good news.

```
Error:  Errors: 
Error:    PrimarySuite.should_deserialize_json_to_test_data » JacksonTestShouldFail Test method class com.fasterxml.jackson.databind.tofix.RecordWithJsonIgnoredMethod5184Test.should_deserialize_json_to_test_data() passed, but should have failed
Error:    PrimarySuite.should_not_deserialize_wrong_json_model_to_test_data » UnrecognizedProperty Unrecognized field "value" (class com.fasterxml.jackson.databind.tofix.RecordWithJsonIgnoredMethod5184Test$TestData5184), not marked as ignorable (one known property: "test_property")
```

So the 1st test can be enabled. I'm not sure about the 2nd failing test.

**Comment by JooHyukKim** [comment]
image

This now-failing test should most likely pass.
The case seems almost identical to the test case we are adding.
Will check again.

**Comment by JooHyukKim** [comment]
```
Error:    PrimarySuite.should_not_deserialize_wrong_json_model_to_test_data » UnrecognizedProperty Unrecognized field "value" (class com.fasterxml.jackson.databind.tofix.RecordWithJsonIgnoredMethod5184Test$TestData5184), not marked as ignorable (one known property: "test_property")
```

This is simply configuration error, Jackson 2 deserialization fails on unknown JSON field by default.
I belive https://github.com/FasterXML/jackson-databind/pull/5628/changes/7b22e5691165f9fefdecb2bfa6c23cf6d4b0f7c4 is proper fix needed. 
But let's see!

File: src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordWithJsonIgnoredMethod5184Test.java [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 import java.util.Optional;
 
+import com.fasterxml.jackson.databind.DeserializationFeature;
```
Comment (pjfanning) [inline src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordWithJsonIgnoredMethod5184Test.java:5]: Are all the tests passing for this class? If so, could we get rid of the `tofix` in the package name, maybe move to the `deser` package.

File: src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordJsonIgnoreRoundTrip5184Test.java [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+     */
+    @Test
+    public void testSerializationUsesFieldNotGetter() throws Exception {
+        final Foo obj = new Foo("field-value");
+        final String json = MAPPER.writeValueAsString(obj);
+
+        // Should serialize the field value "field-value", not what getBar() returns (123)
+        assertThat(json).isEqualTo("{\"bar\":\"field-value\"}");
+    }
+}
```
Comment (pjfanning) [inline src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordJsonIgnoreRoundTrip5184Test.java]: can you add a new line at the end of the file?

File: src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordWithJsonIgnoredMethod5184Test.java (hunk 1 above)
Comment (JooHyukKim) [reply src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordWithJsonIgnoredMethod5184Test.java:5]: Good idea, might as well 👍

**Comment by cowtowncoder** [comment]
I am not sure this is safe to backport in 2.x which is why it was originally fixed just for 3.1.

I am open to being convinced otherwise but will need to think about it for a bit.

File: src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java [hunk 3]
```diff
@@ -1250,6 +1250,19 @@ else if (Boolean.TRUE.equals(ai.hasAsValue(m))) {
         // 27-Dec-2019, tatu: [databind#2527] may need to rename according to field
         implName = _checkRenameByField(implName);
         boolean ignore = ai.hasIgnoreMarker(m);
+        // 31-Jan-2026, @Copilot: [databind#5184]: Not the cleanest fix but here goes...
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java]: Please remove/change `@Copilot` reference; all code changes to reference human involved, not aI agent only (ok to mention as helper if that makes sense)

**Comment by cowtowncoder** [comment]
I am leaning towards merging this in for 2(.22.0). Will merge tomorrow if I still feel that way :)

**Comment by cowtowncoder** [comment]
@JooHyukKim I can merge this but will probably even backport further in 2.21 since that is LTS version.

**Review by cowtowncoder — APPROVED** [review]
