### PR TITLE
Fix #5401 Single-arg method invocations should not fall back to input…

### LINKED ISSUE #5401: Regression with `@JsonCreator` that returns `null` for empty strings
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

While updating to Jackson 3.0, our test suite revealed a regression introduced in #5090
where deserializing from a property with an empty string value using a `@JsonCreator` method that transforms this value to `null` causes the empty string to be assigned into the field as-is, raising `ClassCastException`.

### Version Information

3.0.1

### Reproduction

```java
    static class NonEmpty {
      public NonEmptyString nonEmpty;
    }

    static class NonEmptyString {
        public final String value;

        @JsonCreator
        public static NonEmptyString of(String value) {
            if (value == null || value.isEmpty()) {
                return null;
            }
            return new NonEmptyString(value);
        }

        private NonEmptyString(String value) {
            this.value = value;
        }
    }

    @Test
    void testDeserializeFieldToNullIfCreatorReturnsNull()
            throws Exception
    {
        NonEmpty result = MAPPER.readValue(
                "{ \"nonEmpty\": \"\" }",
                NonEmpty.class);

        assertNotNull(result);
        assertNull(result.nonEmpty);
    }
``` 

```
[ERROR] Errors: 
[ERROR]   JsonCreatorReturningNull4938Test.testDeserializeToNullWhenAllPropertyIsNull:119 ╗ Databind Cannot cast java.lang.String to tools.jackson.databind.deser.creators.JsonCreatorReturningNull4938Test$Localized1
 at [Source: (String)"{ "locale": "" }"; line: 1, column: 15] (through reference chain: tools.jackson.databind.deser.creators.JsonCreatorReturningNull4938Test$Localized["locale"])
```

### Expected behavior

A passing test, where `NonEmpty.nonEmpty` is `null`.

### Additional context

I will be opening a PR with fix shortly

### PR DESCRIPTION
**Pull request by JoostK**
… argument for `null` return values

Fixes #5401

### CODE REVIEW

File: src/test/java/tools/jackson/databind/deser/creators/JsonCreatorReturningNull4938Test.java [hunk 1]
```diff
@@ -92,6 +112,18 @@ public void addProperty(String key, Object value) {
 
     private final ObjectMapper MAPPER = newJsonMapper();
 
+    @Test
```
Comment (cowtowncoder) [inline src/test/java/tools/jackson/databind/deser/creators/JsonCreatorReturningNull4938Test.java]: Add comment like

    // For [databind#5401]

and add `5401` in method name as well

**Comment by cowtowncoder** [comment]
Makes sense, but I am puzzled by original code -- why is it returning argument instead of null... :-/

@stevenschlansker Any idea on ^^^?

**Comment by stevenschlansker** [comment]
Sorry, I'm not sure. Seems good to remove to me.

**Comment by cowtowncoder** [comment]
@stevenschlansker All good -- did not mean as in "WTH" but more like "is this safe to remove" :)
So sanity check so we won't remove something important.

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
So, looks good, thank you @JoostK !

Just one thing before I merge (and back-port in 3.0(.3)) -- unless we have one already, need CLA from here:

https://github.com/FasterXML/jackson/blob/main/contributor-agreement.pdf

Only needs to be sent once, good for all future contributions.
The usual way is to print, fill & sign, scan/photo, email to `cla` at fasterxml dot com.

Once we have it, I can merge this in. Thanks again!

**Comment by JoostK** [comment]
> Only needs to be sent once, good for all future contributions. The usual way is to print, fill & sign, scan/photo, email to `cla` at fasterxml dot com.

Done

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Merged in, backported in `3.0` for 3.0.3 release
