### PR TITLE
Fix #5231 with MethodHandle with varargs in deserialization

### LINKED ISSUE #5231: Jackson 3 (rc6) deserialization of `Locale` (array) fails
### Discussed in https://github.com/FasterXML/jackson-databind/discussions/5230

<div type='discussions-op-text'>

<sup>Originally posted by **tsegall** July 22, 2025</sup>
I get the following exception in Jackson 3  (rc6)(the same program works in Jackson 2)

Exception in thread "main" tools.jackson.databind.DatabindException: Cannot cast [Ljava.util.Locale; to java.util.Locale
 at [Source: (String)"{"locale":"en-US","locales":["en-US"]}"; line: 1, column: 38] (through reference chain: j3bug.DateTimeParserConfig["locales"])
	at tools.jackson.databind.DatabindException.wrapWithPath(DatabindException.java:111)
	at tools.jackson.databind.deser.bean.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1850)
	at tools.jackson.databind.deser.bean.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:534)
	at tools.jackson.databind.deser.bean.BeanDeserializer.deserialize(BeanDeserializer.java:200)
	at tools.jackson.databind.deser.DeserializationContextExt.readRootValue(DeserializationContextExt.java:265)
	at tools.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2688)
	at tools.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1600)
	at j3bug.J3bug.main(J3bug.java:15)
Caused by: java.lang.ClassCastException: Cannot cast [Ljava.util.Locale; to java.util.Locale
	at java.base/java.lang.Class.cast(Class.java:3889)
	at tools.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:132)
	at tools.jackson.databind.deser.bean.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:532)
	... 5 more

Class I am attempting to serialize is here:

```
package j3bug;

import java.util.Locale;

public class DateTimeParserConfig {
        public Locale[] locales;
        private Locale locale;

        public Locale[] getLocales() {
                return locales;
        }

        public void setLocales(final Locale... locales) {
                this.locales = locales;
                if (locales != null && locales.length == 1)
                        this.locale = this.locales[0];
        }

        protected void setLocale(final Locale locale) {
                this.locale = locale;
        }

        public Locale getLocale() {
                if (locale != null)
                        return locale;

                locales = new Locale[] { Locale.getDefault() };

                return locales.length == 1 ? locales[0] : null;
        }
}
```

Driver is here:

```
package j3bug;

import java.util.Locale;

import tools.jackson.core.StreamReadFeature;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;

public abstract class J3bug {
                
        public static void main(String[] args) {
                ObjectMapper mapper = JsonMapper.builder().enable(StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION).build();
                DateTimeParserConfig cfg = new DateTimeParserConfig();
                String serialized = mapper.writeValueAsString(cfg);
                mapper.readValue(serialized, DateTimeParserConfig.class);
        }               
}
```

Any clues appreciated.

</div>

### PR DESCRIPTION
**Pull request by JooHyukKim**
Fixes #5231 

### Conclusion

Problem is with **argument-spreading** (I think)

### Description

There seems to be issue with `MethodProperty` in the deserialization where setters with varargs (e.g. `setLocales(Locale... locales)`).

I am assuming the problem is caused by the setter method being varargs, the underlying `MethodHandle` created via `MethodHandles.unreflect()` retains the varargs behavior by default, which enables argument spreading. 

```
Cannot cast [Ljava.util.Locale; to java.util.Locale
```

The fix uses `.asFixedArity()` on the unreflected `MethodHandle` when the underlying method is varargs. This disables argument spreading, ensuring that the method handle treats the argument as a single array, matching Jackson’s calling convention.

### Refs

- [`MethodHandle.asFixedArity()` JavaDoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/invoke/MethodHandle.html#asFixedArity())

### CODE REVIEW

**Comment by JooHyukKim** [comment]
@stevenschlansker WDYT?
Review much appreciated.
I don't usally go this deep into JVM, so I am quite concerned lol.

**Comment by cowtowncoder** [comment]
This is kind of my concern wrt `MethodHandle` change: right now knowledge is bit limited by the team.
Fix seems reasonable but I cannot really review it either.

Maybe @yawkat could double-check besides our resident master (@stevenschlansker )

File: src/main/java/tools/jackson/databind/deser/impl/MethodProperty.java [hunk 1]
```diff
@@ -209,7 +210,14 @@ class SetterHolder extends UnreflectHandleSupplier {
         protected MethodHandle unreflect() throws IllegalAccessException {
             if (_annotated instanceof AnnotatedMethod) {
                 AnnotatedMethod am = (AnnotatedMethod) _annotated;
-                return MethodHandles.lookup().unreflect(am.getAnnotated());
+                Method method = am.getAnnotated();
+                MethodHandle raw = MethodHandles.lookup().unreflect(method);
+
+                // [databind#5231] If it's varargs, disable varargs handling, 2025-July-25 (Since 3.0)
+                if (method.isVarArgs()) {
```
Comment (stevenschlansker) [inline src/main/java/tools/jackson/databind/deser/impl/MethodProperty.java]: I think the `asFixedArity` method already does this check for you -

> If the current method handle is not of variable arity, the current method handle is returned.

so maybe this could just be 
```
return MethodHandles.lookup()
    .unreflect(am.getAnnotated())
    .asFixedArity();
```

File: src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+
+        protected void setLocale(final Locale locale) {
+            this.locale = locale;
+        }
+
+        public Locale getLocale() {
+            if (locale != null)
+                return locale;
+
+            locales = new Locale[]{Locale.getDefault()};
```
Comment (stevenschlansker) [inline src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java]: this could surprisingly reset `locales` array and lose previously set value, but maybe that's intentional / doesn't matter?

File: src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+
+    private void _testMultiple(ObjectMapper mapper) {
+        DateTimeParserConfig cfg = new DateTimeParserConfig();
+        cfg.setLocales(new Locale[]{Locale.US, Locale.UK, Locale.ENGLISH});
+        String json = mapper.writeValueAsString(cfg);
+
+        DateTimeParserConfig result = mapper.readValue(json, DateTimeParserConfig.class);
+
+        assertNotNull(result);
+        assertNotNull(result.locales); // Should fallback to Locale.getDefault()
```
Comment (stevenschlansker) [inline src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java]: it would be better to assert the actual values, rather than just checking for null or not.

**Review by stevenschlansker — COMMENTED** [review]
Thank you for fixing this issue. I have a couple comments on the MR before we merge.

File: src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java (hunk 2 above)
Comment (JooHyukKim) [reply src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java]: Ah yes, just for reproduction purposes. But let's clean up

**Comment by JooHyukKim** [comment]
Applied reviews and requested changes again.

File: src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+        String json = MAPPER.writeValueAsString(cfg);
+
+        DateTimeParserConfig result = MAPPER.readValue(json, DateTimeParserConfig.class);
+
+        assertNotNull(result);
+        assertThat(toList(result.locales))
+                .containsExactlyInAnyOrder(Locale.JAPANESE);
+    }
+
+    private List<Locale> toList(Locale[] locales) {
```
Comment (stevenschlansker) [inline src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java:73]: I think this could just be `Arrays.asList`

**Review by stevenschlansker — APPROVED** [review]
Thank you for finding and fixing this bug!

**Comment by stevenschlansker** [comment]
@cowtowncoder , I think this is a relatively low risk fix for the next rc or final release, especially once all the other jackson project tests pass.

File: src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java (hunk 4 above)
Comment (stevenschlansker) [reply src/test/java/tools/jackson/databind/deser/jdk/JDKLocaleWithVargarg5231Test.java:73]: or omitted entirely, as `assertj` seems to support asserting on arrays directly.

**Comment by cowtowncoder** [comment]
> @cowtowncoder , I think this is a relatively low risk fix for the next rc or final release, especially once all the other jackson project tests pass.

Sounds good then.

@JooHyukKim could you add release notes entry and we can merge it -- there will still be at least 3.0.0-rc7 before 3.0.0 final.

**Comment by JooHyukKim** [comment]
@cowtowncoder Added. Seems good to go now?

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
> @cowtowncoder Added. Seems good to go now?

Yes!
