### PR TITLE
Experimenting with #1467: Support for @JsonUnwrapped in @JsonCreators

### LINKED ISSUE #1467: Support `@JsonUnwrapped` with `@JsonCreator`
(note: follow-up for #265)

Current implementation of `@JsonUnwrapped` deserialization requires handling of all other properties first, and only then reconstructing unwrapped objects. This works ok via fields/setters, but can not work with `@JsonCreator` passed values.

But with a major rewrite it should be possible to make this work. This probably requires more support for actually determining unwrapped-properties a priori, instead of just buffering anything that doesn't match. Or maybe it only requires more logic in handling of creator.

### PR DESCRIPTION
**Pull request by fxshlein**
(fixes #1467 -- one of oldest highly-voted-for open issues)

I was more or less just messing around with an approach to solve this for now without the big refactor mentioned in the issue. Perhaps this is already fine? The test I added is green at least, but I have no idea what I might have missed. After all, if an "object with three properties" test covered a considerable amount of jackson's feature set, I wouldn't be using it... 😆

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java [hunk 1]
```diff
@@ -1,62 +1,112 @@
...
             }
             newProps.add(prop);
         }
-        return new UnwrappedPropertyHandler(newProps);
+        return newProps;
+    }
+
+    public boolean isUnwrapped(SettableBeanProperty property) {
+        return this._unwrappedPropertyNames.contains(property.getName());
+    }
```
Comment (fxshlein) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java:88]: Would this be sufficient to check for the unwrapped properties? Not sure how different things affect the result of `getName()`

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java [hunk 2]
```diff
@@ -1,62 +1,112 @@
...
-import com.fasterxml.jackson.core.*;
+import com.fasterxml.jackson.core.JsonParser;
 import com.fasterxml.jackson.databind.DeserializationContext;
 import com.fasterxml.jackson.databind.JsonDeserializer;
+import com.fasterxml.jackson.databind.PropertyName;
 import com.fasterxml.jackson.databind.deser.SettableBeanProperty;
 import com.fasterxml.jackson.databind.util.NameTransformer;
 import com.fasterxml.jackson.databind.util.TokenBuffer;
 
+import java.io.IOException;
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java:11]: Could you move these back to where they were? (I assume IDE just reordered them automatically).

(we finally have Coding Style Guide -> https://github.com/FasterXML/jackson/blob/master/contribution/jackson-coding-style-guide.md

that explains intended ordering)

File: src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java [hunk 3]
```diff
@@ -716,6 +717,14 @@ private void _addCreatorParam(Map<String, POJOPropertyBuilder> props,
         PropertyName pn = _annotationIntrospector.findNameForDeserialization(param);
         boolean expl = (pn != null && !pn.isEmpty());
         if (!expl) {
+            boolean unrwapping = _annotationIntrospector.findUnwrappingNameTransformer(param) != null;
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java:720]: typo in name :)

File: src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedCreatorParam265Test.java [hunk 4]
```diff
@@ -1,101 +0,0 @@
-package com.fasterxml.jackson.databind.struct;
```
Comment (cowtowncoder) [inline src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedCreatorParam265Test.java:1]: Why was this test deleted? Was it just renamed or ... ?

File: src/test/java/com/fasterxml/jackson/databind/struct/TestUnwrappedWithJsonCreator.java [hunk 5]
```diff
@@ -0,0 +1,128 @@
+package com.fasterxml.jackson.databind.struct;
+
+import com.fasterxml.jackson.annotation.*;
+import com.fasterxml.jackson.databind.*;
+
+/**
+ * Tests to verify [databind#1467].
+ */
+public class TestUnwrappedWithJsonCreator extends BaseMapTest
```
Comment (cowtowncoder) [inline src/test/java/com/fasterxml/jackson/databind/struct/TestUnwrappedWithJsonCreator.java:9]: Newer naming convention leads to `UnwrappedWith[Json]CreatorTest` (we haven't renamed all or even most tests but trying to move in that direction).

**Comment by cowtowncoder** [comment]
Whoa! Impressive work. I share your suspicion wrt test coverage (lack thereof), but it is what it is.

I'd need to read this through with more thought and focus to see if there's anything specifically that wouldn't work (or be against design). In the meantime I added some notes on code style issues (which are obviously not super important but might as well mention now).

Also, assuming we get through this to merge it, one thing needed (if not already done) is CLA:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

which we need before merging the first contribution. It's usually easiest to print, fill & sign, scan/photo, email to `cla` at fasterxml dot com. Only needed once, good for all future contributions.

File: src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedCreatorParam265Test.java (hunk 4 above)
Comment (fxshlein) [reply src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedCreatorParam265Test.java:1]: This was the test that verified that error messages were printed when using `@JsonUnwrapped` in a creator, which hopefully shouldn't be needed anymore :)

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java:88]: In theory names should be `PropertyName` instances (matters with XML, mostly), but internally a few things are still just `String`s so I suspect this is fine.

File: src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordWithJsonUnwrappedTest.java [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+    /*
+    /**********************************************************************
+    /* Tests, JsonUnwrapped deserialization
+    /**********************************************************************
+     */
+
+    public void testUnwrappedWithRecord() throws Exception
+    {
+        String json = "{\"unrelated\": \"unrelatedValue\", \"property1\": \"value1\", \"property2\": \"value2\"}";
+        RecordWithJsonUnwrapped outer = MAPPER.readValue(json, RecordWithJsonUnwrapped.class);
```
Comment (cowtowncoder) [inline src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordWithJsonUnwrappedTest.java:26]: Works, but might make sense to first serialize from instance, then read back (round-trip). To make both directions work (I realize that this PR is just for deserialization but still)

Comment (fxshlein) [reply src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordWithJsonUnwrappedTest.java]: Changed it to a round-trip. Should I also change the tests in `UnwrappedWithCreatorTest`? Since there are already similar tests for serializing regular classes.

**Comment by fxshlein** [comment]
@cowtowncoder I sent the signed CLA to `cla@...`. 🙂 

Just to verify, [here](https://github.com/FasterXML/jackson/blob/master/CONTRIBUTING.md#paperwork) it says to email the CLA to `info@...`, are both fine?

File: src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedCreatorParam265Test.java (hunk 4 above)
Comment (cowtowncoder) [reply src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedCreatorParam265Test.java:1]: Ah. Yes, that makes sense. :)

File: src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java [hunk 7]
```diff
@@ -855,7 +855,7 @@ protected Object deserializeUsingPropertyBasedWithUnwrapped(JsonParser p, Deseri
             if (buffer.readIdProperty(propName) && creatorProp == null) {
                 continue;
             }
-            if (creatorProp != null) {
+            if (creatorProp != null && !_unwrappedPropertyHandler.isUnwrapped(creatorProp)) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java:858]: I'll have to think about this; ideally such lookup shouldn't be needed (rather, creatorProp would have knowledge of whether it's created via unwrapping).

Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java:858]: Oddly enough, removing this call makes no difference; all tests pass the same (including Record test).

So is it actually needed? Either we should have a test that fails without it, or it should just be removed, I think.

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java:86]: As per my comment higher up, I am not sure this method is actually needed: at least tests included seem to pass just fine without it being called (as well as all other existing tests).

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java [hunk 8]
```diff
@@ -15,49 +18,93 @@
...
+public class UnwrappedPropertyHandler {
+    /**
+     * We need a placeholder for creator properties that don't have name
+     * but are marked with `@JsonWrapped` annotation.
+     */
+    public final static PropertyName UNWRAPPED_CREATOR_PARAM_NAME = new PropertyName("@JsonUnwrapped");
+
+    protected final List<SettableBeanProperty> _creatorProperties;
     protected final List<SettableBeanProperty> _properties;
+    protected final Set<String> _unwrappedPropertyNames;
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java:30]: ... and if `isUnwrapped()` is not actually needed, can drop this `Set` and code that maintains it.

File: src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedWithCreatorTest.java [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+import com.fasterxml.jackson.annotation.*;
+import com.fasterxml.jackson.databind.*;
+
+/**
+ * Tests to verify [databind#1467].
+ */
+public class UnwrappedWithCreatorTest extends BaseMapTest
+{
+	static class ExplicitWithoutName {
+		private final String _unrelated;
```
Comment (cowtowncoder) [inline src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedWithCreatorTest.java:12]: @fxshlein I changed internal field names to make 100% sure test could not accidentally work due to field name matching constructor property name (since that would actually work despite `final` field declaration, in absence of Creator parameters).

File: src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java (hunk 7 above)
Comment (fxshlein) [reply src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java:858]: Yeah, it seems like this makes no sense anymore, I probably implemented it before adapting the rest of the code. The issue this _would_ have solved is if you have a structure like this:
```java
record Outer(@JsonUnwrapped Inner propertyName) {}

record Inner(String propertyName, String otherPropertyName) {}
```
There is a property called `propertyName` inside and outside the unwrapped structure, so when deserializing and encountering the property called "propertyName", I initially thought it would find that property. But as far as this code is concerned, the outer property is called `"@JsonUnwrapped"`, so it should not clash either way. Because of this fake name, the `_unwrappedPropertyNames` set used for `isUnwrapped` actually only contains `"@JsonUnwrapped"`... 😄

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java (hunk 8 above)
Comment (fxshlein) [reply src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java]: Removed the set and the check!

File: src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedPropertyBasedCreatorWithPrefixTest.java [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+        private final String _property;
+
+        public Inner(@JsonProperty("property") String property) {
+            _property = property;
+        }
+
+        public String getProperty() {
+            return _property;
+        }
+    }
```
Comment (fxshlein) [inline src/test/java/com/fasterxml/jackson/databind/struct/UnwrappedPropertyBasedCreatorWithPrefixTest.java:25]: @cowtowncoder While looking at something else, I noticed that you could not do this because the `NameTransformer` used for unwrapping is not applied to `_propertyBasedCreator`, only to `_beanProperties`. This commit seems to fix that: https://github.com/FasterXML/jackson-databind/pull/4271/commits/d65dfacf8d9ec371910db8f230b775e11828b7c1. I guess it broadly fits the scope of the PR, but I can also remove it and make a separate one. In theory its more or less unrelated.

**Comment by fxshlein** [comment]
I noticed a minor issue with the placeholder name: If you use two `@JsonUnwrapped` parameters in a creator without explicitly giving it a name `@JsonProperty`, they will be marked as duplicates, as they both get the placeholder:
```
Caused by: java.lang.IllegalArgumentException: Duplicate creator property "@JsonUnwrapped" (index 2 vs 3) for type ...
```

I added a test case here:
https://github.com/FasterXML/jackson-databind/pull/4271/files#diff-1b40e79714a359efac38026f7dfe9dbf45f4def1877d805437ba48955ae9478eR68-R96

From what I can see, there are three solutions to this:
1. Just let it happen, maybe add a special exception message that tells users to simply distinguish the properties using `@JsonProperty`. On one hand this should fit right in, as the user probably has to have `@JsonProperty` on all parameters anyways, but on the other hand it would be kind of weird since the name is never actually used.
2. Change the placeholder to include the index ("unnamed @JsonUnwrapped property at N"). This is the one I implemented now, which makes the test case work. This is nice since the name is more unique, and the names also double as human-readable identifiers in error messages.
3. Do a refactor to allow unwrapped properties to bypass all the places where properties are placed in a map, using their name as a key. I started this here: https://github.com/fxshlein/jackson-databind/commit/3bd10a06548260445cfcde0643f885de5537a09d, but it's already a pretty massive undertaking without even touching everything.

File: src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java (hunk 7 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java]: Right, I thought it might just contain `@JsonUnwrapped` :)

**Comment by cowtowncoder** [comment]
To me (2), adding index for bogus name, sounds reasonable at this point. +1.

**Comment by wingsofovnia** [comment]
While looking for a stop-gap solution for this in GitHub, I found [this](https://github.com/eclipse-tractusx/bpdm/blob/15b6fbdcdce513374cf7718e704ec33976157382/bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/service/DataClassUnwrappedJsonDeserializer.kt#L39) ([usage](https://github.com/eclipse-tractusx/bpdm/blob/15b6fbdcdce513374cf7718e704ec33976157382/bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/SiteGateOutputResponse.kt#L30)) rather straightforward solution for `@JsonUnwrapped` support in Kotlin data classes. Perhaps this might be helpful for you or others who seek a temp solution.

Looking forward to having this merged. Thank you for the contribution!

**Comment by eranl** [comment]
@cowtowncoder, what's the status of this PR?

**Comment by JooHyukKim** [comment]
@eranl The submitter stop working 6months ago. Unless target issue is highly voted, it would be reasonable to say that there is small chance of merging unless @fxshlein or someone else picks it back up

**Comment by cowtowncoder** [comment]
Quick note: this would need to be re-based on 2.18 which may be tricky due to major POJO property introspection rewrite (or might be easy).
If so, could be considered; definitely the problem to solve is worth tackling.

**Comment by cowtowncoder** [comment]
Re-based, but now there are conflicts to resolve... not sure I have time to tackle those right now.

**Comment by cowtowncoder** [comment]
Ok. Had a look and... yeah, no. These merge conflicts are actually beyond my repairing.
I think I broke this pr, unfortunately; it would need to be re-created starting from 2.18 branch.
The problem is that lots of code was removed from `src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java` and replaced with additions in `src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java`.

Unfortunately those 2 classes were heavily modified by this PR.

But if anyone has time and interest to reconstruct this PR based off 2.18, we could consider it (or, in near future when 2.18 released, against 2.19).

**Comment by fxshlein** [comment]
> @eranl The submitter stop working 6months ago. Unless target issue is highly voted, it would be reasonable to say that there is small chance of merging unless @fxshlein or someone else picks it back up

I'm sick at the moment, but maybe I can give it a shot later this week. I was just waiting for the PR to be merged tho, as far as I was concerned nothing was left to do, right? As far as the last comment, I had already implemented the second solution, I was just presenting alternatives. Maybe that caused a misunderstanding, sorry!

**Comment by fxshlein** [comment]
Hi @cowtowncoder! Sorry for the long wait, completely forgot about this PR if I'm honest.

I reimplemented everything on top of `1.18`. I can't rename the branch in the PR, so it's still called `1.17`, but it's the latest branch. I'll also deploy the new updated branch from my fork to our internal maven repo and run our tests using that. Those use lots of `@JsonUnwrapped` annotations in previously unsupported places.

**Comment by fxshlein** [comment]
Quick update, I tested the updated branch with our internal code (which was based on the old branch) now, and it still works perfectly. I think this should be ready to merge now 🙂

File: src/main/java/com/fasterxml/jackson/databind/deser/SettableBeanProperty.java [hunk 11]
```diff
@@ -584,6 +585,25 @@ public final Object deserializeWith(JsonParser p, DeserializationContext ctxt,
         return value;
     }
 
+    /**
+     * Returns a copy of this property, unwrapped using the given {@link NameTransformer}.
+     */
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/deser/SettableBeanProperty.java:590]: Can you add `@since 2.18.0`? likewise with any other new public methods.

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/BeanPropertyMap.java [hunk 12]
```diff
@@ -713,25 +713,6 @@ public String toString()
     /**********************************************************
      */
 
-    protected SettableBeanProperty _rename(SettableBeanProperty prop, NameTransformer xf)
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/BeanPropertyMap.java:716]: this breaks backward compatbility - add back the old method and deprecate it

Comment (pjfanning) [reply src/main/java/com/fasterxml/jackson/databind/deser/impl/BeanPropertyMap.java:716]: the method can call the new unwrap method, but we need to keep the existing method (its implementation can change - as long as it the change retains the existing behaviour)

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java [hunk 13]
```diff
@@ -17,51 +18,83 @@
...
     protected final List<SettableBeanProperty> _properties;
 
     public UnwrappedPropertyHandler()  {
-        _properties = new ArrayList<SettableBeanProperty>();
+        _creatorProperties = new ArrayList<>();
+        _properties = new ArrayList<>();
     }
 
-    protected UnwrappedPropertyHandler(List<SettableBeanProperty> props)  {
+    protected UnwrappedPropertyHandler(List<SettableBeanProperty> creatorProps, List<SettableBeanProperty> props) {
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java:29]: you need to keep the existing method and deprecate it

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java [hunk 14]
```diff
@@ -17,51 +18,83 @@
...
+        _creatorProperties = creatorProps;
         _properties = props;
     }
 
+    public void addCreatorProperty(SettableBeanProperty property) {
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java:34]: needs to have javadoc including its `@since 2.18`

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java [hunk 15]
```diff
@@ -17,51 +18,83 @@
...
+                continue;
             }
-            newProps.add(prop);
+
+            newProps.add(prop.unwrapped(transformer));
+        }
+        return newProps;
+    }
+
+    public PropertyValueBuffer processUnwrappedCreatorProperties(
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java:65]: javadoc with `@since 2.18`

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java [hunk 16]
```diff
@@ -17,51 +18,83 @@
...
             p.nextToken();
             prop.deserializeAndSet(p, ctxt, bean);
         }
         return bean;
     }
+
+    /**
+     * We need a placeholder for creator properties that don't have a name,
+     * but are marked with `@JsonWrapped` annotation.
+     */
```
Comment (pjfanning) [inline src/main/java/com/fasterxml/jackson/databind/deser/impl/UnwrappedPropertyHandler.java:96]: `@since 2.18`

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/BeanPropertyMap.java (hunk 12 above)
Comment (fxshlein) [reply src/main/java/com/fasterxml/jackson/databind/deser/impl/BeanPropertyMap.java:716]: good point, readded it!

**Comment by cowtowncoder** [comment]
Quick note: due to timing, this won't make it in 2.18, too risky.

**Comment by fxshlein** [comment]
haha, I already figured when I saw the 2.18 RC a few days ago. Changed it to 2.19!

**Comment by fxshlein** [comment]
@cowtowncoder I changed the base branch to 1.19, seems to work without conflicts. I guess this could be merged now that the 1.19 branch exists, right?

**Comment by wingsofovnia** [comment]
Is there any update on this or reason why this isn't getting merged? Looks all green and all feedback addressed.

**Comment by JooHyukKim** [comment]
> Is there any update on this or reason why this isn't getting merged? Looks all green and all feedback addressed.

We need proper planning wrt timing on when features get merged.
And this is not the only feature waiting to get merged.
Read some more and you will see Tatu saying...

    Quick note: due to timing, this won't make it in 2.18, too risky.

Not to mention `@since 2.18` is already outdated.

**Comment by fxshlein** [comment]
> > Is there any update on this or reason why this isn't getting merged? Looks all green and all feedback addressed.
> 
> We need proper planning wrt timing on when features get merged. And this is not the only feature waiting to get merged. Read some more and you will see Tatu saying...
> 
> ```
> Quick note: due to timing, this won't make it in 2.18, too risky.
> ```
> 
> Not to mention `@since 2.18` is already outdated.

Note that the target branch for this PR is the development branch for `2.19`, and I changed everything to `@since 2.19` a while ago already, so I think the comment regarding `2.18` timing should be addressed. The timing issue was that, when I updated the PR to target `2.18`, the release candidate for `2.18` was already out, at which point it makes no sense to add additional features. I think for `2.19` it should be fine to merge this right?

**Comment by cowtowncoder** [comment]
Went over this once, made tiny stylistic changes but want to go over the thing once more and then get merged. My spider sense is tingling wrt this being possibly risky, still, but at the same time all tests, added ones and old, pass -- and this would solve one of only 8 "most-wanted" issues, so clearly many users would like to see it come available.
So will get this merged, just want to be as sure as I can.

File: src/main/java/com/fasterxml/jackson/databind/deser/impl/BeanPropertyMap.java (hunk 12 above)
Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/deser/impl/BeanPropertyMap.java:715]: Looking at this again, while I usually agree, in this case it is an internal method called from nowhere else (and `BeanPropertyMap` not extensible via sub-calling). But it's ok to leave it for now, being just 1-liner.

**Review by cowtowncoder — APPROVED** [review]
LGTM. Bit worried about possible name clashes, `POJOPropertiesCollector`, but can deal with problems if they arise.

**Comment by JooHyukKim** [comment]
Great job @fxshlein !

**Comment by cowtowncoder** [comment]
Agreed. Now if I can get this cleanly merged into 3.0 that's the real test... except for one aspect, got it done. So am hopeful still.
