### PR TITLE
Fix #5398: ignore + rename

### LINKED ISSUE #5398: `@JsonProperty.value` + `@JsonIgnore` on setter does not work anymore since 2.18.4
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Hi,

The following fails since 2.18.4 (I tested also 2.20.1):
```java
    class Test {
        private String prop = "someValue";

        @JsonProperty(value = "renamedProp")
        public String getProp() {
            return prop;
        }

        @JsonIgnore
        public void setProp(String prop) {
            this.prop = prop;
        }

        public static void main(String[] args) throws Exception {
            var m = new ObjectMapper();
            m.readValue(m.writeValueAsString(new Test()), Test.class);
        }
    }
```

This fails with:
> Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "renamedProp" (class example.Test), not marked as ignorable (one known property: "prop"])

I know that the best practice is to instead set the property as readonly but it's still a regression I guess?

### Version Information

2.20.1

### Reproduction

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cowtowncoder**
Fixes #5398

### CODE REVIEW

File: src/test/java/com/fasterxml/jackson/databind/introspect/JsonPropertyRename5398Test.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+        String json = MAPPER.writeValueAsString(original);
+
+        // Should serialize with renamed property
+        assertEquals("{\"renamedProp\":\"someValue\"}", json);
+
+        // Should be able to deserialize back (setter is ignored, so field remains default)
+        Test5398 result = MAPPER.readValue(json, Test5398.class);
+        assertNotNull(result);
+        // Since setter is ignored, the deserialized object should have the default value
+        assertEquals("someValue", result.getProp());
```
Comment (victornoel) [inline src/test/java/com/fasterxml/jackson/databind/introspect/JsonPropertyRename5398Test.java:44]: @cowtowncoder just a nitpick but here I think the test is too ambiguous, it would have been better to set original's `prop` to a different value than the default one, to validate that it's indeed the default value that is used and not the one coming from `json`.

I can submit a PR if you want :)

Comment (victornoel) [reply src/test/java/com/fasterxml/jackson/databind/introspect/JsonPropertyRename5398Test.java:44]: Ha! I tried and actually the comment 
```
// Since setter is ignored, the deserialized object should have the default value
```

Is incorrect, if I remove the default value from the class and set it manually just before calling `writeValueAsString`, then `result.getProp()` has the value "someValue".

I tested on 2.17 too and it was like that also.

Comment (victornoel) [reply src/test/java/com/fasterxml/jackson/databind/introspect/JsonPropertyRename5398Test.java:44]: And this behaviour is actually consistent with when we don't rename the prop (cf my examples in https://github.com/FasterXML/jackson-databind/issues/5398#issuecomment-3553051842). I proposed an improvement of this test here: https://github.com/FasterXML/jackson-databind/pull/5412
