### PR TITLE
Fix handling of ObjectId-property in JsonIdentityInfo for uniform deserialization

### LINKED ISSUE #3838: Difference in the handling of `ObjectId-property` in `JsonIdentityInfo` depending on the deserialization route.
**Describe the bug**
This is the problem reported in https://github.com/FasterXML/jackson-module-kotlin/issues/378 .

Setter-based deserialization does not generate an error if the `id-property` is not present on the `JSON`.
On the other hand, instantiator-based deserialization throws a `MismatchedInputException` if the `id-property` is not present in the `JSON`.

**Version information**
It has been present since at least 2.9.9 and is reproduced in 2.15.0-rc1.

**To Reproduce**

```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

public class ObjectId {
    @JsonIdentityInfo(property = "id", generator = ObjectIdGenerators.PropertyGenerator.class)
    static class SetterBased {
        private String id;

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }

    @JsonIdentityInfo(property = "id", generator = ObjectIdGenerators.PropertyGenerator.class)
    static class CreatorBased {
        private final String id;

        @JsonCreator
        CreatorBased(@JsonProperty(value = "id") String id) {
            this.id = id;
        }

        public String getId() {
            return id;
        }
    }

    @Test
    void test() throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();

        // -> no error
        SetterBased t1 = mapper.readValue("{}", SetterBased.class);
        System.out.println(t1.id); // -> null

        // -> MismatchedInputException thrown
        CreatorBased t2 = mapper.readValue("{}", CreatorBased.class);
    }
}
```

**Expected behavior**
It would be correct to be one of the following summarized below.
https://github.com/FasterXML/jackson-module-kotlin/issues/378#issuecomment-1477141827

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by JooHyukKim**
### Description

- Fix issue with object ID handling during setter-based deserialization. 
- Closes #3838.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you for providing this @JooHyukKim ! I hope to find time to review it; looks straight-forward enough.

File: src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java [hunk 1]
```diff
@@ -367,6 +367,15 @@ public Object deserializeFromObject(JsonParser p, DeserializationContext ctxt) t
...
         p.setCurrentValue(bean);
+
+        // [databind#3838]: Uniform handling of missing objectId
+        if (_objectIdReader != null) {
+            // check if there are any properties present in the JSON object
+            if (!p.hasCurrentToken() || p.getCurrentToken() == JsonToken.END_OBJECT) {
+            // throw an error here since there are no properties in the JSON object
+                ctxt.reportUnresolvedObjectId(_objectIdReader, bean);
+            }
+        }
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java:378]: Quick note: I think this should probably be moved after following block (`if (p.canReadObjectId()) ...`) since that handles "native" Object Ids (mostly for YAML).

File: src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java [hunk 2]
```diff
@@ -367,6 +367,15 @@ public Object deserializeFromObject(JsonParser p, DeserializationContext ctxt) t
         final Object bean = _valueInstantiator.createUsingDefault(ctxt);
         // [databind#631]: Assign current value, to be accessible by custom deserializers
         p.setCurrentValue(bean);
+
+        // [databind#3838]: Uniform handling of missing objectId
+        if (_objectIdReader != null) {
+            // check if there are any properties present in the JSON object
+            if (!p.hasCurrentToken() || p.getCurrentToken() == JsonToken.END_OBJECT) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java:379]: Actually... no, I don't think this is right. Where does this logic come from? Is it based on similar pattern somewhere, or just trying to see if it resolves specific failing test case?

Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java:379]: @JooHyukKim Let me try to go back to code -- maybe I am confused.
There are 2 parts to Object Id handling basically -- inclusion of Object Id as part of JSON Object (additional property); and then Object Id Reference (either scalar id or, in very limited cases, single-propert Object). So I want to make sure I understand which parts are being processed.

I'll add another note wrt timing/

**Comment by cowtowncoder** [comment]
Ok: due to timing -- I REALLY want to close out 2.15.0, and need to publish -rc3 -- I will not include this PR in 2.15.0 just to reduce risk. I will try to review & give feedback, but change itself most likely needs to go in 2.16. That gives us more time to make sure changes align with architecture & overall design.

**Comment by cowtowncoder** [comment]
This PR seems to be in bit of messed up state?

**Comment by cowtowncoder** [comment]
@JooHyukKim Actually now diffs look good. Not sure what I was seeing earlier :)

File: src/test/java/com/fasterxml/jackson/databind/deser/JsonIdentityInfoIdProperty3838Test.java [hunk 3]
```diff
@@ -0,0 +1,197 @@
+package com.fasterxml.jackson.databind.deser;
```
Comment (cowtowncoder) [inline src/test/java/com/fasterxml/jackson/databind/deser/JsonIdentityInfoIdProperty3838Test.java:1]: Needs to go under `...deser.objectid` but I can move it after merge if necessary.

File: src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java [hunk 4]
```diff
@@ -373,6 +373,10 @@ public Object deserializeFromObject(JsonParser p, DeserializationContext ctxt) t
                 _handleTypedObjectId(p, ctxt, bean, id);
             }
         }
+        // [databind#3838]: since 2.16 Uniform handling of missing objectId
+        if (_objectIdReader != null && p.getCurrentToken() == JsonToken.END_OBJECT) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java:377]: Ahhhhhh. It is only for the specific case of empty JSON Object. That's the piece I was missing, wondering how could this be safe. I'll update comment and

**Review by cowtowncoder — APPROVED** [review]

File: src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java (hunk 4 above)
Comment (JooHyukKim) [reply src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java:377]: > It is only for the specific case of empty JSON Object

Looking back, making a comment about the empty part would have made things clearer 😄 I will add updating comment (or checking that comment was made)  to my todo list also 👍🏻👍🏻

File: src/test/java/com/fasterxml/jackson/databind/deser/JsonIdentityInfoIdProperty3838Test.java (hunk 3 above)
Comment (JooHyukKim) [reply src/test/java/com/fasterxml/jackson/databind/deser/JsonIdentityInfoIdProperty3838Test.java:1]: Seems to be done by [this commit](https://github.com/FasterXML/jackson-databind/commit/998ca54978c3bcedc90398c2303acffa2f6ff63c#diff-0e6a39d906c028115b3ceb46d470ec298533705bd940973e6a8b5a7803abe2d0), but in `...objectid` packge. Moving on.

Comment (cowtowncoder) [reply src/test/java/com/fasterxml/jackson/databind/deser/JsonIdentityInfoIdProperty3838Test.java:1]: yes. And you are right, no "deser" in there, my bad.
