### PR TITLE
Fix #5309, better message for `DoubleNode.getIntValue()` exception.

### LINKED ISSUE #5309: Confusing exception for `DoubleNode` to `Integer` conversion in Jackson 3
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When having a DoubleNode with decimal value doing a `ObjectMapper.treeToValue(doubleNode, Integer.class)` in 2.x 2.718 results in `2` but in 3.x the fractional part is checked which fails the conversion to Integer.

The returned exception for the conversion in 3.x is:
`tools.jackson.core.exc.InputCoercionException: Numeric value (2.718) out of range of `int` (-2147483648 - 2147483647)`

This was confusing in that the value is easily inside the range and the issue is actually that the value has a fractional part marking the canConvertToInt as false due to it not being able to convertToExactIntegral.

To lessen the confusion of this conversion error it would be good if the exception would say clearly that it failed due to the fractional value being present and not because the value is out of range.

### Version Information

3.0.0-rc9

### Reproduction

```java
@Test
public void double_to_int_conversion_failure {
    ObjectMapper mapper = new ObjectMapper();

    JsonNode jsonNode = mapper.valueToTree(2.718);

    mapper.treeToValue(jsonNode, Integer.class);
}
``` 

### Expected behavior

The exception should highlight the actual reason for the failure.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JooHyukKim**

### CODE REVIEW

File: src/main/java/tools/jackson/databind/node/TreeTraversingParser.java [hunk 1]
```diff
@@ -298,6 +299,13 @@ public float getFloatValue() throws InputCoercionException {
     public int getIntValue() throws InputCoercionException {
         final NumericNode node = (NumericNode) currentNumericNode(NR_INT);
         if (!node.canConvertToInt()) {
+            // [databind#5309] Misleading exception message for DoubleNode to Int value coversion.
+            if (node.isFloatingPointNumber()) {
+                _reportInvalidNumber(String.format(
+                        "Failed to parse Int value from '%s' of type %s", node.toString(),
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/node/TreeTraversingParser.java]: The idea is right, but need to work on wording: "convert" instead of "parse" I think.

File: src/test/java/tools/jackson/databind/node/DoubleNodeToIntExceptionMessage5309Test.java [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+    @Test
+    public void exceptionMessageTest()
+    {
+        ObjectMapper mapper = JsonMapper.builder().build();
+        JsonNode jsonNode = mapper.valueToTree(2.718);
+
+        try {
+            Integer a = mapper.treeToValue(jsonNode, Integer.class);
+            fail("Should have thrown an exception");
+        } catch (Exception e) {
```
Comment (cowtowncoder) [inline src/test/java/tools/jackson/databind/node/DoubleNodeToIntExceptionMessage5309Test.java]: Should catch more specific type, not just any `Exception`.

File: src/main/java/tools/jackson/databind/node/TreeTraversingParser.java [hunk 3]
```diff
@@ -298,6 +299,13 @@ public float getFloatValue() throws InputCoercionException {
     public int getIntValue() throws InputCoercionException {
         final NumericNode node = (NumericNode) currentNumericNode(NR_INT);
         if (!node.canConvertToInt()) {
+            // [databind#5309] Misleading exception message for DoubleNode to Int value coversion.
+            if (node.isFloatingPointNumber()) {
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/node/TreeTraversingParser.java]: Not safe assumption: some FPs fine (one without fraction), could be out of range.

File: src/main/java/tools/jackson/databind/node/TreeTraversingParser.java [hunk 4]
```diff
@@ -298,6 +299,13 @@ public float getFloatValue() throws InputCoercionException {
...
+                _reportInvalidNumber(String.format(
+                        "Failed to parse Int value from '%s' of type %s", node.toString(),
+                        node.getClass().getSimpleName()));
+            }
+            // .... otherwise fallback to existing behavior
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/node/TreeTraversingParser.java]: Need the same long-conversion as well.

File: src/main/java/tools/jackson/databind/node/TreeTraversingParser.java (hunk 3 above)
Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/node/TreeTraversingParser.java]: Will use `!node.canConvertToExactIntegral()` instead

File: src/main/java/tools/jackson/databind/node/TreeTraversingParser.java (hunk 4 above)
Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/node/TreeTraversingParser.java]: Done.
