### PR TITLE
Record constructor with single write-only parameter should result in properties-based creator, to fix #3897

### LINKED ISSUE #3897: 2.15.0 breaks deserialization when POJO/Record only has a single field and is marked `Access.WRITE_ONLY`
**Describe the bug**

Trying to deserialize the following Java Record throws `MismatchedInputException`

```java

public record Example(@JsonProperty(access = JsonProperty.Access.WRITE_ONLY) String value) {
}

```

Same issue happens with at least a regular class and `@JsonCreator` constructor

Adding any other fields fixes the issue, even if those fields are also WRITE_ONLY fields.

Stacktrace:

```
Cannot construct instance of `foo.bar.baz.Example` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"value": "aaa"}"; line: 1, column: 2]
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `foo.bar.baz.Example` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"value": "aaa"}"; line: 1, column: 2]
	at app//com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at app//com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1739)
	at app//com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1364)
	at app//com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1424)
	at app//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at app//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at app//com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at app//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at app//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at app//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
```

**Version information**
2.15.0

**To Reproduce**
Using the above record definition with plain ObjectMapper throws the above exception

```java
new ObjectMapper().readValue("{\"value\": \"aaa\"}", Example.class);
```

**Expected behavior**
With 2.14.2 value was successfully deserialized.

### PR DESCRIPTION
**Pull request by yihtserns**
Currently, this is how a 1-arg constructor parameter is evaluated (priority according to the listed order):

| | What | Properties-based | Delegating |
|---|---|---|---|
|1| Constructor parameter has `@JsonProperty("<some name>")` | ✅ | |
|2| Any field has `@JsonValue` | | ✅ |
|3| Any getter method has `@JsonValue` | | ✅ |
|4| Constructor parameter has `@JacksonInject` | ✅ | |
|5| Constructor parameter name matched a getter method name | ✅ | |
|6| Constructor parameter name matched a field name | ✅ | |
|7| Default | | ✅ |

This PR changes that to:
| | What | Properties-based | Delegating |
|---|---|---|---|
|1| Constructor parameter has `@JsonProperty("<some name>")` | ✅ | |
|2| Any field has `@JsonValue` | | ✅ |
|3| Any getter method has `@JsonValue` | | ✅ |
|4| Constructor parameter has `@JacksonInject` | ✅ | |
|5| Constructor parameter name matched a getter method name | ✅ | |
|6| Constructor parameter name matched a field name | ✅ | |
|6| Is Record canonical constructor parameter `⭐ NEW` | ✅ | |
|8| Default | | ✅ |

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@yihtserns Do you think this would be safe enough to go in 2.15(.1)? I think I'd merge it if you are comfortable.

File: src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java [hunk 1]
```diff
@@ -1032,6 +1032,10 @@ private boolean _checkIfCreatorPropertyBased(BeanDescription beanDesc,
                 }
             }
         }
+        // [databind#3897]: Record canonical constructor will have implicitly named propDef
+        if (propDef != null && !propDef.isExplicitlyNamed() && beanDesc.isRecordType()) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java:1036]: Minor thing but can remove first check and move inside previous if-block (which checks for `propDef != null`).

**Review by cowtowncoder — APPROVED** [review]

File: src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java (hunk 1 above)
Comment (yihtserns) [reply src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java:1036]: Actually I agonized over these 2 options:
<table>
  <thead>
  <tr>
    <th>Option 1</th>
    <th>Option 2</th>
  </tr>
  </thead>
  <tbody>
    <tr>
        <td>
<pre>
private boolean _checkIfCreatorPropertyBased(...) {
    ...
    if (propDef != null) {
        ...
        if (implName != null && !implName.isEmpty()) {
            if (propDef.couldSerialize()) {
                return true;
            } else if (beanDesc.isRecordType()) {
                // [databind#3897]: Record canonical constructor will have implicitly named propDef
                return true;
            }
        }
    }
    // in absence of everything else, default to delegating
    return false;
}
</pre>
        </td>
        <td>
<pre>
private boolean _checkIfCreatorPropertyBased(...) {
    ...
    if (propDef != null) {
        ...
    }
    // [databind#3897]: Record canonical constructor will have implicitly named propDef
    if (propDef != null && !propDef.isExplicitlyNamed() && beanDesc.isRecordType()) {
        return true;
    }
    // in absence of everything else, default to delegating
    return false;
}
</pre>
        </td>
    </tr>
  </tbody>
</table>

I chose Option 2 because it looks easier to understand with just a quick glance.  But I'll change it if you feel strongly about Option 1.

**Comment by yihtserns** [comment]
> If you are ok with that, would it be possible to re-based/re-create against 2.15 branch?

Actually the branch was created from `2.15`, I didn't notice the PR is against `2.16`.  Let me change that.
