### PR TITLE
Fix #3188: Skip unknown enum keys in Map deserialization with READ_UNKNOWN_ENUM_VALUES_AS_NULL

### LINKED ISSUE #3188: Skip unknown keys in Map deserialization
(Transferred from https://github.com/FasterXML/jackson-dataformats-text/issues/277)

When serializing to `Map` or `EnumMap` it is impossible to skip unknown keys. This is hardly an issue with vanilla String keys, but it becomes relevant with custom KeyDeserializers that map the original String keys to a smaller key universe, such as an Enum. If the source has String keys for which no mapping exists deserialization will throw an exception.

There are some options to work around this (e.g. `DeserilizationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL`) but these are not very clean and will not cover all situations. It also gives way to NULL keys in Maps, which is mostly harmless, but questionable (https://stackoverflow.com/a/45210670). Newer map implementations, including Guava's, do not allow NULL keys.

The other workaround is to define a default value, that will serve as a Map key, if the key could not be deserialized. This approach leads to situations, where clients may wish to clean up the default element from the deserialized Map in a post-processing step.

The cleanest solution, that we do not have yet, is to tell Jackson to skip unknown Map keys entirely. Since Map keys usually have the semantics of (JSON) properties, a mechanism like `@JsonIgnoreProperties` or `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES=true|false` would be desirable

The latest (endorsed) proposal in the other issue introduced a new `DeserializationFeature.SKIP_UNKNOWN_MAP_KEYS=true|false` feature that should trigger the skipping logic in the Map deserialization process.

### PR DESCRIPTION
**Pull request by dlwldnjs1009**
Fix #3188

### Problem
With `EnumFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL` enabled:
- `EnumMap` skips entries with unknown enum keys
- `Map`/`HashMap` inserts a `null` key

### Change
Add internal (package-private) capability interface `NullKeySkippable`.
`JDKKeyDeserializer.EnumKD` implements it and signals when `null` keys should skip the entry.
`MapDeserializer` checks the capability and skips the whole entry when the key deserializes to `null`.

No enum-specific logic added to `MapDeserializer`. No public API change.

### Tests
- `Map<Enum,V>`, `HashMap<Enum,V>`, `LinkedHashMap<Enum,V>`: unknown keys are skipped; no `null` key inserted
- interleaved unknown keys
- `@JsonDeserialize(as=HashMap.class)` case
- default behavior unchanged (still fails without the feature)

Closes #3188

### CODE REVIEW

File: src/main/java/tools/jackson/databind/deser/jdk/MapDeserializer.java [hunk 1]
```diff
@@ -502,18 +502,25 @@ protected final Map<Object,Object> _readAndBind(JsonParser p, DeserializationCon
         } else {
             JsonToken t = p.currentToken();
             if (t != JsonToken.PROPERTY_NAME) {
-                if (t == JsonToken.END_OBJECT) {
-                    return result;
-                }
-                ctxt.reportWrongTokenException(this, JsonToken.PROPERTY_NAME, null);
+                _checkIsEndObject(ctxt, t);
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/jdk/MapDeserializer.java:505]: Extracted check to unify handling.

**Review by cowtowncoder — APPROVED** [review]
LGTM
