### PR TITLE
Fix #4771: Support OBJECT shape for QNAME serialization and deserialization.

### LINKED ISSUE #4771: `QName` (de)serialization ignores prefix
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

QName (de)serialization ignores prefix, because it uses [QName#toString()](https://docs.oracle.com/en/java/javase/21/docs/api/java.xml/javax/xml/namespace/QName.html#toString()) and [QName#valueOf(java.lang.String)](https://docs.oracle.com/en/java/javase/21/docs/api/java.xml/javax/xml/namespace/QName.html#valueOf(java.lang.String)).

### Version Information

2.17.2

### Reproduction

```java
        QName qname = new QName("http://test.com", "test", "p");
        System.out.println(qname.getPrefix()); // <- p
        ObjectMapper mapper = new ObjectMapper();
        String ser = mapper.writeValueAsString(writer, qname);
        System.out.println(ser); // <- "{http://test.com}test"
        QName result = mapper.readValue(ser, QName.class);
        System.out.println(result.getPrefix()); // <- empty string
```

### Expected behavior

QName prefix is preserved.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mcvayc**
This commit fixes #4771 by supporting the JsonFormat OBJECT shape during serialization and deserialization.

### CODE REVIEW

**Comment by mcvayc** [comment]
I'm sorry about the whitespace changes.  I'll see if I can fix those without another round of approvals.

**Comment by cowtowncoder** [comment]
Great! I'll hope to review this soon, maybe tomorrow. And since we have CLA already, can proceed with merge if all goes well! Thank you in advance.

**Comment by mcvayc** [comment]
I just rebased and fixed some of the unnecessary whitespace formatting issues.

File: src/main/java/com/fasterxml/jackson/databind/ext/CoreXMLDeserializers.java [hunk 1]
```diff
@@ -92,16 +92,50 @@ public Std(Class<?> raw, int kind) {
...
             return super.deserialize(p, ctxt);
         }
 
+        private QName _parseQNameObject(JsonParser p, DeserializationContext ctxt)
+            throws IOException
+        {
+            JsonNode tree = ctxt.readTree(p);
+
+            if (!tree.has("localPart")) {
+                throw new JsonParseException("QName is missing required field: localPart");
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/ext/CoreXMLDeserializers.java:117]: `JsonParseException` should be reserved for JSON decoding problems: here we need a `JsonMappingException` subtype. Usually via `DeserializationContext`, let me see what method should be used. Ideally `localPart` would also be included in quotes (since that's done with other messages)

Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/ext/CoreXMLDeserializers.java:117]: Ok, method to call is:

```
    public <T> T reportInputMismatch(Class<?> targetType,
            String msg, Object... msgArgs) throws JsonMappingException
```

I can maybe change it.

Comment (cowtowncoder) [reply src/main/java/com/fasterxml/jackson/databind/ext/CoreXMLDeserializers.java:117]: Will change.

File: src/main/java/com/fasterxml/jackson/databind/ext/CoreXMLSerializers.java [hunk 2]
```diff
@@ -116,4 +120,55 @@ protected Calendar _convert(XMLGregorianCalendar input) {
...
+        public final void serializeWithType(QName value, JsonGenerator g, SerializerProvider provider,
+                                            TypeSerializer typeSer)
+            throws IOException
+        {
+            g.writeObject(value);
+        }
+
+        @Override
+        public void acceptJsonFormatVisitor(JsonFormatVisitorWrapper visitor, JavaType typeHint) throws JsonMappingException {
+            visitor.expectBooleanFormat(typeHint);
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/ext/CoreXMLSerializers.java:171]: Not boolean, object, will change.

**Comment by mcvayc** [comment]
Thanks, @cowtowncoder.  I'm sorry you had to make so many changes but I'm grateful for your fixes and for merging this.  I will learn from this so subsequent PRs will be more polished.

**Comment by cowtowncoder** [comment]
@mcvayc Not at all -- you had a pretty clean PR & figured out all the pieces very well.
I don't mind minor polish in somewhat complicated area. So don't feel bad at all.

And thank you for providing the improvement! That's how things improve.
