### PR TITLE
Fix #5897: skip TokenBuffer allocation for unknown properties in records

### LINKED ISSUE #5897: Excessive `TokenBuffer` allocations when deserializing records
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When deserializing objects whose construction goes through a property-based creator – which includes every Java record, since records always use the canonical constructor – `BeanDeserializer._deserializeUsingPropertyBased` allocates a fresh `TokenBuffer` on every call. Each `TokenBuffer` allocates at least one `Segment` (an `Object[]` plus a token-type array). For workloads that stream many small records, this shows up prominently in allocation profiles.

Code path:

```
  BeanDeserializer.deserialize
    → BeanDeserializerBase.deserializeFromObjectUsingNonDefault
      → BeanDeserializer._deserializeUsingPropertyBased
        → DeserializationContext.bufferForInputBuffering
          → TokenBuffer.forBuffering   // fresh allocation per object
```

Format-independent — reproduces with JSON, CSV, or any other backend. Since records are now the idiomatic way to model immutable DTOs in Java and unconditionally force this path, users migrating DTOs from classes-with-setters to records see a regression in allocation rate with no change in code shape.

The buffer's lifetime is bounded to _deserializeUsingPropertyBased, so reusing it (with `RecyclerPool`?) may be feasible.

### Version Information

3.1.1

### Reproduction

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by phraktle**
Partial fix for #5897.

Skips allocating a `TokenBuffer` for unknown properties in `_deserializeUsingPropertyBased` when the declared bean type is final, `FAIL_ON_UNKNOWN_PROPERTIES` is disabled, and no `DeserializationProblemHandler` is registered. Applied to `BeanDeserializer` and `BuilderBasedDeserializer`.

Benchmark is in line with `@JsonIgnoreProperties(ignoreUnknown=true)`, ~25% improvement in allocation/runtime.

### CODE REVIEW

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java [hunk 1]
```diff
@@ -1884,6 +1884,20 @@ protected Object handleUnknownProperties(DeserializationContext ctxt,
...
+    /**
+     * True when an unknown property may be skipped at the source rather than
+     * buffered: either {@link #_ignoreAllUnknown} is set, or (per [databind#5897])
+     * the bean type is final and unknowns would be silently discarded anyway.
+     */
+    protected final boolean _shouldSkipUnknowns(DeserializationContext ctxt) {
+        if (_ignoreAllUnknown) {
+            return true;
+        }
+        return _beanType.isFinal()
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java:1909]: Why is `final` check added? Why is it necessary?

**Comment by cowtowncoder** [comment]
I'll need to think this through, but I like the possibility of improvement.

One thing we'll need before merging (if not yet done; I tried to verify but may have missed) is CLA, from here:

https://github.com/FasterXML/jackson/blob/main/CLA-jackson-2026.pdf

it only needs to be sent once before the first contribution & is good for all future PRs.
The usual way is to print, fill & sign, scan/photo, email to `cla` at fasterxml dot com.

Looking forward to merging this!

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializer.java [hunk 2]
```diff
@@ -814,8 +815,9 @@ protected Object _deserializeUsingPropertyBased(final JsonParser p, final Deseri
             }
             // 29-Mar-2021, tatu: [databind#3082] May skip collection if we know
             //    they'd just get ignored (note: any-setter handled above; unwrapped
-            //    properties also separately handled)
-            if (_ignoreAllUnknown) {
+            //    properties also separately handled). Covers both annotation-driven
+            //    `_ignoreAllUnknown` and [databind#5897] config-driven skip.
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializer.java]: Should inline brief explanation of "config-driven" skip...

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java:1909]: Ok, asked Claude and it pointed out that this is for sub-classing for Polymorphic deserialization, during which buffered content would be needed.

**Comment by phraktle** [comment]
> I'll need to think this through, but I like the possibility of improvement.
> 
> One thing we'll need before merging (if not yet done; I tried to verify but may have missed) is CLA, from here:
> 
> https://github.com/FasterXML/jackson/blob/main/CLA-jackson-2026.pdf
> 
> it only needs to be sent once before the first contribution & is good for all future PRs. The usual way is to print, fill & sign, scan/photo, email to `cla` at fasterxml dot com.
> 
> Looking forward to merging this!

Thanks, submitted the CLA!

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializer.java (hunk 2 above)
Comment (phraktle) [reply src/main/java/tools/jackson/databind/deser/bean/BeanDeserializer.java]: comment improved

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java [hunk 3]
```diff
@@ -1884,6 +1884,20 @@ protected Object handleUnknownProperties(DeserializationContext ctxt,
         return bean;
     }
 
+    /**
+     * True when an unknown property may be skipped at the source rather than
+     * buffered: either {@link #_ignoreAllUnknown} is set, or (per [databind#5897])
+     * the bean type is final and unknowns would be silently discarded anyway.
+     */
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java:1904]: Add `@since 3.2`

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java [hunk 4]
```diff
@@ -1884,6 +1884,20 @@ protected Object handleUnknownProperties(DeserializationContext ctxt,
         return bean;
     }
 
+    /**
+     * True when an unknown property may be skipped at the source rather than
+     * buffered: either {@link #_ignoreAllUnknown} is set, or (per [databind#5897])
+     * the bean type is final and unknowns would be silently discarded anyway.
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java]: Still doesn't explain why final type matters (why would unknown props be dropped in just that case). AFAIK this is just for polymorphic deser case... but would some tests fail if this check was removed?

File: src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java [hunk 5]
```diff
@@ -1884,6 +1884,27 @@ protected Object handleUnknownProperties(DeserializationContext ctxt,
...
+     * {@link DeserializationProblemHandler}s are registered, and
+     * {@link DeserializationFeature#FAIL_ON_UNKNOWN_PROPERTIES} is disabled.
+     *
+     * @since 3.2
+     */
+    protected final boolean _shouldSkipUnknowns(DeserializationContext ctxt) {
+        if (_ignoreAllUnknown) {
+            return true;
+        }
+        return _beanType.isFinal()
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/bean/BeanDeserializerBase.java:1909]: For funsies I commented out `isFinal` check, and that does lead to failures. So it is necessary.

**Review by cowtowncoder — APPROVED** [review]
