### PR TITLE
Regression fix for #4741 `Include.NON_DEFAULT` setting used on POJO, empty values are not included in json if default is null

### LINKED ISSUE #4741: When `Include.NON_DEFAULT` setting is used on POJO, empty values are not included in json if default is `null`
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

After upgrading to 2.18.0, empty Strings/objects are no longer included in json output if NON_DEFAULT annotation is used on the class and the default value is null. This is possibly related to fixing https://github.com/FasterXML/jackson-databind/issues/4464
As far as I can understand, the documentation states that the test below should pass, as it does in 2.17.1.
image

### Version Information

2.18.0

### Reproduction

```java
@Test
void testSerialization() throws JsonProcessingException {
    MyString input = new MyString();
    input.setValue("");
    ObjectMapper objectMapper = new ObjectMapper();
    String json = objectMapper.writeValueAsString(input);
    MyString output = objectMapper.readValue(json, MyString.class);
    assertEquals(input.getValue(), output.getValue());
}

@JsonInclude(JsonInclude.Include.NON_DEFAULT)
@Data
public static class MyString {
    private String value = null;
}
``` 

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JooHyukKim**
demonstrates "possible" solution that resolves #4741

### CODE REVIEW

File: src/main/java/com/fasterxml/jackson/databind/ser/PropertyBuilder.java [hunk 1]
```diff
@@ -182,8 +182,12 @@ protected BeanPropertyWriter buildWriter(SerializerProvider prov,
             }
             if (valueToSuppress == null) {
                 suppressNulls = true;
-                // [databind#4464] NON_DEFAULT does not work with NON_EMPTY for custom serializer
-                valueToSuppress = BeanPropertyWriter.MARKER_FOR_EMPTY;
+                // [databind#4471] Different behavior when Include.NON_DEFAULT
+                //   setting is used on POJO vs global setting, as per documentation.
+                if (!_useRealPropertyDefaults) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/ser/PropertyBuilder.java:187]: Instead of re-checking configuration settings, let's rely on "_useRealPropertyDefaults" which means that POJO settings are in use (not global-, per-type or property)?

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
@JooHyukKim I figured out a simpler check which I _think_ works. But wanted to ask WDYT before merging. All tests pass which is good.

File: src/main/java/com/fasterxml/jackson/databind/ser/PropertyBuilder.java (hunk 1 above)
Comment (JooHyukKim) [reply src/main/java/com/fasterxml/jackson/databind/ser/PropertyBuilder.java:187]: Makes sense 👌🏼

**Comment by JooHyukKim** [comment]
I like the simpler check 🙏🏼 LGTM! @cowtowncoder

**Comment by cowtowncoder** [comment]
@JooHyukKim Thank you for taking a lead on this! I'll go ahead and merge soon.
