### PR TITLE
Fix #1654 (yet another attempt)

### LINKED ISSUE #1654: `@JsonTypeInfo(use = JsonTypeInfo.Id.NONE)` override on property is ignored
NOTE: below is the original report, but title changed to reflect evolution of the issue.

-------

Tested versions: 2.9.0.pr3, 2.8.8 and 2.0.1

Expected behavior: Jackson respects `@JsonDeserialize(contentUsing=...)` even if the content's type is determined via `@JsonTypeInfo`.
Actual behavior: `@JsonDeserialize(contentUsing=...)` is ignored.

The following example demonstrates the issue. 
The expected output is "ok". 
The observed output is empty. BarDeserializer is never called (nor constructed for that matter).

Removing the `@JsonTypeInfo` line "fixes" the example.

```
public class Test {
  static class BarDeserializer extends JsonDeserializer<Bar> {
    @Override
    public Bar deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
      System.out.println("ok");
      return p.readValueAs(Bar.class);
    }
  }

  @JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
  static class Bar {
    public int dummy;
  }

  static class Foo {
    @JsonDeserialize(contentUsing = BarDeserializer.class)
    public List<Bar> bars;
  }

  public static void main(String[] args) throws IOException {
    Foo foo = new Foo();
    foo.bars = Arrays.asList(new Bar());

    ObjectMapper om = new ObjectMapper();
    om.readValue(om.writeValueAsString(foo), Foo.class);
  }
}

```

### PR DESCRIPTION
**Pull request by cowtowncoder**
So, here's a bit more comprehensive attempt at #1654, assisted by Claude.

### CODE REVIEW

File: src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeDeserializer.java [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+    }
+
+    @Override
+    public TypeDeserializer forProperty(BeanProperty prop) {
+        return this;
+    }
+
+    @Override
+    public JsonTypeInfo.As getTypeInclusion() {
+        return JsonTypeInfo.As.PROPERTY;
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeDeserializer.java]: Not sure what should be indicated but... maybe not this.

File: src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeSerializer.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+            SerializationContext ctxt, WritableTypeId typeId)
+        throws JacksonException
+    {
+        // Write the value start token if needed, but NO type information
+        if (typeId.valueShape == JsonToken.START_OBJECT) {
+            g.writeStartObject(typeId.forValue);
+        } else if (typeId.valueShape == JsonToken.START_ARRAY) {
+            g.writeStartArray();
+        }
+        // Mark as "already written" to prevent suffix from trying to close
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeSerializer.java]: Actually, indicate that:

1. Start marker (part of value) was written but
2. No wrapper was written.

File: src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java [hunk 3]
```diff
@@ -162,6 +170,10 @@ public TypeSerializer findPropertyContentTypeSerializer(SerializationContext ctx
             return findTypeSerializer(ctxt, contentType,
                     ctxt.introspectClassAnnotations(contentType.getRawClass()));
         }
+        // [databind#1654]: Explicit `@JsonTypeInfo(Id.NONE)` should block class-level type info
+        if (b == NO_RESOLVER) {
+            return tools.jackson.databind.jsontype.impl.NoOpTypeSerializer.instance();
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/TypeResolverProvider.java]: Use import, not FQN

File: src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeDeserializer.java (hunk 1 above)
Comment (JacksonJang) [reply src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeDeserializer.java]: Would adding NONE as a JsonTypeInfo.As value be considered undesirable?

File: src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeDeserializer.java [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+        _defaultDeserializer = null;
+    }
+
+    private NoOpTypeDeserializer(JavaType baseType,
+            ValueDeserializer<Object> defaultDeserializer) {
+        _baseType = baseType;
+        _defaultDeserializer = defaultDeserializer;
+    }
+
+    public NoOpTypeDeserializer withDefaultImpl(ValueDeserializer<Object> deser) {
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeDeserializer.java]: Name seems wrong.

File: src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeDeserializer.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/tools/jackson/databind/jsontype/impl/NoOpTypeDeserializer.java]: That could have backwards-compatibility effects, although nothing immediately obvious.
But for now let's work without such option.

**Comment by cowtowncoder** [comment]
Ok, original test for #1654 passes. But I am not sure it's right at all -- it:

1. Has no custom serializer use
2. Custom deserializer does not seem to be used?

So handling of `JsonTypeInfo.Id.NONE` is fixed, but lookup for custom deserializer appears to be missing; and probably serializer too.

**Comment by JacksonJang** [comment]
Thanks for the follow-up!

I checked the behavior locally with the debugger, 
and from what I can see both the custom serializer and the custom deserializer
**are correctly used** when `JsonTypeInfo.Id.NONE` is applied.

1. **NoOpTypeSerializer**
   - Breakpoint hits when serializing the target type  
Serialize

2. **NoOpTypeDeserializer**
   - Breakpoint hits during deserialization and the call stack correctly flows into the custom deserializer  
Deserialize

I've attached the debugger screenshots showing both breakpoints being triggered.

**Comment by cowtowncoder** [comment]
@JacksonJang These are custom _type_ deserializer/serializer (`TypeDeserializer` / `TypeSerializer`) and they are called ok as per fix.

But what seems to be missing are _value_ (de)serializers (`ValueDeserializer` / `ValueSerializer`); added using `@Json[De]Serialize(contentUsing = MyValue[De]Serializer.class)`.

So there are 2 different things.

Test has

```
        @JsonDeserialize(contentUsing = Value1654Deserializer.class)
        @JsonTypeInfo(use = JsonTypeInfo.Id.NONE)
        public List<Value1654> values;
```

but is missing 

```
    @JsonSerialize(contentUsing = Value1654Serializer.class)
```

Hope this helps!

**Comment by cowtowncoder** [comment]
I think issue is probably best split in two: one wrt `@JsonTypeInfo(use = JsonTypeInfo.Id.NONE)` (now fixed) and follow-up for value (de)serializer overrides.

**Comment by JacksonJang** [comment]
Correction on my previous comment:
I re-checked the test case and found that the assertion in noTypeInfoOverrideDeser is incorrect.
The custom deserializer always returns `new Value1654(13)`, but the test expects `x = 7`:

```
assertEquals(7, unResult.values.get(1).x);
```

If the custom deserializer is actually being invoked, both elements should have x = 13. The current assertion would only pass if the custom deserializer is not being used.

I'll fix the incorrect assertion (x=7 → x=13) and update the test to properly verify the custom deserializer invocation.

**Comment by cowtowncoder** [comment]
@JacksonJang Yes, but do note split between `TypeDeserializer` and `ValueDeserializer` (and same on serialization side). Former handles Type Ids (wrt `@JsonTypeInfo`), latter actual value itself.

So there are at least 2 aspects to resolve. This PR addresses one.

**Comment by JacksonJang** [comment]
@cowtowncoder 
I’ve just submitted the PR with the code that successfully passed the latest test run.
Please take a look when you have a moment.

https://github.com/FasterXML/jackson-databind/pull/5479
