### PR TITLE
Fix #1419: allow Map.Entry shape/format overrides

### LINKED ISSUE #1419: `JsonFormat.Shape.POJO`  does not work for `Map.Entry` via property annotation
(note: follow-up of #865)

Although use of class annotations works for `Map.Entry` serialization and deserialization, per-property annotation doesn't. The reason for this is that it significantly easier to block default (de)serialization from being used when class has the annotation; for per-property annotation this has to be done from within `createContextual()`.

### PR DESCRIPTION
**Pull request by cowtowncoder**
Implements #1419.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Not loving replicating of subset of `BeanDeserializer` but apparently less complex than alternatives.

File: src/main/java/tools/jackson/databind/deser/jdk/MapEntryDeserializer.java [hunk 1]
```diff
@@ -232,6 +267,75 @@ public Map.Entry<Object,Object> deserialize(JsonParser p, DeserializationContext
...
+        if (t == JsonToken.START_OBJECT) {
+            t = p.nextToken();
+        } else if (t != JsonToken.PROPERTY_NAME && t != JsonToken.END_OBJECT) {
+            if (t == JsonToken.START_ARRAY) {
+                return _deserializeFromArray(p, ctxt);
+            }
+            return (Map.Entry<Object,Object>) ctxt.handleUnexpectedToken(getValueType(ctxt), p);
+        }
+
+        final KeyDeserializer keyDes = _keyDeserializer;
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/jdk/MapEntryDeserializer.java]: This is actually wrong: `KeyDeserializer` is only good for JSON Object property names; here we need a proper `ValueDeserializer`...

File: src/main/java/tools/jackson/databind/deser/jdk/MapEntryDeserializer.java [hunk 2]
```diff
@@ -232,6 +267,75 @@ public Map.Entry<Object,Object> deserialize(JsonParser p, DeserializationContext
...
+                    wrapAndThrow(ctxt, e, Map.Entry.class, propName);
+                }
+            } else {
+                // Unknown property: check if we should fail or skip
+                handleUnknownProperty(p, ctxt, _containerType.getRawClass(), propName);
+            }
+
+            t = p.nextToken(); // move to next property or END_OBJECT
+        }
+
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/databind/deser/jdk/MapEntryDeserializer.java:513]: Missing checks for missing (absent) "key" or "value"...
