### PR TITLE
Fixed  #2215 - Support BigInteger and BigDecimal in StdValueInstantiator

### LINKED ISSUE #2215: Support BigDecimal in StdValueInstantiator
Currently using 2.9.6; have searched and don't see any planned changes in this area.

Basically, I would like this test to pass by default:

```java
private static class BigDecimalWrapper {
    public final BigDecimal value;
    public BigDecimalWrapper(BigDecimal value) { this.value = value; }
}
@Test
public void createFromBigDecimal() throws IOException {
    assertThat(new ObjectMapper().readValue("42.5", BigDecimalWrapper.class).value, is(new BigDecimal("42.5")));
}
```
the same way that this one does:
```java
private static class DoubleWrapper {
    public final Double value;
    public DoubleWrapper(Double value) { this.value = value; }
}
@Test
public void createFromDouble() throws IOException {
    assertThat(new ObjectMapper().readValue("42.5", DoubleWrapper.class).value, is(new Double("42.5")));
}
```

Currently, `StdValueInstantiator` does not support `BigDecimal` (or `BigInteger`) at all. I would like to add support for `BigDecimal` creators to `createFromDouble`, `createFromLong`, and `createFromInt` (and `BigInteger` creators to `createFromLong` and `createFromInt`) in `StdValueInstantiator` as widening conversions, the same way that `createFromInt` supports using long creators as a widening conversion.

### PR DESCRIPTION
**Pull request by upsidedownsmile**
(for #2215)

- Add BigInteger creator to StdValueInstantiator#createFromInt, StdValueInstantiator#createFromLong  StdValueInstantiator#createFromDouble for the case that number type is INT, LONG and DOUBLE respectively.
- Created StdValueInstantiator#createFromBigInteger and StdValueInstantiator#createFromBigDecimal and auxiliary methods(canCreateFrom..., configureFrom...) for the remaining cases, when number type is BIG_INTEGER and BIG_DECIMAL.
- Get the single argument creator inside BasicDeserealizerFactory#_handleSingleArgumentCreator and add C_BIG_INTEGER and C_BIG_DECIMAL types to CreatorCollector to represent each one.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Sounds good -- thank you very much for contributing this!

I need to re-read it once to see if I missed anything, but one thing I do need before merging is CLA from:

https://github.com/FasterXML/jackson/blob/master/MANUAL.md

and the common way is to print it, fill & sign, scan/photo, email to `info` at fasterxml dot com.
This only needs to be done once, before the first contribution.

Looking forward to merging this PR, thank you again!

**Comment by upsidedownsmile** [comment]
I'm glad to hear that.
I just sent the CLA to info@fasterxml.com.

**Comment by cowtowncoder** [comment]
CLA received, will do one last review, merge. Thank you very much for contributing this!

File: src/main/java/com/fasterxml/jackson/databind/deser/std/StdValueInstantiator.java [hunk 1]
```diff
@@ -345,37 +361,106 @@ public Object createFromInt(DeserializationContext ctxt, int value) throws IOExc
...
+            }
         }
+
+        return super.createFromLong(ctxt, value);
+    }
+
+    @Override
+    public Object createFromBigInteger(DeserializationContext ctxt, BigInteger value) throws IOException
+    {
+        if (_fromBigDecimalCreator != null) {
```
Comment (cowtowncoder) [inline src/main/java/com/fasterxml/jackson/databind/deser/std/StdValueInstantiator.java:411]: ... and here we have a bug. 

Which is not caught by test cases since numbers used do not extend beyond value range of `long` (for `BigInteger`), or, for `BigDecimal` as that is never really reported by JSON parser. Would be exposed by Smile codec, maybe some other binary codecs.
But I'll try fixing BigInteger case at least.
